// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="reconstruct_reconstruct,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu49dr-ffvf1760-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.704800,HLS_SYN_LAT=3961855,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=80255,HLS_SYN_LUT=33063,HLS_VERSION=2024_2}" *)

module reconstruct (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axi_scalar_data_AWVALID,
        s_axi_scalar_data_AWREADY,
        s_axi_scalar_data_AWADDR,
        s_axi_scalar_data_WVALID,
        s_axi_scalar_data_WREADY,
        s_axi_scalar_data_WDATA,
        s_axi_scalar_data_WSTRB,
        s_axi_scalar_data_ARVALID,
        s_axi_scalar_data_ARREADY,
        s_axi_scalar_data_ARADDR,
        s_axi_scalar_data_RVALID,
        s_axi_scalar_data_RREADY,
        s_axi_scalar_data_RDATA,
        s_axi_scalar_data_RRESP,
        s_axi_scalar_data_BVALID,
        s_axi_scalar_data_BREADY,
        s_axi_scalar_data_BRESP,
        m_axi_atomLocations_AWVALID,
        m_axi_atomLocations_AWREADY,
        m_axi_atomLocations_AWADDR,
        m_axi_atomLocations_AWID,
        m_axi_atomLocations_AWLEN,
        m_axi_atomLocations_AWSIZE,
        m_axi_atomLocations_AWBURST,
        m_axi_atomLocations_AWLOCK,
        m_axi_atomLocations_AWCACHE,
        m_axi_atomLocations_AWPROT,
        m_axi_atomLocations_AWQOS,
        m_axi_atomLocations_AWREGION,
        m_axi_atomLocations_AWUSER,
        m_axi_atomLocations_WVALID,
        m_axi_atomLocations_WREADY,
        m_axi_atomLocations_WDATA,
        m_axi_atomLocations_WSTRB,
        m_axi_atomLocations_WLAST,
        m_axi_atomLocations_WID,
        m_axi_atomLocations_WUSER,
        m_axi_atomLocations_ARVALID,
        m_axi_atomLocations_ARREADY,
        m_axi_atomLocations_ARADDR,
        m_axi_atomLocations_ARID,
        m_axi_atomLocations_ARLEN,
        m_axi_atomLocations_ARSIZE,
        m_axi_atomLocations_ARBURST,
        m_axi_atomLocations_ARLOCK,
        m_axi_atomLocations_ARCACHE,
        m_axi_atomLocations_ARPROT,
        m_axi_atomLocations_ARQOS,
        m_axi_atomLocations_ARREGION,
        m_axi_atomLocations_ARUSER,
        m_axi_atomLocations_RVALID,
        m_axi_atomLocations_RREADY,
        m_axi_atomLocations_RDATA,
        m_axi_atomLocations_RLAST,
        m_axi_atomLocations_RID,
        m_axi_atomLocations_RUSER,
        m_axi_atomLocations_RRESP,
        m_axi_atomLocations_BVALID,
        m_axi_atomLocations_BREADY,
        m_axi_atomLocations_BRESP,
        m_axi_atomLocations_BID,
        m_axi_atomLocations_BUSER,
        m_axi_emissions_AWVALID,
        m_axi_emissions_AWREADY,
        m_axi_emissions_AWADDR,
        m_axi_emissions_AWID,
        m_axi_emissions_AWLEN,
        m_axi_emissions_AWSIZE,
        m_axi_emissions_AWBURST,
        m_axi_emissions_AWLOCK,
        m_axi_emissions_AWCACHE,
        m_axi_emissions_AWPROT,
        m_axi_emissions_AWQOS,
        m_axi_emissions_AWREGION,
        m_axi_emissions_AWUSER,
        m_axi_emissions_WVALID,
        m_axi_emissions_WREADY,
        m_axi_emissions_WDATA,
        m_axi_emissions_WSTRB,
        m_axi_emissions_WLAST,
        m_axi_emissions_WID,
        m_axi_emissions_WUSER,
        m_axi_emissions_ARVALID,
        m_axi_emissions_ARREADY,
        m_axi_emissions_ARADDR,
        m_axi_emissions_ARID,
        m_axi_emissions_ARLEN,
        m_axi_emissions_ARSIZE,
        m_axi_emissions_ARBURST,
        m_axi_emissions_ARLOCK,
        m_axi_emissions_ARCACHE,
        m_axi_emissions_ARPROT,
        m_axi_emissions_ARQOS,
        m_axi_emissions_ARREGION,
        m_axi_emissions_ARUSER,
        m_axi_emissions_RVALID,
        m_axi_emissions_RREADY,
        m_axi_emissions_RDATA,
        m_axi_emissions_RLAST,
        m_axi_emissions_RID,
        m_axi_emissions_RUSER,
        m_axi_emissions_RRESP,
        m_axi_emissions_BVALID,
        m_axi_emissions_BREADY,
        m_axi_emissions_BRESP,
        m_axi_emissions_BID,
        m_axi_emissions_BUSER,
        m_axi_fullImage_AWVALID,
        m_axi_fullImage_AWREADY,
        m_axi_fullImage_AWADDR,
        m_axi_fullImage_AWID,
        m_axi_fullImage_AWLEN,
        m_axi_fullImage_AWSIZE,
        m_axi_fullImage_AWBURST,
        m_axi_fullImage_AWLOCK,
        m_axi_fullImage_AWCACHE,
        m_axi_fullImage_AWPROT,
        m_axi_fullImage_AWQOS,
        m_axi_fullImage_AWREGION,
        m_axi_fullImage_AWUSER,
        m_axi_fullImage_WVALID,
        m_axi_fullImage_WREADY,
        m_axi_fullImage_WDATA,
        m_axi_fullImage_WSTRB,
        m_axi_fullImage_WLAST,
        m_axi_fullImage_WID,
        m_axi_fullImage_WUSER,
        m_axi_fullImage_ARVALID,
        m_axi_fullImage_ARREADY,
        m_axi_fullImage_ARADDR,
        m_axi_fullImage_ARID,
        m_axi_fullImage_ARLEN,
        m_axi_fullImage_ARSIZE,
        m_axi_fullImage_ARBURST,
        m_axi_fullImage_ARLOCK,
        m_axi_fullImage_ARCACHE,
        m_axi_fullImage_ARPROT,
        m_axi_fullImage_ARQOS,
        m_axi_fullImage_ARREGION,
        m_axi_fullImage_ARUSER,
        m_axi_fullImage_RVALID,
        m_axi_fullImage_RREADY,
        m_axi_fullImage_RDATA,
        m_axi_fullImage_RLAST,
        m_axi_fullImage_RID,
        m_axi_fullImage_RUSER,
        m_axi_fullImage_RRESP,
        m_axi_fullImage_BVALID,
        m_axi_fullImage_BREADY,
        m_axi_fullImage_BRESP,
        m_axi_fullImage_BID,
        m_axi_fullImage_BUSER,
        m_axi_imageProjs_AWVALID,
        m_axi_imageProjs_AWREADY,
        m_axi_imageProjs_AWADDR,
        m_axi_imageProjs_AWID,
        m_axi_imageProjs_AWLEN,
        m_axi_imageProjs_AWSIZE,
        m_axi_imageProjs_AWBURST,
        m_axi_imageProjs_AWLOCK,
        m_axi_imageProjs_AWCACHE,
        m_axi_imageProjs_AWPROT,
        m_axi_imageProjs_AWQOS,
        m_axi_imageProjs_AWREGION,
        m_axi_imageProjs_AWUSER,
        m_axi_imageProjs_WVALID,
        m_axi_imageProjs_WREADY,
        m_axi_imageProjs_WDATA,
        m_axi_imageProjs_WSTRB,
        m_axi_imageProjs_WLAST,
        m_axi_imageProjs_WID,
        m_axi_imageProjs_WUSER,
        m_axi_imageProjs_ARVALID,
        m_axi_imageProjs_ARREADY,
        m_axi_imageProjs_ARADDR,
        m_axi_imageProjs_ARID,
        m_axi_imageProjs_ARLEN,
        m_axi_imageProjs_ARSIZE,
        m_axi_imageProjs_ARBURST,
        m_axi_imageProjs_ARLOCK,
        m_axi_imageProjs_ARCACHE,
        m_axi_imageProjs_ARPROT,
        m_axi_imageProjs_ARQOS,
        m_axi_imageProjs_ARREGION,
        m_axi_imageProjs_ARUSER,
        m_axi_imageProjs_RVALID,
        m_axi_imageProjs_RREADY,
        m_axi_imageProjs_RDATA,
        m_axi_imageProjs_RLAST,
        m_axi_imageProjs_RID,
        m_axi_imageProjs_RUSER,
        m_axi_imageProjs_RRESP,
        m_axi_imageProjs_BVALID,
        m_axi_imageProjs_BREADY,
        m_axi_imageProjs_BRESP,
        m_axi_imageProjs_BID,
        m_axi_imageProjs_BUSER,
        m_axi_imageProjs_local_AWVALID,
        m_axi_imageProjs_local_AWREADY,
        m_axi_imageProjs_local_AWADDR,
        m_axi_imageProjs_local_AWID,
        m_axi_imageProjs_local_AWLEN,
        m_axi_imageProjs_local_AWSIZE,
        m_axi_imageProjs_local_AWBURST,
        m_axi_imageProjs_local_AWLOCK,
        m_axi_imageProjs_local_AWCACHE,
        m_axi_imageProjs_local_AWPROT,
        m_axi_imageProjs_local_AWQOS,
        m_axi_imageProjs_local_AWREGION,
        m_axi_imageProjs_local_AWUSER,
        m_axi_imageProjs_local_WVALID,
        m_axi_imageProjs_local_WREADY,
        m_axi_imageProjs_local_WDATA,
        m_axi_imageProjs_local_WSTRB,
        m_axi_imageProjs_local_WLAST,
        m_axi_imageProjs_local_WID,
        m_axi_imageProjs_local_WUSER,
        m_axi_imageProjs_local_ARVALID,
        m_axi_imageProjs_local_ARREADY,
        m_axi_imageProjs_local_ARADDR,
        m_axi_imageProjs_local_ARID,
        m_axi_imageProjs_local_ARLEN,
        m_axi_imageProjs_local_ARSIZE,
        m_axi_imageProjs_local_ARBURST,
        m_axi_imageProjs_local_ARLOCK,
        m_axi_imageProjs_local_ARCACHE,
        m_axi_imageProjs_local_ARPROT,
        m_axi_imageProjs_local_ARQOS,
        m_axi_imageProjs_local_ARREGION,
        m_axi_imageProjs_local_ARUSER,
        m_axi_imageProjs_local_RVALID,
        m_axi_imageProjs_local_RREADY,
        m_axi_imageProjs_local_RDATA,
        m_axi_imageProjs_local_RLAST,
        m_axi_imageProjs_local_RID,
        m_axi_imageProjs_local_RUSER,
        m_axi_imageProjs_local_RRESP,
        m_axi_imageProjs_local_BVALID,
        m_axi_imageProjs_local_BREADY,
        m_axi_imageProjs_local_BRESP,
        m_axi_imageProjs_local_BID,
        m_axi_imageProjs_local_BUSER,
        m_axi_imageProjs_local_size_AWVALID,
        m_axi_imageProjs_local_size_AWREADY,
        m_axi_imageProjs_local_size_AWADDR,
        m_axi_imageProjs_local_size_AWID,
        m_axi_imageProjs_local_size_AWLEN,
        m_axi_imageProjs_local_size_AWSIZE,
        m_axi_imageProjs_local_size_AWBURST,
        m_axi_imageProjs_local_size_AWLOCK,
        m_axi_imageProjs_local_size_AWCACHE,
        m_axi_imageProjs_local_size_AWPROT,
        m_axi_imageProjs_local_size_AWQOS,
        m_axi_imageProjs_local_size_AWREGION,
        m_axi_imageProjs_local_size_AWUSER,
        m_axi_imageProjs_local_size_WVALID,
        m_axi_imageProjs_local_size_WREADY,
        m_axi_imageProjs_local_size_WDATA,
        m_axi_imageProjs_local_size_WSTRB,
        m_axi_imageProjs_local_size_WLAST,
        m_axi_imageProjs_local_size_WID,
        m_axi_imageProjs_local_size_WUSER,
        m_axi_imageProjs_local_size_ARVALID,
        m_axi_imageProjs_local_size_ARREADY,
        m_axi_imageProjs_local_size_ARADDR,
        m_axi_imageProjs_local_size_ARID,
        m_axi_imageProjs_local_size_ARLEN,
        m_axi_imageProjs_local_size_ARSIZE,
        m_axi_imageProjs_local_size_ARBURST,
        m_axi_imageProjs_local_size_ARLOCK,
        m_axi_imageProjs_local_size_ARCACHE,
        m_axi_imageProjs_local_size_ARPROT,
        m_axi_imageProjs_local_size_ARQOS,
        m_axi_imageProjs_local_size_ARREGION,
        m_axi_imageProjs_local_size_ARUSER,
        m_axi_imageProjs_local_size_RVALID,
        m_axi_imageProjs_local_size_RREADY,
        m_axi_imageProjs_local_size_RDATA,
        m_axi_imageProjs_local_size_RLAST,
        m_axi_imageProjs_local_size_RID,
        m_axi_imageProjs_local_size_RUSER,
        m_axi_imageProjs_local_size_RRESP,
        m_axi_imageProjs_local_size_BVALID,
        m_axi_imageProjs_local_size_BREADY,
        m_axi_imageProjs_local_size_BRESP,
        m_axi_imageProjs_local_size_BID,
        m_axi_imageProjs_local_size_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_SCALAR_DATA_DATA_WIDTH = 32;
parameter    C_S_AXI_SCALAR_DATA_ADDR_WIDTH = 7;
parameter    C_M_AXI_ATOMLOCATIONS_ID_WIDTH = 1;
parameter    C_M_AXI_ATOMLOCATIONS_ADDR_WIDTH = 64;
parameter    C_M_AXI_ATOMLOCATIONS_DATA_WIDTH = 64;
parameter    C_M_AXI_ATOMLOCATIONS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ATOMLOCATIONS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_ATOMLOCATIONS_WUSER_WIDTH = 1;
parameter    C_M_AXI_ATOMLOCATIONS_RUSER_WIDTH = 1;
parameter    C_M_AXI_ATOMLOCATIONS_BUSER_WIDTH = 1;
parameter    C_M_AXI_ATOMLOCATIONS_USER_VALUE = 0;
parameter    C_M_AXI_ATOMLOCATIONS_PROT_VALUE = 0;
parameter    C_M_AXI_ATOMLOCATIONS_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_EMISSIONS_ID_WIDTH = 1;
parameter    C_M_AXI_EMISSIONS_ADDR_WIDTH = 64;
parameter    C_M_AXI_EMISSIONS_DATA_WIDTH = 32;
parameter    C_M_AXI_EMISSIONS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_EMISSIONS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_EMISSIONS_WUSER_WIDTH = 1;
parameter    C_M_AXI_EMISSIONS_RUSER_WIDTH = 1;
parameter    C_M_AXI_EMISSIONS_BUSER_WIDTH = 1;
parameter    C_M_AXI_EMISSIONS_USER_VALUE = 0;
parameter    C_M_AXI_EMISSIONS_PROT_VALUE = 0;
parameter    C_M_AXI_EMISSIONS_CACHE_VALUE = 3;
parameter    C_M_AXI_FULLIMAGE_ID_WIDTH = 1;
parameter    C_M_AXI_FULLIMAGE_ADDR_WIDTH = 64;
parameter    C_M_AXI_FULLIMAGE_DATA_WIDTH = 32;
parameter    C_M_AXI_FULLIMAGE_AWUSER_WIDTH = 1;
parameter    C_M_AXI_FULLIMAGE_ARUSER_WIDTH = 1;
parameter    C_M_AXI_FULLIMAGE_WUSER_WIDTH = 1;
parameter    C_M_AXI_FULLIMAGE_RUSER_WIDTH = 1;
parameter    C_M_AXI_FULLIMAGE_BUSER_WIDTH = 1;
parameter    C_M_AXI_FULLIMAGE_USER_VALUE = 0;
parameter    C_M_AXI_FULLIMAGE_PROT_VALUE = 0;
parameter    C_M_AXI_FULLIMAGE_CACHE_VALUE = 3;
parameter    C_M_AXI_IMAGEPROJS_ID_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_ADDR_WIDTH = 64;
parameter    C_M_AXI_IMAGEPROJS_DATA_WIDTH = 32;
parameter    C_M_AXI_IMAGEPROJS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_WUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_RUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_BUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_USER_VALUE = 0;
parameter    C_M_AXI_IMAGEPROJS_PROT_VALUE = 0;
parameter    C_M_AXI_IMAGEPROJS_CACHE_VALUE = 3;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_ID_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_ADDR_WIDTH = 64;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_DATA_WIDTH = 32;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_AWUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_ARUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_WUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_RUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_BUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_USER_VALUE = 0;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_PROT_VALUE = 0;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_CACHE_VALUE = 3;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ID_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ADDR_WIDTH = 64;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_DATA_WIDTH = 32;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_AWUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ARUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_WUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_RUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_BUSER_WIDTH = 1;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_USER_VALUE = 0;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_PROT_VALUE = 0;
parameter    C_M_AXI_IMAGEPROJS_LOCAL_SIZE_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_SCALAR_DATA_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_ATOMLOCATIONS_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_EMISSIONS_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_FULLIMAGE_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_IMAGEPROJS_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_IMAGEPROJS_LOCAL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_IMAGEPROJS_LOCAL_SIZE_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input   s_axi_scalar_data_AWVALID;
output   s_axi_scalar_data_AWREADY;
input  [C_S_AXI_SCALAR_DATA_ADDR_WIDTH - 1:0] s_axi_scalar_data_AWADDR;
input   s_axi_scalar_data_WVALID;
output   s_axi_scalar_data_WREADY;
input  [C_S_AXI_SCALAR_DATA_DATA_WIDTH - 1:0] s_axi_scalar_data_WDATA;
input  [C_S_AXI_SCALAR_DATA_WSTRB_WIDTH - 1:0] s_axi_scalar_data_WSTRB;
input   s_axi_scalar_data_ARVALID;
output   s_axi_scalar_data_ARREADY;
input  [C_S_AXI_SCALAR_DATA_ADDR_WIDTH - 1:0] s_axi_scalar_data_ARADDR;
output   s_axi_scalar_data_RVALID;
input   s_axi_scalar_data_RREADY;
output  [C_S_AXI_SCALAR_DATA_DATA_WIDTH - 1:0] s_axi_scalar_data_RDATA;
output  [1:0] s_axi_scalar_data_RRESP;
output   s_axi_scalar_data_BVALID;
input   s_axi_scalar_data_BREADY;
output  [1:0] s_axi_scalar_data_BRESP;
output   m_axi_atomLocations_AWVALID;
input   m_axi_atomLocations_AWREADY;
output  [C_M_AXI_ATOMLOCATIONS_ADDR_WIDTH - 1:0] m_axi_atomLocations_AWADDR;
output  [C_M_AXI_ATOMLOCATIONS_ID_WIDTH - 1:0] m_axi_atomLocations_AWID;
output  [7:0] m_axi_atomLocations_AWLEN;
output  [2:0] m_axi_atomLocations_AWSIZE;
output  [1:0] m_axi_atomLocations_AWBURST;
output  [1:0] m_axi_atomLocations_AWLOCK;
output  [3:0] m_axi_atomLocations_AWCACHE;
output  [2:0] m_axi_atomLocations_AWPROT;
output  [3:0] m_axi_atomLocations_AWQOS;
output  [3:0] m_axi_atomLocations_AWREGION;
output  [C_M_AXI_ATOMLOCATIONS_AWUSER_WIDTH - 1:0] m_axi_atomLocations_AWUSER;
output   m_axi_atomLocations_WVALID;
input   m_axi_atomLocations_WREADY;
output  [C_M_AXI_ATOMLOCATIONS_DATA_WIDTH - 1:0] m_axi_atomLocations_WDATA;
output  [C_M_AXI_ATOMLOCATIONS_WSTRB_WIDTH - 1:0] m_axi_atomLocations_WSTRB;
output   m_axi_atomLocations_WLAST;
output  [C_M_AXI_ATOMLOCATIONS_ID_WIDTH - 1:0] m_axi_atomLocations_WID;
output  [C_M_AXI_ATOMLOCATIONS_WUSER_WIDTH - 1:0] m_axi_atomLocations_WUSER;
output   m_axi_atomLocations_ARVALID;
input   m_axi_atomLocations_ARREADY;
output  [C_M_AXI_ATOMLOCATIONS_ADDR_WIDTH - 1:0] m_axi_atomLocations_ARADDR;
output  [C_M_AXI_ATOMLOCATIONS_ID_WIDTH - 1:0] m_axi_atomLocations_ARID;
output  [7:0] m_axi_atomLocations_ARLEN;
output  [2:0] m_axi_atomLocations_ARSIZE;
output  [1:0] m_axi_atomLocations_ARBURST;
output  [1:0] m_axi_atomLocations_ARLOCK;
output  [3:0] m_axi_atomLocations_ARCACHE;
output  [2:0] m_axi_atomLocations_ARPROT;
output  [3:0] m_axi_atomLocations_ARQOS;
output  [3:0] m_axi_atomLocations_ARREGION;
output  [C_M_AXI_ATOMLOCATIONS_ARUSER_WIDTH - 1:0] m_axi_atomLocations_ARUSER;
input   m_axi_atomLocations_RVALID;
output   m_axi_atomLocations_RREADY;
input  [C_M_AXI_ATOMLOCATIONS_DATA_WIDTH - 1:0] m_axi_atomLocations_RDATA;
input   m_axi_atomLocations_RLAST;
input  [C_M_AXI_ATOMLOCATIONS_ID_WIDTH - 1:0] m_axi_atomLocations_RID;
input  [C_M_AXI_ATOMLOCATIONS_RUSER_WIDTH - 1:0] m_axi_atomLocations_RUSER;
input  [1:0] m_axi_atomLocations_RRESP;
input   m_axi_atomLocations_BVALID;
output   m_axi_atomLocations_BREADY;
input  [1:0] m_axi_atomLocations_BRESP;
input  [C_M_AXI_ATOMLOCATIONS_ID_WIDTH - 1:0] m_axi_atomLocations_BID;
input  [C_M_AXI_ATOMLOCATIONS_BUSER_WIDTH - 1:0] m_axi_atomLocations_BUSER;
output   m_axi_emissions_AWVALID;
input   m_axi_emissions_AWREADY;
output  [C_M_AXI_EMISSIONS_ADDR_WIDTH - 1:0] m_axi_emissions_AWADDR;
output  [C_M_AXI_EMISSIONS_ID_WIDTH - 1:0] m_axi_emissions_AWID;
output  [7:0] m_axi_emissions_AWLEN;
output  [2:0] m_axi_emissions_AWSIZE;
output  [1:0] m_axi_emissions_AWBURST;
output  [1:0] m_axi_emissions_AWLOCK;
output  [3:0] m_axi_emissions_AWCACHE;
output  [2:0] m_axi_emissions_AWPROT;
output  [3:0] m_axi_emissions_AWQOS;
output  [3:0] m_axi_emissions_AWREGION;
output  [C_M_AXI_EMISSIONS_AWUSER_WIDTH - 1:0] m_axi_emissions_AWUSER;
output   m_axi_emissions_WVALID;
input   m_axi_emissions_WREADY;
output  [C_M_AXI_EMISSIONS_DATA_WIDTH - 1:0] m_axi_emissions_WDATA;
output  [C_M_AXI_EMISSIONS_WSTRB_WIDTH - 1:0] m_axi_emissions_WSTRB;
output   m_axi_emissions_WLAST;
output  [C_M_AXI_EMISSIONS_ID_WIDTH - 1:0] m_axi_emissions_WID;
output  [C_M_AXI_EMISSIONS_WUSER_WIDTH - 1:0] m_axi_emissions_WUSER;
output   m_axi_emissions_ARVALID;
input   m_axi_emissions_ARREADY;
output  [C_M_AXI_EMISSIONS_ADDR_WIDTH - 1:0] m_axi_emissions_ARADDR;
output  [C_M_AXI_EMISSIONS_ID_WIDTH - 1:0] m_axi_emissions_ARID;
output  [7:0] m_axi_emissions_ARLEN;
output  [2:0] m_axi_emissions_ARSIZE;
output  [1:0] m_axi_emissions_ARBURST;
output  [1:0] m_axi_emissions_ARLOCK;
output  [3:0] m_axi_emissions_ARCACHE;
output  [2:0] m_axi_emissions_ARPROT;
output  [3:0] m_axi_emissions_ARQOS;
output  [3:0] m_axi_emissions_ARREGION;
output  [C_M_AXI_EMISSIONS_ARUSER_WIDTH - 1:0] m_axi_emissions_ARUSER;
input   m_axi_emissions_RVALID;
output   m_axi_emissions_RREADY;
input  [C_M_AXI_EMISSIONS_DATA_WIDTH - 1:0] m_axi_emissions_RDATA;
input   m_axi_emissions_RLAST;
input  [C_M_AXI_EMISSIONS_ID_WIDTH - 1:0] m_axi_emissions_RID;
input  [C_M_AXI_EMISSIONS_RUSER_WIDTH - 1:0] m_axi_emissions_RUSER;
input  [1:0] m_axi_emissions_RRESP;
input   m_axi_emissions_BVALID;
output   m_axi_emissions_BREADY;
input  [1:0] m_axi_emissions_BRESP;
input  [C_M_AXI_EMISSIONS_ID_WIDTH - 1:0] m_axi_emissions_BID;
input  [C_M_AXI_EMISSIONS_BUSER_WIDTH - 1:0] m_axi_emissions_BUSER;
output   m_axi_fullImage_AWVALID;
input   m_axi_fullImage_AWREADY;
output  [C_M_AXI_FULLIMAGE_ADDR_WIDTH - 1:0] m_axi_fullImage_AWADDR;
output  [C_M_AXI_FULLIMAGE_ID_WIDTH - 1:0] m_axi_fullImage_AWID;
output  [7:0] m_axi_fullImage_AWLEN;
output  [2:0] m_axi_fullImage_AWSIZE;
output  [1:0] m_axi_fullImage_AWBURST;
output  [1:0] m_axi_fullImage_AWLOCK;
output  [3:0] m_axi_fullImage_AWCACHE;
output  [2:0] m_axi_fullImage_AWPROT;
output  [3:0] m_axi_fullImage_AWQOS;
output  [3:0] m_axi_fullImage_AWREGION;
output  [C_M_AXI_FULLIMAGE_AWUSER_WIDTH - 1:0] m_axi_fullImage_AWUSER;
output   m_axi_fullImage_WVALID;
input   m_axi_fullImage_WREADY;
output  [C_M_AXI_FULLIMAGE_DATA_WIDTH - 1:0] m_axi_fullImage_WDATA;
output  [C_M_AXI_FULLIMAGE_WSTRB_WIDTH - 1:0] m_axi_fullImage_WSTRB;
output   m_axi_fullImage_WLAST;
output  [C_M_AXI_FULLIMAGE_ID_WIDTH - 1:0] m_axi_fullImage_WID;
output  [C_M_AXI_FULLIMAGE_WUSER_WIDTH - 1:0] m_axi_fullImage_WUSER;
output   m_axi_fullImage_ARVALID;
input   m_axi_fullImage_ARREADY;
output  [C_M_AXI_FULLIMAGE_ADDR_WIDTH - 1:0] m_axi_fullImage_ARADDR;
output  [C_M_AXI_FULLIMAGE_ID_WIDTH - 1:0] m_axi_fullImage_ARID;
output  [7:0] m_axi_fullImage_ARLEN;
output  [2:0] m_axi_fullImage_ARSIZE;
output  [1:0] m_axi_fullImage_ARBURST;
output  [1:0] m_axi_fullImage_ARLOCK;
output  [3:0] m_axi_fullImage_ARCACHE;
output  [2:0] m_axi_fullImage_ARPROT;
output  [3:0] m_axi_fullImage_ARQOS;
output  [3:0] m_axi_fullImage_ARREGION;
output  [C_M_AXI_FULLIMAGE_ARUSER_WIDTH - 1:0] m_axi_fullImage_ARUSER;
input   m_axi_fullImage_RVALID;
output   m_axi_fullImage_RREADY;
input  [C_M_AXI_FULLIMAGE_DATA_WIDTH - 1:0] m_axi_fullImage_RDATA;
input   m_axi_fullImage_RLAST;
input  [C_M_AXI_FULLIMAGE_ID_WIDTH - 1:0] m_axi_fullImage_RID;
input  [C_M_AXI_FULLIMAGE_RUSER_WIDTH - 1:0] m_axi_fullImage_RUSER;
input  [1:0] m_axi_fullImage_RRESP;
input   m_axi_fullImage_BVALID;
output   m_axi_fullImage_BREADY;
input  [1:0] m_axi_fullImage_BRESP;
input  [C_M_AXI_FULLIMAGE_ID_WIDTH - 1:0] m_axi_fullImage_BID;
input  [C_M_AXI_FULLIMAGE_BUSER_WIDTH - 1:0] m_axi_fullImage_BUSER;
output   m_axi_imageProjs_AWVALID;
input   m_axi_imageProjs_AWREADY;
output  [C_M_AXI_IMAGEPROJS_ADDR_WIDTH - 1:0] m_axi_imageProjs_AWADDR;
output  [C_M_AXI_IMAGEPROJS_ID_WIDTH - 1:0] m_axi_imageProjs_AWID;
output  [7:0] m_axi_imageProjs_AWLEN;
output  [2:0] m_axi_imageProjs_AWSIZE;
output  [1:0] m_axi_imageProjs_AWBURST;
output  [1:0] m_axi_imageProjs_AWLOCK;
output  [3:0] m_axi_imageProjs_AWCACHE;
output  [2:0] m_axi_imageProjs_AWPROT;
output  [3:0] m_axi_imageProjs_AWQOS;
output  [3:0] m_axi_imageProjs_AWREGION;
output  [C_M_AXI_IMAGEPROJS_AWUSER_WIDTH - 1:0] m_axi_imageProjs_AWUSER;
output   m_axi_imageProjs_WVALID;
input   m_axi_imageProjs_WREADY;
output  [C_M_AXI_IMAGEPROJS_DATA_WIDTH - 1:0] m_axi_imageProjs_WDATA;
output  [C_M_AXI_IMAGEPROJS_WSTRB_WIDTH - 1:0] m_axi_imageProjs_WSTRB;
output   m_axi_imageProjs_WLAST;
output  [C_M_AXI_IMAGEPROJS_ID_WIDTH - 1:0] m_axi_imageProjs_WID;
output  [C_M_AXI_IMAGEPROJS_WUSER_WIDTH - 1:0] m_axi_imageProjs_WUSER;
output   m_axi_imageProjs_ARVALID;
input   m_axi_imageProjs_ARREADY;
output  [C_M_AXI_IMAGEPROJS_ADDR_WIDTH - 1:0] m_axi_imageProjs_ARADDR;
output  [C_M_AXI_IMAGEPROJS_ID_WIDTH - 1:0] m_axi_imageProjs_ARID;
output  [7:0] m_axi_imageProjs_ARLEN;
output  [2:0] m_axi_imageProjs_ARSIZE;
output  [1:0] m_axi_imageProjs_ARBURST;
output  [1:0] m_axi_imageProjs_ARLOCK;
output  [3:0] m_axi_imageProjs_ARCACHE;
output  [2:0] m_axi_imageProjs_ARPROT;
output  [3:0] m_axi_imageProjs_ARQOS;
output  [3:0] m_axi_imageProjs_ARREGION;
output  [C_M_AXI_IMAGEPROJS_ARUSER_WIDTH - 1:0] m_axi_imageProjs_ARUSER;
input   m_axi_imageProjs_RVALID;
output   m_axi_imageProjs_RREADY;
input  [C_M_AXI_IMAGEPROJS_DATA_WIDTH - 1:0] m_axi_imageProjs_RDATA;
input   m_axi_imageProjs_RLAST;
input  [C_M_AXI_IMAGEPROJS_ID_WIDTH - 1:0] m_axi_imageProjs_RID;
input  [C_M_AXI_IMAGEPROJS_RUSER_WIDTH - 1:0] m_axi_imageProjs_RUSER;
input  [1:0] m_axi_imageProjs_RRESP;
input   m_axi_imageProjs_BVALID;
output   m_axi_imageProjs_BREADY;
input  [1:0] m_axi_imageProjs_BRESP;
input  [C_M_AXI_IMAGEPROJS_ID_WIDTH - 1:0] m_axi_imageProjs_BID;
input  [C_M_AXI_IMAGEPROJS_BUSER_WIDTH - 1:0] m_axi_imageProjs_BUSER;
output   m_axi_imageProjs_local_AWVALID;
input   m_axi_imageProjs_local_AWREADY;
output  [C_M_AXI_IMAGEPROJS_LOCAL_ADDR_WIDTH - 1:0] m_axi_imageProjs_local_AWADDR;
output  [C_M_AXI_IMAGEPROJS_LOCAL_ID_WIDTH - 1:0] m_axi_imageProjs_local_AWID;
output  [7:0] m_axi_imageProjs_local_AWLEN;
output  [2:0] m_axi_imageProjs_local_AWSIZE;
output  [1:0] m_axi_imageProjs_local_AWBURST;
output  [1:0] m_axi_imageProjs_local_AWLOCK;
output  [3:0] m_axi_imageProjs_local_AWCACHE;
output  [2:0] m_axi_imageProjs_local_AWPROT;
output  [3:0] m_axi_imageProjs_local_AWQOS;
output  [3:0] m_axi_imageProjs_local_AWREGION;
output  [C_M_AXI_IMAGEPROJS_LOCAL_AWUSER_WIDTH - 1:0] m_axi_imageProjs_local_AWUSER;
output   m_axi_imageProjs_local_WVALID;
input   m_axi_imageProjs_local_WREADY;
output  [C_M_AXI_IMAGEPROJS_LOCAL_DATA_WIDTH - 1:0] m_axi_imageProjs_local_WDATA;
output  [C_M_AXI_IMAGEPROJS_LOCAL_WSTRB_WIDTH - 1:0] m_axi_imageProjs_local_WSTRB;
output   m_axi_imageProjs_local_WLAST;
output  [C_M_AXI_IMAGEPROJS_LOCAL_ID_WIDTH - 1:0] m_axi_imageProjs_local_WID;
output  [C_M_AXI_IMAGEPROJS_LOCAL_WUSER_WIDTH - 1:0] m_axi_imageProjs_local_WUSER;
output   m_axi_imageProjs_local_ARVALID;
input   m_axi_imageProjs_local_ARREADY;
output  [C_M_AXI_IMAGEPROJS_LOCAL_ADDR_WIDTH - 1:0] m_axi_imageProjs_local_ARADDR;
output  [C_M_AXI_IMAGEPROJS_LOCAL_ID_WIDTH - 1:0] m_axi_imageProjs_local_ARID;
output  [7:0] m_axi_imageProjs_local_ARLEN;
output  [2:0] m_axi_imageProjs_local_ARSIZE;
output  [1:0] m_axi_imageProjs_local_ARBURST;
output  [1:0] m_axi_imageProjs_local_ARLOCK;
output  [3:0] m_axi_imageProjs_local_ARCACHE;
output  [2:0] m_axi_imageProjs_local_ARPROT;
output  [3:0] m_axi_imageProjs_local_ARQOS;
output  [3:0] m_axi_imageProjs_local_ARREGION;
output  [C_M_AXI_IMAGEPROJS_LOCAL_ARUSER_WIDTH - 1:0] m_axi_imageProjs_local_ARUSER;
input   m_axi_imageProjs_local_RVALID;
output   m_axi_imageProjs_local_RREADY;
input  [C_M_AXI_IMAGEPROJS_LOCAL_DATA_WIDTH - 1:0] m_axi_imageProjs_local_RDATA;
input   m_axi_imageProjs_local_RLAST;
input  [C_M_AXI_IMAGEPROJS_LOCAL_ID_WIDTH - 1:0] m_axi_imageProjs_local_RID;
input  [C_M_AXI_IMAGEPROJS_LOCAL_RUSER_WIDTH - 1:0] m_axi_imageProjs_local_RUSER;
input  [1:0] m_axi_imageProjs_local_RRESP;
input   m_axi_imageProjs_local_BVALID;
output   m_axi_imageProjs_local_BREADY;
input  [1:0] m_axi_imageProjs_local_BRESP;
input  [C_M_AXI_IMAGEPROJS_LOCAL_ID_WIDTH - 1:0] m_axi_imageProjs_local_BID;
input  [C_M_AXI_IMAGEPROJS_LOCAL_BUSER_WIDTH - 1:0] m_axi_imageProjs_local_BUSER;
output   m_axi_imageProjs_local_size_AWVALID;
input   m_axi_imageProjs_local_size_AWREADY;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ADDR_WIDTH - 1:0] m_axi_imageProjs_local_size_AWADDR;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ID_WIDTH - 1:0] m_axi_imageProjs_local_size_AWID;
output  [7:0] m_axi_imageProjs_local_size_AWLEN;
output  [2:0] m_axi_imageProjs_local_size_AWSIZE;
output  [1:0] m_axi_imageProjs_local_size_AWBURST;
output  [1:0] m_axi_imageProjs_local_size_AWLOCK;
output  [3:0] m_axi_imageProjs_local_size_AWCACHE;
output  [2:0] m_axi_imageProjs_local_size_AWPROT;
output  [3:0] m_axi_imageProjs_local_size_AWQOS;
output  [3:0] m_axi_imageProjs_local_size_AWREGION;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_AWUSER_WIDTH - 1:0] m_axi_imageProjs_local_size_AWUSER;
output   m_axi_imageProjs_local_size_WVALID;
input   m_axi_imageProjs_local_size_WREADY;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_DATA_WIDTH - 1:0] m_axi_imageProjs_local_size_WDATA;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_WSTRB_WIDTH - 1:0] m_axi_imageProjs_local_size_WSTRB;
output   m_axi_imageProjs_local_size_WLAST;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ID_WIDTH - 1:0] m_axi_imageProjs_local_size_WID;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_WUSER_WIDTH - 1:0] m_axi_imageProjs_local_size_WUSER;
output   m_axi_imageProjs_local_size_ARVALID;
input   m_axi_imageProjs_local_size_ARREADY;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ADDR_WIDTH - 1:0] m_axi_imageProjs_local_size_ARADDR;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ID_WIDTH - 1:0] m_axi_imageProjs_local_size_ARID;
output  [7:0] m_axi_imageProjs_local_size_ARLEN;
output  [2:0] m_axi_imageProjs_local_size_ARSIZE;
output  [1:0] m_axi_imageProjs_local_size_ARBURST;
output  [1:0] m_axi_imageProjs_local_size_ARLOCK;
output  [3:0] m_axi_imageProjs_local_size_ARCACHE;
output  [2:0] m_axi_imageProjs_local_size_ARPROT;
output  [3:0] m_axi_imageProjs_local_size_ARQOS;
output  [3:0] m_axi_imageProjs_local_size_ARREGION;
output  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ARUSER_WIDTH - 1:0] m_axi_imageProjs_local_size_ARUSER;
input   m_axi_imageProjs_local_size_RVALID;
output   m_axi_imageProjs_local_size_RREADY;
input  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_DATA_WIDTH - 1:0] m_axi_imageProjs_local_size_RDATA;
input   m_axi_imageProjs_local_size_RLAST;
input  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ID_WIDTH - 1:0] m_axi_imageProjs_local_size_RID;
input  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_RUSER_WIDTH - 1:0] m_axi_imageProjs_local_size_RUSER;
input  [1:0] m_axi_imageProjs_local_size_RRESP;
input   m_axi_imageProjs_local_size_BVALID;
output   m_axi_imageProjs_local_size_BREADY;
input  [1:0] m_axi_imageProjs_local_size_BRESP;
input  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_ID_WIDTH - 1:0] m_axi_imageProjs_local_size_BID;
input  [C_M_AXI_IMAGEPROJS_LOCAL_SIZE_BUSER_WIDTH - 1:0] m_axi_imageProjs_local_size_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] atomLocations_offset;
wire   [63:0] imageProjs_local_offset;
wire   [63:0] imageProjs_offset;
wire   [63:0] imageProjs_local_size_offset;
wire   [63:0] fullImage_offset;
wire   [63:0] emissions_offset;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
reg    ap_idle;
wire   [31:0] atomLocationsSize;
wire   [31:0] projShape0;
wire   [31:0] projShape1;
wire   [31:0] psfSupersample;
wire   [31:0] imageProjectionSize;
wire   [31:0] fullImage_rows;
wire   [31:0] fullImage_cols;
wire    atomLocations_0_AWREADY;
wire    atomLocations_0_WREADY;
wire    atomLocations_0_ARREADY;
wire    atomLocations_0_RVALID;
wire   [63:0] atomLocations_0_RDATA;
wire    atomLocations_0_RLAST;
wire   [0:0] atomLocations_0_RID;
wire   [8:0] atomLocations_0_RFIFONUM;
wire   [0:0] atomLocations_0_RUSER;
wire   [1:0] atomLocations_0_RRESP;
wire    atomLocations_0_BVALID;
wire    emissions_0_AWREADY;
wire    emissions_0_WREADY;
wire    emissions_0_ARREADY;
wire    emissions_0_RVALID;
wire   [31:0] emissions_0_RDATA;
wire   [8:0] emissions_0_RFIFONUM;
wire    emissions_0_BVALID;
wire   [1:0] emissions_0_BRESP;
wire   [0:0] emissions_0_BID;
wire   [0:0] emissions_0_BUSER;
wire    fullImage_0_AWREADY;
wire    fullImage_0_WREADY;
wire    fullImage_0_ARREADY;
wire    fullImage_0_RVALID;
wire   [31:0] fullImage_0_RDATA;
wire    fullImage_0_RLAST;
wire   [0:0] fullImage_0_RID;
wire   [8:0] fullImage_0_RFIFONUM;
wire   [0:0] fullImage_0_RUSER;
wire   [1:0] fullImage_0_RRESP;
wire    fullImage_0_BVALID;
wire    imageProjs_0_AWREADY;
wire    imageProjs_0_WREADY;
wire    imageProjs_0_ARREADY;
wire    imageProjs_0_RVALID;
wire   [31:0] imageProjs_0_RDATA;
wire    imageProjs_0_RLAST;
wire   [0:0] imageProjs_0_RID;
wire   [8:0] imageProjs_0_RFIFONUM;
wire   [0:0] imageProjs_0_RUSER;
wire   [1:0] imageProjs_0_RRESP;
wire    imageProjs_0_BVALID;
wire    imageProjs_local_0_AWREADY;
wire    imageProjs_local_0_WREADY;
wire    imageProjs_local_0_ARREADY;
wire    imageProjs_local_0_RVALID;
wire   [31:0] imageProjs_local_0_RDATA;
wire    imageProjs_local_0_RLAST;
wire   [0:0] imageProjs_local_0_RID;
wire   [8:0] imageProjs_local_0_RFIFONUM;
wire   [0:0] imageProjs_local_0_RUSER;
wire   [1:0] imageProjs_local_0_RRESP;
wire    imageProjs_local_0_BVALID;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_conv;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WDATA;
wire   [7:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WVALID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WDATA;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WVALID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WDATA;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WVALID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WDATA;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_BREADY;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_idx_0;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WVALID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WDATA;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_start;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_done;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_ready;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_idle;
wire    dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_continue;
wire    ap_bound_full_n;
reg    ap_bound_write;
wire   [31:0] ap_bound_dout;
wire    ap_bound_empty_n;
wire    ap_bound_read;
reg   [31:0] ap_loop_dataflow_input_count;
reg   [31:0] ap_loop_dataflow_output_count;
wire   [31:0] ap_bound_minus_1;
wire   [31:0] ap_bound_minus_1_output;
reg    ap_real_start;
reg    ap_partial_ready;
reg    ap_internal_ready;
reg    ap_internal_done;
wire    ap_bound_ack;
reg    ap_bound_reg_ack;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_loop_dataflow_input_count = 32'd0;
#0 ap_loop_dataflow_output_count = 32'd0;
#0 ap_bound_reg_ack = 1'b0;
end

reconstruct_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .atomLocations_offset(atomLocations_offset),
    .imageProjs_local_offset(imageProjs_local_offset),
    .imageProjs_offset(imageProjs_offset),
    .imageProjs_local_size_offset(imageProjs_local_size_offset),
    .fullImage_offset(fullImage_offset),
    .emissions_offset(emissions_offset),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

reconstruct_scalar_data_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_SCALAR_DATA_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_SCALAR_DATA_DATA_WIDTH ))
scalar_data_s_axi_U(
    .AWVALID(s_axi_scalar_data_AWVALID),
    .AWREADY(s_axi_scalar_data_AWREADY),
    .AWADDR(s_axi_scalar_data_AWADDR),
    .WVALID(s_axi_scalar_data_WVALID),
    .WREADY(s_axi_scalar_data_WREADY),
    .WDATA(s_axi_scalar_data_WDATA),
    .WSTRB(s_axi_scalar_data_WSTRB),
    .ARVALID(s_axi_scalar_data_ARVALID),
    .ARREADY(s_axi_scalar_data_ARREADY),
    .ARADDR(s_axi_scalar_data_ARADDR),
    .RVALID(s_axi_scalar_data_RVALID),
    .RREADY(s_axi_scalar_data_RREADY),
    .RDATA(s_axi_scalar_data_RDATA),
    .RRESP(s_axi_scalar_data_RRESP),
    .BVALID(s_axi_scalar_data_BVALID),
    .BREADY(s_axi_scalar_data_BREADY),
    .BRESP(s_axi_scalar_data_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .atomLocationsSize(atomLocationsSize),
    .projShape0(projShape0),
    .projShape1(projShape1),
    .psfSupersample(psfSupersample),
    .imageProjectionSize(imageProjectionSize),
    .fullImage_rows(fullImage_rows),
    .fullImage_cols(fullImage_cols)
);

reconstruct_atomLocations_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_ATOMLOCATIONS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_ATOMLOCATIONS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_ATOMLOCATIONS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_ATOMLOCATIONS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_ATOMLOCATIONS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_ATOMLOCATIONS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_ATOMLOCATIONS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_ATOMLOCATIONS_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_ATOMLOCATIONS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_ATOMLOCATIONS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_ATOMLOCATIONS_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
atomLocations_m_axi_U(
    .AWVALID(m_axi_atomLocations_AWVALID),
    .AWREADY(m_axi_atomLocations_AWREADY),
    .AWADDR(m_axi_atomLocations_AWADDR),
    .AWID(m_axi_atomLocations_AWID),
    .AWLEN(m_axi_atomLocations_AWLEN),
    .AWSIZE(m_axi_atomLocations_AWSIZE),
    .AWBURST(m_axi_atomLocations_AWBURST),
    .AWLOCK(m_axi_atomLocations_AWLOCK),
    .AWCACHE(m_axi_atomLocations_AWCACHE),
    .AWPROT(m_axi_atomLocations_AWPROT),
    .AWQOS(m_axi_atomLocations_AWQOS),
    .AWREGION(m_axi_atomLocations_AWREGION),
    .AWUSER(m_axi_atomLocations_AWUSER),
    .WVALID(m_axi_atomLocations_WVALID),
    .WREADY(m_axi_atomLocations_WREADY),
    .WDATA(m_axi_atomLocations_WDATA),
    .WSTRB(m_axi_atomLocations_WSTRB),
    .WLAST(m_axi_atomLocations_WLAST),
    .WID(m_axi_atomLocations_WID),
    .WUSER(m_axi_atomLocations_WUSER),
    .ARVALID(m_axi_atomLocations_ARVALID),
    .ARREADY(m_axi_atomLocations_ARREADY),
    .ARADDR(m_axi_atomLocations_ARADDR),
    .ARID(m_axi_atomLocations_ARID),
    .ARLEN(m_axi_atomLocations_ARLEN),
    .ARSIZE(m_axi_atomLocations_ARSIZE),
    .ARBURST(m_axi_atomLocations_ARBURST),
    .ARLOCK(m_axi_atomLocations_ARLOCK),
    .ARCACHE(m_axi_atomLocations_ARCACHE),
    .ARPROT(m_axi_atomLocations_ARPROT),
    .ARQOS(m_axi_atomLocations_ARQOS),
    .ARREGION(m_axi_atomLocations_ARREGION),
    .ARUSER(m_axi_atomLocations_ARUSER),
    .RVALID(m_axi_atomLocations_RVALID),
    .RREADY(m_axi_atomLocations_RREADY),
    .RDATA(m_axi_atomLocations_RDATA),
    .RLAST(m_axi_atomLocations_RLAST),
    .RID(m_axi_atomLocations_RID),
    .RUSER(m_axi_atomLocations_RUSER),
    .RRESP(m_axi_atomLocations_RRESP),
    .BVALID(m_axi_atomLocations_BVALID),
    .BREADY(m_axi_atomLocations_BREADY),
    .BRESP(m_axi_atomLocations_BRESP),
    .BID(m_axi_atomLocations_BID),
    .BUSER(m_axi_atomLocations_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARVALID),
    .I_CH0_ARREADY(atomLocations_0_ARREADY),
    .I_CH0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARADDR),
    .I_CH0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARLEN),
    .I_CH0_RVALID(atomLocations_0_RVALID),
    .I_CH0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_RREADY),
    .I_CH0_RDATA(atomLocations_0_RDATA),
    .I_CH0_RFIFONUM(atomLocations_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(atomLocations_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(atomLocations_0_WREADY),
    .I_CH0_WDATA(64'd0),
    .I_CH0_WSTRB(8'd0),
    .I_CH0_BVALID(atomLocations_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

reconstruct_emissions_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_EMISSIONS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_EMISSIONS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_EMISSIONS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_EMISSIONS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_EMISSIONS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_EMISSIONS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_EMISSIONS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_EMISSIONS_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_EMISSIONS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_EMISSIONS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_EMISSIONS_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
emissions_m_axi_U(
    .AWVALID(m_axi_emissions_AWVALID),
    .AWREADY(m_axi_emissions_AWREADY),
    .AWADDR(m_axi_emissions_AWADDR),
    .AWID(m_axi_emissions_AWID),
    .AWLEN(m_axi_emissions_AWLEN),
    .AWSIZE(m_axi_emissions_AWSIZE),
    .AWBURST(m_axi_emissions_AWBURST),
    .AWLOCK(m_axi_emissions_AWLOCK),
    .AWCACHE(m_axi_emissions_AWCACHE),
    .AWPROT(m_axi_emissions_AWPROT),
    .AWQOS(m_axi_emissions_AWQOS),
    .AWREGION(m_axi_emissions_AWREGION),
    .AWUSER(m_axi_emissions_AWUSER),
    .WVALID(m_axi_emissions_WVALID),
    .WREADY(m_axi_emissions_WREADY),
    .WDATA(m_axi_emissions_WDATA),
    .WSTRB(m_axi_emissions_WSTRB),
    .WLAST(m_axi_emissions_WLAST),
    .WID(m_axi_emissions_WID),
    .WUSER(m_axi_emissions_WUSER),
    .ARVALID(m_axi_emissions_ARVALID),
    .ARREADY(m_axi_emissions_ARREADY),
    .ARADDR(m_axi_emissions_ARADDR),
    .ARID(m_axi_emissions_ARID),
    .ARLEN(m_axi_emissions_ARLEN),
    .ARSIZE(m_axi_emissions_ARSIZE),
    .ARBURST(m_axi_emissions_ARBURST),
    .ARLOCK(m_axi_emissions_ARLOCK),
    .ARCACHE(m_axi_emissions_ARCACHE),
    .ARPROT(m_axi_emissions_ARPROT),
    .ARQOS(m_axi_emissions_ARQOS),
    .ARREGION(m_axi_emissions_ARREGION),
    .ARUSER(m_axi_emissions_ARUSER),
    .RVALID(m_axi_emissions_RVALID),
    .RREADY(m_axi_emissions_RREADY),
    .RDATA(m_axi_emissions_RDATA),
    .RLAST(m_axi_emissions_RLAST),
    .RID(m_axi_emissions_RID),
    .RUSER(m_axi_emissions_RUSER),
    .RRESP(m_axi_emissions_RRESP),
    .BVALID(m_axi_emissions_BVALID),
    .BREADY(m_axi_emissions_BREADY),
    .BRESP(m_axi_emissions_BRESP),
    .BID(m_axi_emissions_BID),
    .BUSER(m_axi_emissions_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(emissions_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(emissions_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(emissions_0_RDATA),
    .I_CH0_RFIFONUM(emissions_0_RFIFONUM),
    .I_CH0_AWVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWVALID),
    .I_CH0_AWREADY(emissions_0_AWREADY),
    .I_CH0_AWADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWADDR),
    .I_CH0_AWLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWLEN),
    .I_CH0_WVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WVALID),
    .I_CH0_WREADY(emissions_0_WREADY),
    .I_CH0_WDATA(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WDATA),
    .I_CH0_WSTRB(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WSTRB),
    .I_CH0_BVALID(emissions_0_BVALID),
    .I_CH0_BREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_BREADY)
);

reconstruct_fullImage_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_FULLIMAGE_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_FULLIMAGE_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_FULLIMAGE_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_FULLIMAGE_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_FULLIMAGE_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_FULLIMAGE_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_FULLIMAGE_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_FULLIMAGE_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_FULLIMAGE_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_FULLIMAGE_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_FULLIMAGE_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
fullImage_m_axi_U(
    .AWVALID(m_axi_fullImage_AWVALID),
    .AWREADY(m_axi_fullImage_AWREADY),
    .AWADDR(m_axi_fullImage_AWADDR),
    .AWID(m_axi_fullImage_AWID),
    .AWLEN(m_axi_fullImage_AWLEN),
    .AWSIZE(m_axi_fullImage_AWSIZE),
    .AWBURST(m_axi_fullImage_AWBURST),
    .AWLOCK(m_axi_fullImage_AWLOCK),
    .AWCACHE(m_axi_fullImage_AWCACHE),
    .AWPROT(m_axi_fullImage_AWPROT),
    .AWQOS(m_axi_fullImage_AWQOS),
    .AWREGION(m_axi_fullImage_AWREGION),
    .AWUSER(m_axi_fullImage_AWUSER),
    .WVALID(m_axi_fullImage_WVALID),
    .WREADY(m_axi_fullImage_WREADY),
    .WDATA(m_axi_fullImage_WDATA),
    .WSTRB(m_axi_fullImage_WSTRB),
    .WLAST(m_axi_fullImage_WLAST),
    .WID(m_axi_fullImage_WID),
    .WUSER(m_axi_fullImage_WUSER),
    .ARVALID(m_axi_fullImage_ARVALID),
    .ARREADY(m_axi_fullImage_ARREADY),
    .ARADDR(m_axi_fullImage_ARADDR),
    .ARID(m_axi_fullImage_ARID),
    .ARLEN(m_axi_fullImage_ARLEN),
    .ARSIZE(m_axi_fullImage_ARSIZE),
    .ARBURST(m_axi_fullImage_ARBURST),
    .ARLOCK(m_axi_fullImage_ARLOCK),
    .ARCACHE(m_axi_fullImage_ARCACHE),
    .ARPROT(m_axi_fullImage_ARPROT),
    .ARQOS(m_axi_fullImage_ARQOS),
    .ARREGION(m_axi_fullImage_ARREGION),
    .ARUSER(m_axi_fullImage_ARUSER),
    .RVALID(m_axi_fullImage_RVALID),
    .RREADY(m_axi_fullImage_RREADY),
    .RDATA(m_axi_fullImage_RDATA),
    .RLAST(m_axi_fullImage_RLAST),
    .RID(m_axi_fullImage_RID),
    .RUSER(m_axi_fullImage_RUSER),
    .RRESP(m_axi_fullImage_RRESP),
    .BVALID(m_axi_fullImage_BVALID),
    .BREADY(m_axi_fullImage_BREADY),
    .BRESP(m_axi_fullImage_BRESP),
    .BID(m_axi_fullImage_BID),
    .BUSER(m_axi_fullImage_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARVALID),
    .I_CH0_ARREADY(fullImage_0_ARREADY),
    .I_CH0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARADDR),
    .I_CH0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARLEN),
    .I_CH0_RVALID(fullImage_0_RVALID),
    .I_CH0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_RREADY),
    .I_CH0_RDATA(fullImage_0_RDATA),
    .I_CH0_RFIFONUM(fullImage_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(fullImage_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(fullImage_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(fullImage_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

reconstruct_imageProjs_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_IMAGEPROJS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_IMAGEPROJS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_IMAGEPROJS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_IMAGEPROJS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_IMAGEPROJS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_IMAGEPROJS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_IMAGEPROJS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_IMAGEPROJS_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_IMAGEPROJS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_IMAGEPROJS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_IMAGEPROJS_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
imageProjs_m_axi_U(
    .AWVALID(m_axi_imageProjs_AWVALID),
    .AWREADY(m_axi_imageProjs_AWREADY),
    .AWADDR(m_axi_imageProjs_AWADDR),
    .AWID(m_axi_imageProjs_AWID),
    .AWLEN(m_axi_imageProjs_AWLEN),
    .AWSIZE(m_axi_imageProjs_AWSIZE),
    .AWBURST(m_axi_imageProjs_AWBURST),
    .AWLOCK(m_axi_imageProjs_AWLOCK),
    .AWCACHE(m_axi_imageProjs_AWCACHE),
    .AWPROT(m_axi_imageProjs_AWPROT),
    .AWQOS(m_axi_imageProjs_AWQOS),
    .AWREGION(m_axi_imageProjs_AWREGION),
    .AWUSER(m_axi_imageProjs_AWUSER),
    .WVALID(m_axi_imageProjs_WVALID),
    .WREADY(m_axi_imageProjs_WREADY),
    .WDATA(m_axi_imageProjs_WDATA),
    .WSTRB(m_axi_imageProjs_WSTRB),
    .WLAST(m_axi_imageProjs_WLAST),
    .WID(m_axi_imageProjs_WID),
    .WUSER(m_axi_imageProjs_WUSER),
    .ARVALID(m_axi_imageProjs_ARVALID),
    .ARREADY(m_axi_imageProjs_ARREADY),
    .ARADDR(m_axi_imageProjs_ARADDR),
    .ARID(m_axi_imageProjs_ARID),
    .ARLEN(m_axi_imageProjs_ARLEN),
    .ARSIZE(m_axi_imageProjs_ARSIZE),
    .ARBURST(m_axi_imageProjs_ARBURST),
    .ARLOCK(m_axi_imageProjs_ARLOCK),
    .ARCACHE(m_axi_imageProjs_ARCACHE),
    .ARPROT(m_axi_imageProjs_ARPROT),
    .ARQOS(m_axi_imageProjs_ARQOS),
    .ARREGION(m_axi_imageProjs_ARREGION),
    .ARUSER(m_axi_imageProjs_ARUSER),
    .RVALID(m_axi_imageProjs_RVALID),
    .RREADY(m_axi_imageProjs_RREADY),
    .RDATA(m_axi_imageProjs_RDATA),
    .RLAST(m_axi_imageProjs_RLAST),
    .RID(m_axi_imageProjs_RID),
    .RUSER(m_axi_imageProjs_RUSER),
    .RRESP(m_axi_imageProjs_RRESP),
    .BVALID(m_axi_imageProjs_BVALID),
    .BREADY(m_axi_imageProjs_BREADY),
    .BRESP(m_axi_imageProjs_BRESP),
    .BID(m_axi_imageProjs_BID),
    .BUSER(m_axi_imageProjs_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARVALID),
    .I_CH0_ARREADY(imageProjs_0_ARREADY),
    .I_CH0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARADDR),
    .I_CH0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARLEN),
    .I_CH0_RVALID(imageProjs_0_RVALID),
    .I_CH0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_RREADY),
    .I_CH0_RDATA(imageProjs_0_RDATA),
    .I_CH0_RFIFONUM(imageProjs_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(imageProjs_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(imageProjs_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(imageProjs_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

reconstruct_imageProjs_local_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_IMAGEPROJS_LOCAL_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_IMAGEPROJS_LOCAL_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_IMAGEPROJS_LOCAL_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_IMAGEPROJS_LOCAL_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_IMAGEPROJS_LOCAL_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_IMAGEPROJS_LOCAL_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_IMAGEPROJS_LOCAL_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_IMAGEPROJS_LOCAL_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_IMAGEPROJS_LOCAL_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_IMAGEPROJS_LOCAL_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_IMAGEPROJS_LOCAL_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
imageProjs_local_m_axi_U(
    .AWVALID(m_axi_imageProjs_local_AWVALID),
    .AWREADY(m_axi_imageProjs_local_AWREADY),
    .AWADDR(m_axi_imageProjs_local_AWADDR),
    .AWID(m_axi_imageProjs_local_AWID),
    .AWLEN(m_axi_imageProjs_local_AWLEN),
    .AWSIZE(m_axi_imageProjs_local_AWSIZE),
    .AWBURST(m_axi_imageProjs_local_AWBURST),
    .AWLOCK(m_axi_imageProjs_local_AWLOCK),
    .AWCACHE(m_axi_imageProjs_local_AWCACHE),
    .AWPROT(m_axi_imageProjs_local_AWPROT),
    .AWQOS(m_axi_imageProjs_local_AWQOS),
    .AWREGION(m_axi_imageProjs_local_AWREGION),
    .AWUSER(m_axi_imageProjs_local_AWUSER),
    .WVALID(m_axi_imageProjs_local_WVALID),
    .WREADY(m_axi_imageProjs_local_WREADY),
    .WDATA(m_axi_imageProjs_local_WDATA),
    .WSTRB(m_axi_imageProjs_local_WSTRB),
    .WLAST(m_axi_imageProjs_local_WLAST),
    .WID(m_axi_imageProjs_local_WID),
    .WUSER(m_axi_imageProjs_local_WUSER),
    .ARVALID(m_axi_imageProjs_local_ARVALID),
    .ARREADY(m_axi_imageProjs_local_ARREADY),
    .ARADDR(m_axi_imageProjs_local_ARADDR),
    .ARID(m_axi_imageProjs_local_ARID),
    .ARLEN(m_axi_imageProjs_local_ARLEN),
    .ARSIZE(m_axi_imageProjs_local_ARSIZE),
    .ARBURST(m_axi_imageProjs_local_ARBURST),
    .ARLOCK(m_axi_imageProjs_local_ARLOCK),
    .ARCACHE(m_axi_imageProjs_local_ARCACHE),
    .ARPROT(m_axi_imageProjs_local_ARPROT),
    .ARQOS(m_axi_imageProjs_local_ARQOS),
    .ARREGION(m_axi_imageProjs_local_ARREGION),
    .ARUSER(m_axi_imageProjs_local_ARUSER),
    .RVALID(m_axi_imageProjs_local_RVALID),
    .RREADY(m_axi_imageProjs_local_RREADY),
    .RDATA(m_axi_imageProjs_local_RDATA),
    .RLAST(m_axi_imageProjs_local_RLAST),
    .RID(m_axi_imageProjs_local_RID),
    .RUSER(m_axi_imageProjs_local_RUSER),
    .RRESP(m_axi_imageProjs_local_RRESP),
    .BVALID(m_axi_imageProjs_local_BVALID),
    .BREADY(m_axi_imageProjs_local_BREADY),
    .BRESP(m_axi_imageProjs_local_BRESP),
    .BID(m_axi_imageProjs_local_BID),
    .BUSER(m_axi_imageProjs_local_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARVALID),
    .I_CH0_ARREADY(imageProjs_local_0_ARREADY),
    .I_CH0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARADDR),
    .I_CH0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARLEN),
    .I_CH0_RVALID(imageProjs_local_0_RVALID),
    .I_CH0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_RREADY),
    .I_CH0_RDATA(imageProjs_local_0_RDATA),
    .I_CH0_RFIFONUM(imageProjs_local_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(imageProjs_local_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(imageProjs_local_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(imageProjs_local_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

reconstruct_dataflow_in_loop_VITIS_LOOP_152_1_1 dataflow_in_loop_VITIS_LOOP_152_1_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .conv(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_conv),
    .psfSupersample(psfSupersample),
    .projShape0(projShape0),
    .projShape1(projShape1),
    .m_axi_atomLocations_0_AWVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWVALID),
    .m_axi_atomLocations_0_AWREADY(1'b0),
    .m_axi_atomLocations_0_AWADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWADDR),
    .m_axi_atomLocations_0_AWID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWID),
    .m_axi_atomLocations_0_AWLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWLEN),
    .m_axi_atomLocations_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWSIZE),
    .m_axi_atomLocations_0_AWBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWBURST),
    .m_axi_atomLocations_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWLOCK),
    .m_axi_atomLocations_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWCACHE),
    .m_axi_atomLocations_0_AWPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWPROT),
    .m_axi_atomLocations_0_AWQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWQOS),
    .m_axi_atomLocations_0_AWREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWREGION),
    .m_axi_atomLocations_0_AWUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_AWUSER),
    .m_axi_atomLocations_0_WVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WVALID),
    .m_axi_atomLocations_0_WREADY(1'b0),
    .m_axi_atomLocations_0_WDATA(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WDATA),
    .m_axi_atomLocations_0_WSTRB(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WSTRB),
    .m_axi_atomLocations_0_WLAST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WLAST),
    .m_axi_atomLocations_0_WID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WID),
    .m_axi_atomLocations_0_WUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_WUSER),
    .m_axi_atomLocations_0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARVALID),
    .m_axi_atomLocations_0_ARREADY(atomLocations_0_ARREADY),
    .m_axi_atomLocations_0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARADDR),
    .m_axi_atomLocations_0_ARID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARID),
    .m_axi_atomLocations_0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARLEN),
    .m_axi_atomLocations_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARSIZE),
    .m_axi_atomLocations_0_ARBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARBURST),
    .m_axi_atomLocations_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARLOCK),
    .m_axi_atomLocations_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARCACHE),
    .m_axi_atomLocations_0_ARPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARPROT),
    .m_axi_atomLocations_0_ARQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARQOS),
    .m_axi_atomLocations_0_ARREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARREGION),
    .m_axi_atomLocations_0_ARUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_ARUSER),
    .m_axi_atomLocations_0_RVALID(atomLocations_0_RVALID),
    .m_axi_atomLocations_0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_RREADY),
    .m_axi_atomLocations_0_RDATA(atomLocations_0_RDATA),
    .m_axi_atomLocations_0_RLAST(atomLocations_0_RLAST),
    .m_axi_atomLocations_0_RID(atomLocations_0_RID),
    .m_axi_atomLocations_0_RFIFONUM(atomLocations_0_RFIFONUM),
    .m_axi_atomLocations_0_RUSER(atomLocations_0_RUSER),
    .m_axi_atomLocations_0_RRESP(atomLocations_0_RRESP),
    .m_axi_atomLocations_0_BVALID(1'b0),
    .m_axi_atomLocations_0_BREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_atomLocations_0_BREADY),
    .m_axi_atomLocations_0_BRESP(2'd0),
    .m_axi_atomLocations_0_BID(1'd0),
    .m_axi_atomLocations_0_BUSER(1'd0),
    .atomLocations1(atomLocations_offset),
    .m_axi_imageProjs_0_AWVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWVALID),
    .m_axi_imageProjs_0_AWREADY(1'b0),
    .m_axi_imageProjs_0_AWADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWADDR),
    .m_axi_imageProjs_0_AWID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWID),
    .m_axi_imageProjs_0_AWLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWLEN),
    .m_axi_imageProjs_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWSIZE),
    .m_axi_imageProjs_0_AWBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWBURST),
    .m_axi_imageProjs_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWLOCK),
    .m_axi_imageProjs_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWCACHE),
    .m_axi_imageProjs_0_AWPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWPROT),
    .m_axi_imageProjs_0_AWQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWQOS),
    .m_axi_imageProjs_0_AWREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWREGION),
    .m_axi_imageProjs_0_AWUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_AWUSER),
    .m_axi_imageProjs_0_WVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WVALID),
    .m_axi_imageProjs_0_WREADY(1'b0),
    .m_axi_imageProjs_0_WDATA(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WDATA),
    .m_axi_imageProjs_0_WSTRB(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WSTRB),
    .m_axi_imageProjs_0_WLAST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WLAST),
    .m_axi_imageProjs_0_WID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WID),
    .m_axi_imageProjs_0_WUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_WUSER),
    .m_axi_imageProjs_0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARVALID),
    .m_axi_imageProjs_0_ARREADY(imageProjs_0_ARREADY),
    .m_axi_imageProjs_0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARADDR),
    .m_axi_imageProjs_0_ARID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARID),
    .m_axi_imageProjs_0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARLEN),
    .m_axi_imageProjs_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARSIZE),
    .m_axi_imageProjs_0_ARBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARBURST),
    .m_axi_imageProjs_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARLOCK),
    .m_axi_imageProjs_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARCACHE),
    .m_axi_imageProjs_0_ARPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARPROT),
    .m_axi_imageProjs_0_ARQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARQOS),
    .m_axi_imageProjs_0_ARREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARREGION),
    .m_axi_imageProjs_0_ARUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_ARUSER),
    .m_axi_imageProjs_0_RVALID(imageProjs_0_RVALID),
    .m_axi_imageProjs_0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_RREADY),
    .m_axi_imageProjs_0_RDATA(imageProjs_0_RDATA),
    .m_axi_imageProjs_0_RLAST(imageProjs_0_RLAST),
    .m_axi_imageProjs_0_RID(imageProjs_0_RID),
    .m_axi_imageProjs_0_RFIFONUM(imageProjs_0_RFIFONUM),
    .m_axi_imageProjs_0_RUSER(imageProjs_0_RUSER),
    .m_axi_imageProjs_0_RRESP(imageProjs_0_RRESP),
    .m_axi_imageProjs_0_BVALID(1'b0),
    .m_axi_imageProjs_0_BREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_0_BREADY),
    .m_axi_imageProjs_0_BRESP(2'd0),
    .m_axi_imageProjs_0_BID(1'd0),
    .m_axi_imageProjs_0_BUSER(1'd0),
    .empty(imageProjs_offset),
    .m_axi_fullImage_0_AWVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWVALID),
    .m_axi_fullImage_0_AWREADY(1'b0),
    .m_axi_fullImage_0_AWADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWADDR),
    .m_axi_fullImage_0_AWID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWID),
    .m_axi_fullImage_0_AWLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWLEN),
    .m_axi_fullImage_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWSIZE),
    .m_axi_fullImage_0_AWBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWBURST),
    .m_axi_fullImage_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWLOCK),
    .m_axi_fullImage_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWCACHE),
    .m_axi_fullImage_0_AWPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWPROT),
    .m_axi_fullImage_0_AWQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWQOS),
    .m_axi_fullImage_0_AWREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWREGION),
    .m_axi_fullImage_0_AWUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_AWUSER),
    .m_axi_fullImage_0_WVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WVALID),
    .m_axi_fullImage_0_WREADY(1'b0),
    .m_axi_fullImage_0_WDATA(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WDATA),
    .m_axi_fullImage_0_WSTRB(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WSTRB),
    .m_axi_fullImage_0_WLAST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WLAST),
    .m_axi_fullImage_0_WID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WID),
    .m_axi_fullImage_0_WUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_WUSER),
    .m_axi_fullImage_0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARVALID),
    .m_axi_fullImage_0_ARREADY(fullImage_0_ARREADY),
    .m_axi_fullImage_0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARADDR),
    .m_axi_fullImage_0_ARID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARID),
    .m_axi_fullImage_0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARLEN),
    .m_axi_fullImage_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARSIZE),
    .m_axi_fullImage_0_ARBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARBURST),
    .m_axi_fullImage_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARLOCK),
    .m_axi_fullImage_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARCACHE),
    .m_axi_fullImage_0_ARPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARPROT),
    .m_axi_fullImage_0_ARQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARQOS),
    .m_axi_fullImage_0_ARREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARREGION),
    .m_axi_fullImage_0_ARUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_ARUSER),
    .m_axi_fullImage_0_RVALID(fullImage_0_RVALID),
    .m_axi_fullImage_0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_RREADY),
    .m_axi_fullImage_0_RDATA(fullImage_0_RDATA),
    .m_axi_fullImage_0_RLAST(fullImage_0_RLAST),
    .m_axi_fullImage_0_RID(fullImage_0_RID),
    .m_axi_fullImage_0_RFIFONUM(fullImage_0_RFIFONUM),
    .m_axi_fullImage_0_RUSER(fullImage_0_RUSER),
    .m_axi_fullImage_0_RRESP(fullImage_0_RRESP),
    .m_axi_fullImage_0_BVALID(1'b0),
    .m_axi_fullImage_0_BREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_fullImage_0_BREADY),
    .m_axi_fullImage_0_BRESP(2'd0),
    .m_axi_fullImage_0_BID(1'd0),
    .m_axi_fullImage_0_BUSER(1'd0),
    .fullImage2(fullImage_offset),
    .m_axi_imageProjs_local_0_AWVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWVALID),
    .m_axi_imageProjs_local_0_AWREADY(1'b0),
    .m_axi_imageProjs_local_0_AWADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWADDR),
    .m_axi_imageProjs_local_0_AWID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWID),
    .m_axi_imageProjs_local_0_AWLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWLEN),
    .m_axi_imageProjs_local_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWSIZE),
    .m_axi_imageProjs_local_0_AWBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWBURST),
    .m_axi_imageProjs_local_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWLOCK),
    .m_axi_imageProjs_local_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWCACHE),
    .m_axi_imageProjs_local_0_AWPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWPROT),
    .m_axi_imageProjs_local_0_AWQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWQOS),
    .m_axi_imageProjs_local_0_AWREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWREGION),
    .m_axi_imageProjs_local_0_AWUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_AWUSER),
    .m_axi_imageProjs_local_0_WVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WVALID),
    .m_axi_imageProjs_local_0_WREADY(1'b0),
    .m_axi_imageProjs_local_0_WDATA(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WDATA),
    .m_axi_imageProjs_local_0_WSTRB(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WSTRB),
    .m_axi_imageProjs_local_0_WLAST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WLAST),
    .m_axi_imageProjs_local_0_WID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WID),
    .m_axi_imageProjs_local_0_WUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_WUSER),
    .m_axi_imageProjs_local_0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARVALID),
    .m_axi_imageProjs_local_0_ARREADY(imageProjs_local_0_ARREADY),
    .m_axi_imageProjs_local_0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARADDR),
    .m_axi_imageProjs_local_0_ARID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARID),
    .m_axi_imageProjs_local_0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARLEN),
    .m_axi_imageProjs_local_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARSIZE),
    .m_axi_imageProjs_local_0_ARBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARBURST),
    .m_axi_imageProjs_local_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARLOCK),
    .m_axi_imageProjs_local_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARCACHE),
    .m_axi_imageProjs_local_0_ARPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARPROT),
    .m_axi_imageProjs_local_0_ARQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARQOS),
    .m_axi_imageProjs_local_0_ARREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARREGION),
    .m_axi_imageProjs_local_0_ARUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_ARUSER),
    .m_axi_imageProjs_local_0_RVALID(imageProjs_local_0_RVALID),
    .m_axi_imageProjs_local_0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_RREADY),
    .m_axi_imageProjs_local_0_RDATA(imageProjs_local_0_RDATA),
    .m_axi_imageProjs_local_0_RLAST(imageProjs_local_0_RLAST),
    .m_axi_imageProjs_local_0_RID(imageProjs_local_0_RID),
    .m_axi_imageProjs_local_0_RFIFONUM(imageProjs_local_0_RFIFONUM),
    .m_axi_imageProjs_local_0_RUSER(imageProjs_local_0_RUSER),
    .m_axi_imageProjs_local_0_RRESP(imageProjs_local_0_RRESP),
    .m_axi_imageProjs_local_0_BVALID(1'b0),
    .m_axi_imageProjs_local_0_BREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_imageProjs_local_0_BREADY),
    .m_axi_imageProjs_local_0_BRESP(2'd0),
    .m_axi_imageProjs_local_0_BID(1'd0),
    .m_axi_imageProjs_local_0_BUSER(1'd0),
    .imageProjs_local3(imageProjs_local_offset),
    .idx_0(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_idx_0),
    .m_axi_emissions_0_AWVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWVALID),
    .m_axi_emissions_0_AWREADY(emissions_0_AWREADY),
    .m_axi_emissions_0_AWADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWADDR),
    .m_axi_emissions_0_AWID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWID),
    .m_axi_emissions_0_AWLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWLEN),
    .m_axi_emissions_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWSIZE),
    .m_axi_emissions_0_AWBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWBURST),
    .m_axi_emissions_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWLOCK),
    .m_axi_emissions_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWCACHE),
    .m_axi_emissions_0_AWPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWPROT),
    .m_axi_emissions_0_AWQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWQOS),
    .m_axi_emissions_0_AWREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWREGION),
    .m_axi_emissions_0_AWUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_AWUSER),
    .m_axi_emissions_0_WVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WVALID),
    .m_axi_emissions_0_WREADY(emissions_0_WREADY),
    .m_axi_emissions_0_WDATA(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WDATA),
    .m_axi_emissions_0_WSTRB(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WSTRB),
    .m_axi_emissions_0_WLAST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WLAST),
    .m_axi_emissions_0_WID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WID),
    .m_axi_emissions_0_WUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_WUSER),
    .m_axi_emissions_0_ARVALID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARVALID),
    .m_axi_emissions_0_ARREADY(1'b0),
    .m_axi_emissions_0_ARADDR(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARADDR),
    .m_axi_emissions_0_ARID(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARID),
    .m_axi_emissions_0_ARLEN(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARLEN),
    .m_axi_emissions_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARSIZE),
    .m_axi_emissions_0_ARBURST(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARBURST),
    .m_axi_emissions_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARLOCK),
    .m_axi_emissions_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARCACHE),
    .m_axi_emissions_0_ARPROT(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARPROT),
    .m_axi_emissions_0_ARQOS(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARQOS),
    .m_axi_emissions_0_ARREGION(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARREGION),
    .m_axi_emissions_0_ARUSER(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_ARUSER),
    .m_axi_emissions_0_RVALID(1'b0),
    .m_axi_emissions_0_RREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_RREADY),
    .m_axi_emissions_0_RDATA(32'd0),
    .m_axi_emissions_0_RLAST(1'b0),
    .m_axi_emissions_0_RID(1'd0),
    .m_axi_emissions_0_RFIFONUM(9'd0),
    .m_axi_emissions_0_RUSER(1'd0),
    .m_axi_emissions_0_RRESP(2'd0),
    .m_axi_emissions_0_BVALID(emissions_0_BVALID),
    .m_axi_emissions_0_BREADY(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_m_axi_emissions_0_BREADY),
    .m_axi_emissions_0_BRESP(emissions_0_BRESP),
    .m_axi_emissions_0_BID(emissions_0_BID),
    .m_axi_emissions_0_BUSER(emissions_0_BUSER),
    .emissions4(emissions_offset),
    .idx_0_ap_vld(1'b0),
    .emissions4_ap_vld(1'b1),
    .ap_start(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_start),
    .conv_ap_vld(1'b0),
    .psfSupersample_ap_vld(1'b1),
    .projShape0_ap_vld(1'b1),
    .projShape1_ap_vld(1'b1),
    .atomLocations1_ap_vld(1'b1),
    .fullImage2_ap_vld(1'b1),
    .imageProjs_local3_ap_vld(1'b1),
    .empty_ap_vld(1'b1),
    .ap_done(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_done),
    .ap_ready(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_ready),
    .ap_idle(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_idle),
    .ap_continue(dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_continue)
);

reconstruct_ap_bound ap_bound_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(atomLocationsSize),
    .if_full_n(ap_bound_full_n),
    .if_write(ap_bound_write),
    .if_dout(ap_bound_dout),
    .if_empty_n(ap_bound_empty_n),
    .if_read(ap_bound_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_bound_reg_ack <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (ap_internal_ready == 1'b0))) begin
            ap_bound_reg_ack <= ap_bound_ack;
        end else begin
            ap_bound_reg_ack <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_loop_dataflow_input_count <= 32'd0;
    end else begin
        if ((~(ap_loop_dataflow_input_count == ap_bound_minus_1) & (ap_real_start == 1'b1) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_ready == 1'b1))) begin
            ap_loop_dataflow_input_count <= (ap_loop_dataflow_input_count + 32'd1);
        end else if (((ap_real_start == 1'b1) & (ap_loop_dataflow_input_count == ap_bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_ready == 1'b1))) begin
            ap_loop_dataflow_input_count <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_loop_dataflow_output_count <= 32'd0;
    end else begin
        if ((~(ap_bound_dout <= 32'd0) & ~(ap_loop_dataflow_output_count == ap_bound_minus_1_output) & (1'b1 == ap_bound_empty_n) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_continue == 1'b1) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_done == 1'b1))) begin
            ap_loop_dataflow_output_count <= (ap_loop_dataflow_output_count + 32'd1);
        end else if ((~(ap_bound_dout <= 32'd0) & (1'b1 == ap_bound_empty_n) & (ap_loop_dataflow_output_count == ap_bound_minus_1_output) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_continue == 1'b1) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_done == 1'b1))) begin
            ap_loop_dataflow_output_count <= 32'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b0 == ap_bound_reg_ack))) begin
        ap_bound_write = 1'b1;
    end else begin
        ap_bound_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_loop_dataflow_output_count == 32'd0) & (1'b0 == ap_bound_empty_n) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_bound_empty_n) & ((32'd0 == ap_bound_dout) | ((ap_loop_dataflow_output_count == ap_bound_minus_1_output) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_done == 1'b1))))) begin
        ap_internal_done = 1'b1;
    end else begin
        ap_internal_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_partial_ready == 1'b1) | ((atomLocationsSize <= 32'd0) & (ap_start == 1'b1)))) begin
        ap_internal_ready = 1'b1;
    end else begin
        ap_internal_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_real_start == 1'b1) & (ap_loop_dataflow_input_count == ap_bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_ready == 1'b1))) begin
        ap_partial_ready = 1'b1;
    end else begin
        ap_partial_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(atomLocationsSize <= 32'd0) & (ap_start == 1'b1) & (1'b1 == ap_bound_ack))) begin
        ap_real_start = 1'b1;
    end else begin
        ap_real_start = 1'b0;
    end
end

assign ap_bound_ack = (ap_bound_reg_ack | ap_bound_full_n);

assign ap_bound_minus_1 = (atomLocationsSize - 32'd1);

assign ap_bound_minus_1_output = (ap_bound_dout - 32'd1);

assign ap_bound_read = (ap_internal_done & ap_bound_empty_n);

assign ap_done = ap_internal_done;

assign ap_ready = ap_internal_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign atomLocations_0_RID = 1'd0;

assign atomLocations_0_RLAST = 1'b0;

assign atomLocations_0_RRESP = 2'd0;

assign atomLocations_0_RUSER = 1'd0;

assign dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_start = ap_real_start;

assign dataflow_in_loop_VITIS_LOOP_152_1_1_U0_conv = ap_loop_dataflow_input_count;

assign dataflow_in_loop_VITIS_LOOP_152_1_1_U0_idx_0 = ap_loop_dataflow_input_count;

assign emissions_0_BID = 1'd0;

assign emissions_0_BRESP = 2'd0;

assign emissions_0_BUSER = 1'd0;

assign fullImage_0_RID = 1'd0;

assign fullImage_0_RLAST = 1'b0;

assign fullImage_0_RRESP = 2'd0;

assign fullImage_0_RUSER = 1'd0;

assign imageProjs_0_RID = 1'd0;

assign imageProjs_0_RLAST = 1'b0;

assign imageProjs_0_RRESP = 2'd0;

assign imageProjs_0_RUSER = 1'd0;

assign imageProjs_local_0_RID = 1'd0;

assign imageProjs_local_0_RLAST = 1'b0;

assign imageProjs_local_0_RRESP = 2'd0;

assign imageProjs_local_0_RUSER = 1'd0;

assign m_axi_imageProjs_local_size_ARADDR = 64'd0;

assign m_axi_imageProjs_local_size_ARBURST = 2'd0;

assign m_axi_imageProjs_local_size_ARCACHE = 4'd0;

assign m_axi_imageProjs_local_size_ARID = 1'd0;

assign m_axi_imageProjs_local_size_ARLEN = 8'd0;

assign m_axi_imageProjs_local_size_ARLOCK = 2'd0;

assign m_axi_imageProjs_local_size_ARPROT = 3'd0;

assign m_axi_imageProjs_local_size_ARQOS = 4'd0;

assign m_axi_imageProjs_local_size_ARREGION = 4'd0;

assign m_axi_imageProjs_local_size_ARSIZE = 3'd0;

assign m_axi_imageProjs_local_size_ARUSER = 1'd0;

assign m_axi_imageProjs_local_size_ARVALID = 1'b0;

assign m_axi_imageProjs_local_size_AWADDR = 64'd0;

assign m_axi_imageProjs_local_size_AWBURST = 2'd0;

assign m_axi_imageProjs_local_size_AWCACHE = 4'd0;

assign m_axi_imageProjs_local_size_AWID = 1'd0;

assign m_axi_imageProjs_local_size_AWLEN = 8'd0;

assign m_axi_imageProjs_local_size_AWLOCK = 2'd0;

assign m_axi_imageProjs_local_size_AWPROT = 3'd0;

assign m_axi_imageProjs_local_size_AWQOS = 4'd0;

assign m_axi_imageProjs_local_size_AWREGION = 4'd0;

assign m_axi_imageProjs_local_size_AWSIZE = 3'd0;

assign m_axi_imageProjs_local_size_AWUSER = 1'd0;

assign m_axi_imageProjs_local_size_AWVALID = 1'b0;

assign m_axi_imageProjs_local_size_BREADY = 1'b0;

assign m_axi_imageProjs_local_size_RREADY = 1'b0;

assign m_axi_imageProjs_local_size_WDATA = 32'd0;

assign m_axi_imageProjs_local_size_WID = 1'd0;

assign m_axi_imageProjs_local_size_WLAST = 1'b0;

assign m_axi_imageProjs_local_size_WSTRB = 4'd0;

assign m_axi_imageProjs_local_size_WUSER = 1'd0;

assign m_axi_imageProjs_local_size_WVALID = 1'b0;

assign dataflow_in_loop_VITIS_LOOP_152_1_1_U0_ap_continue = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "reconstruct_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //reconstruct

