// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module reconstruct_post_process (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        projSumUsed,
        sum,
        curr_imageProjs,
        m_axi_emissions_0_AWVALID,
        m_axi_emissions_0_AWREADY,
        m_axi_emissions_0_AWADDR,
        m_axi_emissions_0_AWID,
        m_axi_emissions_0_AWLEN,
        m_axi_emissions_0_AWSIZE,
        m_axi_emissions_0_AWBURST,
        m_axi_emissions_0_AWLOCK,
        m_axi_emissions_0_AWCACHE,
        m_axi_emissions_0_AWPROT,
        m_axi_emissions_0_AWQOS,
        m_axi_emissions_0_AWREGION,
        m_axi_emissions_0_AWUSER,
        m_axi_emissions_0_WVALID,
        m_axi_emissions_0_WREADY,
        m_axi_emissions_0_WDATA,
        m_axi_emissions_0_WSTRB,
        m_axi_emissions_0_WLAST,
        m_axi_emissions_0_WID,
        m_axi_emissions_0_WUSER,
        m_axi_emissions_0_ARVALID,
        m_axi_emissions_0_ARREADY,
        m_axi_emissions_0_ARADDR,
        m_axi_emissions_0_ARID,
        m_axi_emissions_0_ARLEN,
        m_axi_emissions_0_ARSIZE,
        m_axi_emissions_0_ARBURST,
        m_axi_emissions_0_ARLOCK,
        m_axi_emissions_0_ARCACHE,
        m_axi_emissions_0_ARPROT,
        m_axi_emissions_0_ARQOS,
        m_axi_emissions_0_ARREGION,
        m_axi_emissions_0_ARUSER,
        m_axi_emissions_0_RVALID,
        m_axi_emissions_0_RREADY,
        m_axi_emissions_0_RDATA,
        m_axi_emissions_0_RLAST,
        m_axi_emissions_0_RID,
        m_axi_emissions_0_RFIFONUM,
        m_axi_emissions_0_RUSER,
        m_axi_emissions_0_RRESP,
        m_axi_emissions_0_BVALID,
        m_axi_emissions_0_BREADY,
        m_axi_emissions_0_BRESP,
        m_axi_emissions_0_BID,
        m_axi_emissions_0_BUSER,
        dout
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] projSumUsed;
input  [31:0] sum;
input  [31:0] curr_imageProjs;
output   m_axi_emissions_0_AWVALID;
input   m_axi_emissions_0_AWREADY;
output  [63:0] m_axi_emissions_0_AWADDR;
output  [0:0] m_axi_emissions_0_AWID;
output  [31:0] m_axi_emissions_0_AWLEN;
output  [2:0] m_axi_emissions_0_AWSIZE;
output  [1:0] m_axi_emissions_0_AWBURST;
output  [1:0] m_axi_emissions_0_AWLOCK;
output  [3:0] m_axi_emissions_0_AWCACHE;
output  [2:0] m_axi_emissions_0_AWPROT;
output  [3:0] m_axi_emissions_0_AWQOS;
output  [3:0] m_axi_emissions_0_AWREGION;
output  [0:0] m_axi_emissions_0_AWUSER;
output   m_axi_emissions_0_WVALID;
input   m_axi_emissions_0_WREADY;
output  [31:0] m_axi_emissions_0_WDATA;
output  [3:0] m_axi_emissions_0_WSTRB;
output   m_axi_emissions_0_WLAST;
output  [0:0] m_axi_emissions_0_WID;
output  [0:0] m_axi_emissions_0_WUSER;
output   m_axi_emissions_0_ARVALID;
input   m_axi_emissions_0_ARREADY;
output  [63:0] m_axi_emissions_0_ARADDR;
output  [0:0] m_axi_emissions_0_ARID;
output  [31:0] m_axi_emissions_0_ARLEN;
output  [2:0] m_axi_emissions_0_ARSIZE;
output  [1:0] m_axi_emissions_0_ARBURST;
output  [1:0] m_axi_emissions_0_ARLOCK;
output  [3:0] m_axi_emissions_0_ARCACHE;
output  [2:0] m_axi_emissions_0_ARPROT;
output  [3:0] m_axi_emissions_0_ARQOS;
output  [3:0] m_axi_emissions_0_ARREGION;
output  [0:0] m_axi_emissions_0_ARUSER;
input   m_axi_emissions_0_RVALID;
output   m_axi_emissions_0_RREADY;
input  [31:0] m_axi_emissions_0_RDATA;
input   m_axi_emissions_0_RLAST;
input  [0:0] m_axi_emissions_0_RID;
input  [8:0] m_axi_emissions_0_RFIFONUM;
input  [0:0] m_axi_emissions_0_RUSER;
input  [1:0] m_axi_emissions_0_RRESP;
input   m_axi_emissions_0_BVALID;
output   m_axi_emissions_0_BREADY;
input  [1:0] m_axi_emissions_0_BRESP;
input  [0:0] m_axi_emissions_0_BID;
input  [0:0] m_axi_emissions_0_BUSER;
input  [63:0] dout;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_emissions_0_AWVALID;
reg m_axi_emissions_0_WVALID;
reg m_axi_emissions_0_BREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    emissions_blk_n_AW;
wire    ap_CS_fsm_state13;
reg    emissions_blk_n_W;
wire    ap_CS_fsm_state14;
reg    emissions_blk_n_B;
wire    ap_CS_fsm_state19;
reg   [31:0] curr_imageProjs_read_reg_120;
reg    ap_block_state1;
reg   [31:0] projSumUsed_read_reg_125;
reg   [31:0] sum_read_reg_130;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_92_p2;
reg   [31:0] div_i_reg_135;
reg   [63:0] emissions_addr_reg_140;
wire    ap_CS_fsm_state12;
wire   [31:0] grp_fu_88_p2;
reg   [31:0] mul_i_reg_146;
wire  signed [63:0] sext_ln116_fu_106_p1;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state2;
wire   [61:0] trunc_ln_fu_96_p4;
reg    grp_fu_88_ce;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 19'd1;
end

reconstruct_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U2215(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(div_i_reg_135),
    .din1(sum_read_reg_130),
    .ce(grp_fu_88_ce),
    .dout(grp_fu_88_p2)
);

reconstruct_fdiv_32ns_32ns_32_9_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_9_no_dsp_1_U2216(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_imageProjs_read_reg_120),
    .din1(projSumUsed_read_reg_125),
    .ce(1'b1),
    .dout(grp_fu_92_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((m_axi_emissions_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        curr_imageProjs_read_reg_120 <= curr_imageProjs;
        projSumUsed_read_reg_125 <= projSumUsed;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        div_i_reg_135 <= grp_fu_92_p2;
        sum_read_reg_130 <= sum;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        emissions_addr_reg_140 <= sext_ln116_fu_106_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_emissions_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        mul_i_reg_146 <= grp_fu_88_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((m_axi_emissions_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_emissions_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((m_axi_emissions_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((m_axi_emissions_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_emissions_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        emissions_blk_n_AW = m_axi_emissions_0_AWREADY;
    end else begin
        emissions_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        emissions_blk_n_B = m_axi_emissions_0_BVALID;
    end else begin
        emissions_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        emissions_blk_n_W = m_axi_emissions_0_WREADY;
    end else begin
        emissions_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12) | ((m_axi_emissions_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13)))) begin
        grp_fu_88_ce = 1'b1;
    end else begin
        grp_fu_88_ce = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_emissions_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_emissions_0_AWVALID = 1'b1;
    end else begin
        m_axi_emissions_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_emissions_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        m_axi_emissions_0_BREADY = 1'b1;
    end else begin
        m_axi_emissions_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_emissions_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        m_axi_emissions_0_WVALID = 1'b1;
    end else begin
        m_axi_emissions_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((m_axi_emissions_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((m_axi_emissions_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((m_axi_emissions_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign m_axi_emissions_0_ARADDR = 64'd0;

assign m_axi_emissions_0_ARBURST = 2'd0;

assign m_axi_emissions_0_ARCACHE = 4'd0;

assign m_axi_emissions_0_ARID = 1'd0;

assign m_axi_emissions_0_ARLEN = 32'd0;

assign m_axi_emissions_0_ARLOCK = 2'd0;

assign m_axi_emissions_0_ARPROT = 3'd0;

assign m_axi_emissions_0_ARQOS = 4'd0;

assign m_axi_emissions_0_ARREGION = 4'd0;

assign m_axi_emissions_0_ARSIZE = 3'd0;

assign m_axi_emissions_0_ARUSER = 1'd0;

assign m_axi_emissions_0_ARVALID = 1'b0;

assign m_axi_emissions_0_AWADDR = emissions_addr_reg_140;

assign m_axi_emissions_0_AWBURST = 2'd0;

assign m_axi_emissions_0_AWCACHE = 4'd0;

assign m_axi_emissions_0_AWID = 1'd0;

assign m_axi_emissions_0_AWLEN = 64'd1;

assign m_axi_emissions_0_AWLOCK = 2'd0;

assign m_axi_emissions_0_AWPROT = 3'd0;

assign m_axi_emissions_0_AWQOS = 4'd0;

assign m_axi_emissions_0_AWREGION = 4'd0;

assign m_axi_emissions_0_AWSIZE = 3'd0;

assign m_axi_emissions_0_AWUSER = 1'd0;

assign m_axi_emissions_0_RREADY = 1'b0;

assign m_axi_emissions_0_WDATA = mul_i_reg_146;

assign m_axi_emissions_0_WID = 1'd0;

assign m_axi_emissions_0_WLAST = 1'b0;

assign m_axi_emissions_0_WSTRB = 4'd15;

assign m_axi_emissions_0_WUSER = 1'd0;

assign sext_ln116_fu_106_p1 = $signed(trunc_ln_fu_96_p4);

assign trunc_ln_fu_96_p4 = {{dout[63:2]}};

endmodule //reconstruct_post_process
