// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module reconstruct_matrix_sum_prod_Pipeline_VITIS_LOOP_191_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        add76_i29_i,
        add76_i28_i,
        add76_i27_i,
        add76_i26_i,
        add76_i25_i,
        add76_i24_i,
        add76_i23_i,
        add76_i22_i,
        add76_i21_i,
        add76_i20_i,
        add76_i19_i,
        add76_i18_i,
        add76_i17_i,
        add76_i16_i,
        add76_i15_i,
        add76_i14_i,
        add76_i13_i,
        add76_i12_i,
        add76_i11_i,
        add76_i10_i,
        add76_i_i,
        add76_i9_i,
        add76_i8_i,
        add76_i7_i,
        add76_i6_i,
        add76_i5_i,
        add76_i4_i,
        add76_i3_i,
        add76_i2_i,
        add76_i1_i,
        prod_val_29_out,
        prod_val_29_out_ap_vld,
        sum_val_29_out,
        sum_val_29_out_ap_vld,
        prod_val_28_out,
        prod_val_28_out_ap_vld,
        sum_val_28_out,
        sum_val_28_out_ap_vld,
        prod_val_27_out,
        prod_val_27_out_ap_vld,
        sum_val_27_out,
        sum_val_27_out_ap_vld,
        prod_val_26_out,
        prod_val_26_out_ap_vld,
        sum_val_26_out,
        sum_val_26_out_ap_vld,
        prod_val_25_out,
        prod_val_25_out_ap_vld,
        sum_val_25_out,
        sum_val_25_out_ap_vld,
        prod_val_24_out,
        prod_val_24_out_ap_vld,
        sum_val_24_out,
        sum_val_24_out_ap_vld,
        prod_val_23_out,
        prod_val_23_out_ap_vld,
        sum_val_23_out,
        sum_val_23_out_ap_vld,
        prod_val_22_out,
        prod_val_22_out_ap_vld,
        sum_val_22_out,
        sum_val_22_out_ap_vld,
        prod_val_21_out,
        prod_val_21_out_ap_vld,
        sum_val_21_out,
        sum_val_21_out_ap_vld,
        prod_val_20_out,
        prod_val_20_out_ap_vld,
        sum_val_20_out,
        sum_val_20_out_ap_vld,
        prod_val_19_out,
        prod_val_19_out_ap_vld,
        sum_val_19_out,
        sum_val_19_out_ap_vld,
        prod_val_18_out,
        prod_val_18_out_ap_vld,
        sum_val_18_out,
        sum_val_18_out_ap_vld,
        prod_val_17_out,
        prod_val_17_out_ap_vld,
        sum_val_17_out,
        sum_val_17_out_ap_vld,
        prod_val_16_out,
        prod_val_16_out_ap_vld,
        sum_val_16_out,
        sum_val_16_out_ap_vld,
        prod_val_15_out,
        prod_val_15_out_ap_vld,
        sum_val_15_out,
        sum_val_15_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] add76_i29_i;
input  [31:0] add76_i28_i;
input  [31:0] add76_i27_i;
input  [31:0] add76_i26_i;
input  [31:0] add76_i25_i;
input  [31:0] add76_i24_i;
input  [31:0] add76_i23_i;
input  [31:0] add76_i22_i;
input  [31:0] add76_i21_i;
input  [31:0] add76_i20_i;
input  [31:0] add76_i19_i;
input  [31:0] add76_i18_i;
input  [31:0] add76_i17_i;
input  [31:0] add76_i16_i;
input  [31:0] add76_i15_i;
input  [31:0] add76_i14_i;
input  [31:0] add76_i13_i;
input  [31:0] add76_i12_i;
input  [31:0] add76_i11_i;
input  [31:0] add76_i10_i;
input  [31:0] add76_i_i;
input  [31:0] add76_i9_i;
input  [31:0] add76_i8_i;
input  [31:0] add76_i7_i;
input  [31:0] add76_i6_i;
input  [31:0] add76_i5_i;
input  [31:0] add76_i4_i;
input  [31:0] add76_i3_i;
input  [31:0] add76_i2_i;
input  [31:0] add76_i1_i;
output  [31:0] prod_val_29_out;
output   prod_val_29_out_ap_vld;
output  [31:0] sum_val_29_out;
output   sum_val_29_out_ap_vld;
output  [31:0] prod_val_28_out;
output   prod_val_28_out_ap_vld;
output  [31:0] sum_val_28_out;
output   sum_val_28_out_ap_vld;
output  [31:0] prod_val_27_out;
output   prod_val_27_out_ap_vld;
output  [31:0] sum_val_27_out;
output   sum_val_27_out_ap_vld;
output  [31:0] prod_val_26_out;
output   prod_val_26_out_ap_vld;
output  [31:0] sum_val_26_out;
output   sum_val_26_out_ap_vld;
output  [31:0] prod_val_25_out;
output   prod_val_25_out_ap_vld;
output  [31:0] sum_val_25_out;
output   sum_val_25_out_ap_vld;
output  [31:0] prod_val_24_out;
output   prod_val_24_out_ap_vld;
output  [31:0] sum_val_24_out;
output   sum_val_24_out_ap_vld;
output  [31:0] prod_val_23_out;
output   prod_val_23_out_ap_vld;
output  [31:0] sum_val_23_out;
output   sum_val_23_out_ap_vld;
output  [31:0] prod_val_22_out;
output   prod_val_22_out_ap_vld;
output  [31:0] sum_val_22_out;
output   sum_val_22_out_ap_vld;
output  [31:0] prod_val_21_out;
output   prod_val_21_out_ap_vld;
output  [31:0] sum_val_21_out;
output   sum_val_21_out_ap_vld;
output  [31:0] prod_val_20_out;
output   prod_val_20_out_ap_vld;
output  [31:0] sum_val_20_out;
output   sum_val_20_out_ap_vld;
output  [31:0] prod_val_19_out;
output   prod_val_19_out_ap_vld;
output  [31:0] sum_val_19_out;
output   sum_val_19_out_ap_vld;
output  [31:0] prod_val_18_out;
output   prod_val_18_out_ap_vld;
output  [31:0] sum_val_18_out;
output   sum_val_18_out_ap_vld;
output  [31:0] prod_val_17_out;
output   prod_val_17_out_ap_vld;
output  [31:0] sum_val_17_out;
output   sum_val_17_out_ap_vld;
output  [31:0] prod_val_16_out;
output   prod_val_16_out_ap_vld;
output  [31:0] sum_val_16_out;
output   sum_val_16_out_ap_vld;
output  [31:0] prod_val_15_out;
output   prod_val_15_out_ap_vld;
output  [31:0] sum_val_15_out;
output   sum_val_15_out_ap_vld;

reg ap_idle;
reg prod_val_29_out_ap_vld;
reg sum_val_29_out_ap_vld;
reg prod_val_28_out_ap_vld;
reg sum_val_28_out_ap_vld;
reg prod_val_27_out_ap_vld;
reg sum_val_27_out_ap_vld;
reg prod_val_26_out_ap_vld;
reg sum_val_26_out_ap_vld;
reg prod_val_25_out_ap_vld;
reg sum_val_25_out_ap_vld;
reg prod_val_24_out_ap_vld;
reg sum_val_24_out_ap_vld;
reg prod_val_23_out_ap_vld;
reg sum_val_23_out_ap_vld;
reg prod_val_22_out_ap_vld;
reg sum_val_22_out_ap_vld;
reg prod_val_21_out_ap_vld;
reg sum_val_21_out_ap_vld;
reg prod_val_20_out_ap_vld;
reg sum_val_20_out_ap_vld;
reg prod_val_19_out_ap_vld;
reg sum_val_19_out_ap_vld;
reg prod_val_18_out_ap_vld;
reg sum_val_18_out_ap_vld;
reg prod_val_17_out_ap_vld;
reg sum_val_17_out_ap_vld;
reg prod_val_16_out_ap_vld;
reg sum_val_16_out_ap_vld;
reg prod_val_15_out_ap_vld;
reg sum_val_15_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln195_fu_676_p2;
wire   [0:0] icmp_ln191_fu_698_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] i_fu_154;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
reg   [31:0] sum_val_15_fu_158;
reg   [31:0] prod_val_15_fu_162;
reg   [31:0] sum_val_16_fu_166;
reg   [31:0] prod_val_16_fu_170;
reg   [31:0] sum_val_17_fu_174;
reg   [31:0] prod_val_17_fu_178;
reg   [31:0] sum_val_18_fu_182;
reg   [31:0] prod_val_18_fu_186;
reg   [31:0] sum_val_19_fu_190;
reg   [31:0] prod_val_19_fu_194;
reg   [31:0] sum_val_20_fu_198;
reg   [31:0] prod_val_20_fu_202;
reg   [31:0] sum_val_21_fu_206;
reg   [31:0] prod_val_21_fu_210;
reg   [31:0] sum_val_22_fu_214;
reg   [31:0] prod_val_22_fu_218;
reg   [31:0] sum_val_23_fu_222;
reg   [31:0] prod_val_23_fu_226;
reg   [31:0] sum_val_24_fu_230;
reg   [31:0] prod_val_24_fu_234;
reg   [31:0] sum_val_25_fu_238;
reg   [31:0] prod_val_25_fu_242;
reg   [31:0] sum_val_26_fu_246;
reg   [31:0] prod_val_26_fu_250;
reg   [31:0] sum_val_27_fu_254;
reg   [31:0] prod_val_27_fu_258;
reg   [31:0] sum_val_28_fu_262;
reg   [31:0] prod_val_28_fu_266;
reg   [31:0] sum_val_29_fu_270;
reg   [31:0] prod_val_29_fu_274;
wire   [0:0] tmp_fu_682_p3;
wire   [4:0] or_ln_fu_690_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_154 = 5'd0;
#0 sum_val_15_fu_158 = 32'd0;
#0 prod_val_15_fu_162 = 32'd0;
#0 sum_val_16_fu_166 = 32'd0;
#0 prod_val_16_fu_170 = 32'd0;
#0 sum_val_17_fu_174 = 32'd0;
#0 prod_val_17_fu_178 = 32'd0;
#0 sum_val_18_fu_182 = 32'd0;
#0 prod_val_18_fu_186 = 32'd0;
#0 sum_val_19_fu_190 = 32'd0;
#0 prod_val_19_fu_194 = 32'd0;
#0 sum_val_20_fu_198 = 32'd0;
#0 prod_val_20_fu_202 = 32'd0;
#0 sum_val_21_fu_206 = 32'd0;
#0 prod_val_21_fu_210 = 32'd0;
#0 sum_val_22_fu_214 = 32'd0;
#0 prod_val_22_fu_218 = 32'd0;
#0 sum_val_23_fu_222 = 32'd0;
#0 prod_val_23_fu_226 = 32'd0;
#0 sum_val_24_fu_230 = 32'd0;
#0 prod_val_24_fu_234 = 32'd0;
#0 sum_val_25_fu_238 = 32'd0;
#0 prod_val_25_fu_242 = 32'd0;
#0 sum_val_26_fu_246 = 32'd0;
#0 prod_val_26_fu_250 = 32'd0;
#0 sum_val_27_fu_254 = 32'd0;
#0 prod_val_27_fu_258 = 32'd0;
#0 sum_val_28_fu_262 = 32'd0;
#0 prod_val_28_fu_266 = 32'd0;
#0 sum_val_29_fu_270 = 32'd0;
#0 prod_val_29_fu_274 = 32'd0;
#0 ap_done_reg = 1'b0;
end

reconstruct_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if (((icmp_ln191_fu_698_p2 == 1'd0) | (icmp_ln195_fu_676_p2 == 1'd1))) begin
                        i_fu_154[4] <= 1'b1;
        end else if ((ap_loop_init == 1'b1)) begin
                        i_fu_154[4] <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln195_fu_676_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_15_fu_162 <= add76_i2_i;
        prod_val_16_fu_170 <= add76_i4_i;
        prod_val_17_fu_178 <= add76_i6_i;
        prod_val_18_fu_186 <= add76_i8_i;
        prod_val_19_fu_194 <= add76_i_i;
        prod_val_20_fu_202 <= add76_i11_i;
        prod_val_21_fu_210 <= add76_i13_i;
        prod_val_22_fu_218 <= add76_i15_i;
        prod_val_23_fu_226 <= add76_i17_i;
        prod_val_24_fu_234 <= add76_i19_i;
        prod_val_25_fu_242 <= add76_i21_i;
        prod_val_26_fu_250 <= add76_i23_i;
        prod_val_27_fu_258 <= add76_i25_i;
        prod_val_28_fu_266 <= add76_i27_i;
        prod_val_29_fu_274 <= add76_i29_i;
        sum_val_15_fu_158 <= add76_i1_i;
        sum_val_16_fu_166 <= add76_i3_i;
        sum_val_17_fu_174 <= add76_i5_i;
        sum_val_18_fu_182 <= add76_i7_i;
        sum_val_19_fu_190 <= add76_i9_i;
        sum_val_20_fu_198 <= add76_i10_i;
        sum_val_21_fu_206 <= add76_i12_i;
        sum_val_22_fu_214 <= add76_i14_i;
        sum_val_23_fu_222 <= add76_i16_i;
        sum_val_24_fu_230 <= add76_i18_i;
        sum_val_25_fu_238 <= add76_i20_i;
        sum_val_26_fu_246 <= add76_i22_i;
        sum_val_27_fu_254 <= add76_i24_i;
        sum_val_28_fu_262 <= add76_i26_i;
        sum_val_29_fu_270 <= add76_i28_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_154;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_15_out_ap_vld = 1'b1;
    end else begin
        prod_val_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_16_out_ap_vld = 1'b1;
    end else begin
        prod_val_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_17_out_ap_vld = 1'b1;
    end else begin
        prod_val_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_18_out_ap_vld = 1'b1;
    end else begin
        prod_val_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_19_out_ap_vld = 1'b1;
    end else begin
        prod_val_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_20_out_ap_vld = 1'b1;
    end else begin
        prod_val_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_21_out_ap_vld = 1'b1;
    end else begin
        prod_val_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_22_out_ap_vld = 1'b1;
    end else begin
        prod_val_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_23_out_ap_vld = 1'b1;
    end else begin
        prod_val_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_24_out_ap_vld = 1'b1;
    end else begin
        prod_val_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_25_out_ap_vld = 1'b1;
    end else begin
        prod_val_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_26_out_ap_vld = 1'b1;
    end else begin
        prod_val_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_27_out_ap_vld = 1'b1;
    end else begin
        prod_val_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_28_out_ap_vld = 1'b1;
    end else begin
        prod_val_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_val_29_out_ap_vld = 1'b1;
    end else begin
        prod_val_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_15_out_ap_vld = 1'b1;
    end else begin
        sum_val_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_16_out_ap_vld = 1'b1;
    end else begin
        sum_val_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_17_out_ap_vld = 1'b1;
    end else begin
        sum_val_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_18_out_ap_vld = 1'b1;
    end else begin
        sum_val_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_19_out_ap_vld = 1'b1;
    end else begin
        sum_val_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_20_out_ap_vld = 1'b1;
    end else begin
        sum_val_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_21_out_ap_vld = 1'b1;
    end else begin
        sum_val_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_22_out_ap_vld = 1'b1;
    end else begin
        sum_val_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_23_out_ap_vld = 1'b1;
    end else begin
        sum_val_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_24_out_ap_vld = 1'b1;
    end else begin
        sum_val_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_25_out_ap_vld = 1'b1;
    end else begin
        sum_val_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_26_out_ap_vld = 1'b1;
    end else begin
        sum_val_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_27_out_ap_vld = 1'b1;
    end else begin
        sum_val_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_28_out_ap_vld = 1'b1;
    end else begin
        sum_val_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln191_fu_698_p2 == 1'd1) & (icmp_ln195_fu_676_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_val_29_out_ap_vld = 1'b1;
    end else begin
        sum_val_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln191_fu_698_p2 = ((or_ln_fu_690_p3 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln195_fu_676_p2 = ((ap_sig_allocacmp_i_1 == 5'd0) ? 1'b1 : 1'b0);

assign or_ln_fu_690_p3 = {{tmp_fu_682_p3}, {4'd15}};

assign prod_val_15_out = prod_val_15_fu_162;

assign prod_val_16_out = prod_val_16_fu_170;

assign prod_val_17_out = prod_val_17_fu_178;

assign prod_val_18_out = prod_val_18_fu_186;

assign prod_val_19_out = prod_val_19_fu_194;

assign prod_val_20_out = prod_val_20_fu_202;

assign prod_val_21_out = prod_val_21_fu_210;

assign prod_val_22_out = prod_val_22_fu_218;

assign prod_val_23_out = prod_val_23_fu_226;

assign prod_val_24_out = prod_val_24_fu_234;

assign prod_val_25_out = prod_val_25_fu_242;

assign prod_val_26_out = prod_val_26_fu_250;

assign prod_val_27_out = prod_val_27_fu_258;

assign prod_val_28_out = prod_val_28_fu_266;

assign prod_val_29_out = prod_val_29_fu_274;

assign sum_val_15_out = sum_val_15_fu_158;

assign sum_val_16_out = sum_val_16_fu_166;

assign sum_val_17_out = sum_val_17_fu_174;

assign sum_val_18_out = sum_val_18_fu_182;

assign sum_val_19_out = sum_val_19_fu_190;

assign sum_val_20_out = sum_val_20_fu_198;

assign sum_val_21_out = sum_val_21_fu_206;

assign sum_val_22_out = sum_val_22_fu_214;

assign sum_val_23_out = sum_val_23_fu_222;

assign sum_val_24_out = sum_val_24_fu_230;

assign sum_val_25_out = sum_val_25_fu_238;

assign sum_val_26_out = sum_val_26_fu_246;

assign sum_val_27_out = sum_val_27_fu_254;

assign sum_val_28_out = sum_val_28_fu_262;

assign sum_val_29_out = sum_val_29_fu_270;

assign tmp_fu_682_p3 = ap_sig_allocacmp_i_1[32'd4];

always @ (posedge ap_clk) begin
    i_fu_154[3:0] <= 4'b0000;
end

endmodule //reconstruct_matrix_sum_prod_Pipeline_VITIS_LOOP_191_1
