-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reconstruct_getLocalImages_single is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    curr_idx : IN STD_LOGIC_VECTOR (15 downto 0);
    psfSupersample : IN STD_LOGIC_VECTOR (31 downto 0);
    projShape0 : IN STD_LOGIC_VECTOR (31 downto 0);
    projShape1 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_atomLocations_0_AWVALID : OUT STD_LOGIC;
    m_axi_atomLocations_0_AWREADY : IN STD_LOGIC;
    m_axi_atomLocations_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_atomLocations_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_atomLocations_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_atomLocations_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_atomLocations_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_atomLocations_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_atomLocations_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_atomLocations_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_atomLocations_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_atomLocations_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_WVALID : OUT STD_LOGIC;
    m_axi_atomLocations_0_WREADY : IN STD_LOGIC;
    m_axi_atomLocations_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_atomLocations_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_atomLocations_0_WLAST : OUT STD_LOGIC;
    m_axi_atomLocations_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_ARVALID : OUT STD_LOGIC;
    m_axi_atomLocations_0_ARREADY : IN STD_LOGIC;
    m_axi_atomLocations_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_atomLocations_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_atomLocations_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_atomLocations_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_atomLocations_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_atomLocations_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_atomLocations_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_atomLocations_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_atomLocations_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_atomLocations_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_RVALID : IN STD_LOGIC;
    m_axi_atomLocations_0_RREADY : OUT STD_LOGIC;
    m_axi_atomLocations_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_atomLocations_0_RLAST : IN STD_LOGIC;
    m_axi_atomLocations_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_atomLocations_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_atomLocations_0_BVALID : IN STD_LOGIC;
    m_axi_atomLocations_0_BREADY : OUT STD_LOGIC;
    m_axi_atomLocations_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_atomLocations_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_atomLocations_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    atomLocations1 : IN STD_LOGIC_VECTOR (63 downto 0);
    localImages_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    localImages_full_n : IN STD_LOGIC;
    localImages_write : OUT STD_LOGIC;
    localImages_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    localImages_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of reconstruct_getLocalImages_single is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (26 downto 0) := "000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (26 downto 0) := "000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (26 downto 0) := "000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (26 downto 0) := "000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (26 downto 0) := "000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (26 downto 0) := "000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (26 downto 0) := "000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (26 downto 0) := "000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (26 downto 0) := "000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (26 downto 0) := "001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (26 downto 0) := "010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (26 downto 0) := "100000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_96 : STD_LOGIC_VECTOR (7 downto 0) := "10010110";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv23_7FFFFF : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal mask_table_q0 : STD_LOGIC_VECTOR (22 downto 0);
    signal mask_table_q1 : STD_LOGIC_VECTOR (22 downto 0);
    signal one_half_table_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal one_half_table_q1 : STD_LOGIC_VECTOR (23 downto 0);
    signal atomLocations_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal atomLocations_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal localImages_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal grp_fu_309_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_315 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal trunc_ln8_fu_340_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln8_reg_1681 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal icmp_ln8_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1686 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln8_fu_350_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln8_reg_1690 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln8_1_reg_1695 : STD_LOGIC_VECTOR (60 downto 0);
    signal projShape1_read_reg_1706 : STD_LOGIC_VECTOR (31 downto 0);
    signal projShape0_read_reg_1714 : STD_LOGIC_VECTOR (31 downto 0);
    signal psfSupersample_read_reg_1722 : STD_LOGIC_VECTOR (31 downto 0);
    signal atomLocations_addr_read_reg_1727 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln8_2_fu_378_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal data_13_fu_406_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_13_reg_1737 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal data_12_reg_1743 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln167_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_reg_1749 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_1755 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_reg_1760 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_1_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_1_reg_1775 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1781 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_1_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_1_reg_1786 : STD_LOGIC_VECTOR (0 downto 0);
    signal coord_x_fu_512_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal coord_x_reg_1801 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal coord_y_fu_515_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal coord_y_reg_1806 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_12_fu_741_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_12_reg_1811 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_13_fu_972_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_13_reg_1818 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_312_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2_reg_1825 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_293_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_1830 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_297_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub1_reg_1835 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_301_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_6_reg_1840 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal grp_fu_305_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_9_reg_1846 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_14_fu_980_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_14_reg_1852 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal icmp_ln167_2_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_2_reg_1857 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_1863 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_2_fu_1005_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_2_reg_1868 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_15_fu_1027_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_15_reg_1883 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln167_3_fu_1038_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln167_3_reg_1888 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_1894 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_3_fu_1052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_3_reg_1899 : STD_LOGIC_VECTOR (0 downto 0);
    signal dc_7_fu_1149_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_7_reg_1914 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal dc_10_fu_1243_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_10_reg_1919 : STD_LOGIC_VECTOR (31 downto 0);
    signal phi_ln8_reg_282 : STD_LOGIC_VECTOR (55 downto 0);
    signal zext_ln179_fu_460_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln179_1_fu_506_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln179_2_fu_1021_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln179_3_fu_1068_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln8_fu_368_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal mask_table_ce1_local : STD_LOGIC;
    signal mask_table_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal mask_table_ce0_local : STD_LOGIC;
    signal mask_table_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal one_half_table_ce1_local : STD_LOGIC;
    signal one_half_table_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal one_half_table_ce0_local : STD_LOGIC;
    signal one_half_table_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal grp_fu_309_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal shl_ln8_fu_322_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln8_fu_330_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln8_fu_334_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln8_1_fu_389_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_382_p3 : STD_LOGIC_VECTOR (119 downto 0);
    signal zext_ln8_1_fu_396_p1 : STD_LOGIC_VECTOR (119 downto 0);
    signal lshr_ln8_fu_400_p2 : STD_LOGIC_VECTOR (119 downto 0);
    signal xs_exp_4_fu_420_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal index_fu_450_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal xs_exp_5_fu_466_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal index_1_fu_496_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal t_fu_518_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal one_half_cast_i_fu_529_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_2_fu_533_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln301_fu_538_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal xor_ln184_fu_542_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_8_i_fu_554_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal xs_sig_fu_548_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal t_11_fu_564_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln167_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln170_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dc_1_fu_593_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_1_fu_593_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_1_fu_593_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_1_fu_593_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_1_fu_593_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_1_fu_593_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_fu_613_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_fu_633_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_fu_637_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_fu_625_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_fu_651_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_655_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_fu_669_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_661_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_fu_675_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_fu_679_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_1_fu_687_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_647_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_fu_691_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_fu_695_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_fu_701_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_2_fu_707_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_717_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_fu_727_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_fu_617_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_2_fu_735_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_12_fu_749_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal one_half_cast_i18_fu_760_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_4_fu_764_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln301_1_fu_769_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal xor_ln184_1_fu_773_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_8_i1_fu_785_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal xs_sig_1_fu_779_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal t_13_fu_795_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln167_1_fu_807_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln170_1_fu_812_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dc_4_fu_824_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_4_fu_824_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_4_fu_824_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_4_fu_824_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_4_fu_824_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_4_fu_824_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_5_fu_844_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_1_fu_864_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_1_fu_868_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_1_fu_856_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_1_fu_882_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_1_fu_886_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_1_fu_900_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_892_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_2_fu_906_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_2_fu_910_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_3_fu_918_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_1_fu_878_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_1_fu_922_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_1_fu_926_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_1_fu_932_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_4_fu_938_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_948_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_1_fu_958_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_1_fu_848_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_5_fu_966_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_exp_6_fu_983_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal index_2_fu_1011_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal xs_exp_7_fu_1030_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal index_3_fu_1058_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal t_14_fu_1074_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal one_half_cast_i43_fu_1085_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_7_fu_1089_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln301_2_fu_1094_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal xor_ln184_2_fu_1098_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_8_i2_fu_1110_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal xs_sig_2_fu_1104_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal t_15_fu_1120_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln167_2_fu_1132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln170_2_fu_1137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dc_7_fu_1149_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_7_fu_1149_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_7_fu_1149_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_7_fu_1149_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal t_16_fu_1168_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal one_half_cast_i68_fu_1179_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_10_fu_1183_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln301_3_fu_1188_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal xor_ln184_3_fu_1192_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_8_i3_fu_1204_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal xs_sig_3_fu_1198_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal t_17_fu_1214_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln167_3_fu_1226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln170_3_fu_1231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dc_10_fu_1243_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_10_fu_1243_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_10_fu_1243_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_10_fu_1243_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln15_fu_1269_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln15_1_fu_1274_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_15_fu_1262_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln15_1_fu_1284_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal lshr_ln15_2_fu_1290_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln15_fu_1299_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln15_fu_1307_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln16_fu_1323_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln16_1_fu_1328_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_16_fu_1316_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln16_1_fu_1338_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal lshr_ln16_2_fu_1344_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln16_fu_1353_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln16_fu_1361_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal info_Y_min_fu_1311_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln17_fu_1370_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal info_X_min_fu_1365_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln18_fu_1381_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_8_fu_1392_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_2_fu_1411_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_2_fu_1415_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_2_fu_1403_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_2_fu_1429_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_2_fu_1433_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_2_fu_1447_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_1439_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_4_fu_1453_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_4_fu_1457_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_5_fu_1465_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_2_fu_1425_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_2_fu_1469_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_2_fu_1473_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_2_fu_1479_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_6_fu_1485_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_1495_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_2_fu_1505_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_2_fu_1395_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_9_fu_1513_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_11_fu_1527_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_3_fu_1546_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_3_fu_1550_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_3_fu_1538_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_3_fu_1564_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_3_fu_1568_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_3_fu_1582_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_1574_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_6_fu_1588_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_6_fu_1592_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_7_fu_1600_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_3_fu_1560_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_3_fu_1604_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_3_fu_1608_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_3_fu_1614_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_8_fu_1620_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_1630_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_3_fu_1640_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_3_fu_1530_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_10_fu_1648_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_fu_1654_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_14_fu_1519_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal info_Y_max_fu_1376_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal info_X_max_fu_1387_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal dc_1_fu_593_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_1_fu_593_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_1_fu_593_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_4_fu_824_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_4_fu_824_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_4_fu_824_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_7_fu_1149_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_7_fu_1149_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_7_fu_1149_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_10_fu_1243_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_10_fu_1243_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal dc_10_fu_1243_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component reconstruct_fsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component reconstruct_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component reconstruct_sitofp_32ns_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component reconstruct_sparsemux_7_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component reconstruct_getLocalImages_single_mask_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (22 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component reconstruct_getLocalImages_single_one_half_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    mask_table_U : component reconstruct_getLocalImages_single_mask_table_ROM_AUTO_1R
    generic map (
        DataWidth => 23,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => mask_table_address0_local,
        ce0 => mask_table_ce0_local,
        q0 => mask_table_q0,
        address1 => mask_table_address1_local,
        ce1 => mask_table_ce1_local,
        q1 => mask_table_q1);

    one_half_table_U : component reconstruct_getLocalImages_single_one_half_table_ROM_AUTO_1R
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => one_half_table_address0_local,
        ce0 => one_half_table_ce0_local,
        q0 => one_half_table_q0,
        address1 => one_half_table_address1_local,
        ce1 => one_half_table_ce1_local,
        q1 => one_half_table_q1);

    fsub_32ns_32ns_32_4_full_dsp_1_U3 : component reconstruct_fsub_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => coord_x_reg_1801,
        din1 => reg_315,
        ce => ap_const_logic_1,
        dout => grp_fu_293_p2);

    fsub_32ns_32ns_32_4_full_dsp_1_U4 : component reconstruct_fsub_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => coord_y_reg_1806,
        din1 => conv2_reg_1825,
        ce => ap_const_logic_1,
        dout => grp_fu_297_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U5 : component reconstruct_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub_reg_1830,
        din1 => reg_315,
        ce => ap_const_logic_1,
        dout => grp_fu_301_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U6 : component reconstruct_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sub1_reg_1835,
        din1 => reg_315,
        ce => ap_const_logic_1,
        dout => grp_fu_305_p2);

    sitofp_32ns_32_4_no_dsp_1_U7 : component reconstruct_sitofp_32ns_32_4_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_309_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_309_p1);

    sitofp_32ns_32_4_no_dsp_1_U8 : component reconstruct_sitofp_32ns_32_4_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => result_12_reg_1811,
        ce => ap_const_logic_1,
        dout => grp_fu_312_p1);

    sparsemux_7_2_32_1_1_U9 : component reconstruct_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => dc_1_fu_593_p2,
        din1 => dc_1_fu_593_p4,
        din2 => dc_1_fu_593_p6,
        def => dc_1_fu_593_p7,
        sel => dc_1_fu_593_p8,
        dout => dc_1_fu_593_p9);

    sparsemux_7_2_32_1_1_U10 : component reconstruct_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => dc_4_fu_824_p2,
        din1 => dc_4_fu_824_p4,
        din2 => dc_4_fu_824_p6,
        def => dc_4_fu_824_p7,
        sel => dc_4_fu_824_p8,
        dout => dc_4_fu_824_p9);

    sparsemux_7_2_32_1_1_U11 : component reconstruct_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => dc_7_fu_1149_p2,
        din1 => dc_6_reg_1840,
        din2 => dc_7_fu_1149_p6,
        def => dc_7_fu_1149_p7,
        sel => dc_7_fu_1149_p8,
        dout => dc_7_fu_1149_p9);

    sparsemux_7_2_32_1_1_U12 : component reconstruct_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => dc_10_fu_1243_p2,
        din1 => dc_9_reg_1846,
        din2 => dc_10_fu_1243_p6,
        def => dc_10_fu_1243_p7,
        sel => dc_10_fu_1243_p8,
        dout => dc_10_fu_1243_p9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state27) and (localImages_full_n = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_atomLocations_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                atomLocations_addr_read_reg_1727 <= m_axi_atomLocations_0_RDATA;
                projShape0_read_reg_1714 <= projShape0;
                projShape1_read_reg_1706 <= projShape1;
                psfSupersample_read_reg_1722 <= psfSupersample;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                conv2_reg_1825 <= grp_fu_312_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                coord_x_reg_1801 <= coord_x_fu_512_p1;
                coord_y_reg_1806 <= coord_y_fu_515_p1;
                result_12_reg_1811 <= result_12_fu_741_p3;
                result_13_reg_1818 <= result_13_fu_972_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                data_12_reg_1743 <= lshr_ln8_fu_400_p2(63 downto 32);
                data_13_reg_1737 <= data_13_fu_406_p1;
                icmp_ln167_1_reg_1775 <= icmp_ln167_1_fu_476_p2;
                icmp_ln167_reg_1749 <= icmp_ln167_fu_430_p2;
                icmp_ln170_1_reg_1786 <= icmp_ln170_1_fu_490_p2;
                icmp_ln170_reg_1760 <= icmp_ln170_fu_444_p2;
                tmp_12_reg_1781 <= lshr_ln8_fu_400_p2(31 downto 31);
                tmp_1_reg_1755 <= lshr_ln8_fu_400_p2(63 downto 63);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state25)) then
                data_14_reg_1852 <= data_14_fu_980_p1;
                data_15_reg_1883 <= data_15_fu_1027_p1;
                icmp_ln167_2_reg_1857 <= icmp_ln167_2_fu_991_p2;
                icmp_ln167_3_reg_1888 <= icmp_ln167_3_fu_1038_p2;
                icmp_ln170_2_reg_1868 <= icmp_ln170_2_fu_1005_p2;
                icmp_ln170_3_reg_1899 <= icmp_ln170_3_fu_1052_p2;
                tmp_17_reg_1863 <= data_14_fu_980_p1(31 downto 31);
                tmp_20_reg_1894 <= data_15_fu_1027_p1(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state26)) then
                dc_10_reg_1919 <= dc_10_fu_1243_p9;
                dc_7_reg_1914 <= dc_7_fu_1149_p9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state24)) then
                dc_6_reg_1840 <= grp_fu_301_p2;
                dc_9_reg_1846 <= grp_fu_305_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                icmp_ln8_reg_1686 <= icmp_ln8_fu_344_p2;
                    select_ln8_reg_1690(1 downto 0) <= select_ln8_fu_350_p3(1 downto 0);
                trunc_ln8_1_reg_1695 <= add_ln8_fu_334_p2(63 downto 3);
                trunc_ln8_reg_1681 <= trunc_ln8_fu_340_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_atomLocations_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                phi_ln8_reg_282 <= trunc_ln8_2_fu_378_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state17))) then
                reg_315 <= grp_fu_309_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                sub1_reg_1835 <= grp_fu_297_p2;
                sub_reg_1830 <= grp_fu_293_p2;
            end if;
        end if;
    end process;
    select_ln8_reg_1690(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, m_axi_atomLocations_0_ARREADY, m_axi_atomLocations_0_RVALID, localImages_full_n, ap_CS_fsm_state2, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state27, ap_block_state1, icmp_ln8_reg_1686)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((m_axi_atomLocations_0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((m_axi_atomLocations_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln8_reg_1686 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                elsif (((m_axi_atomLocations_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln8_reg_1686 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((m_axi_atomLocations_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state27) and (localImages_full_n = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state27;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln17_fu_1370_p2 <= std_logic_vector(unsigned(info_Y_min_fu_1311_p2) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln18_fu_1381_p2 <= std_logic_vector(unsigned(info_X_min_fu_1365_p2) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln317_1_fu_886_p2 <= std_logic_vector(unsigned(zext_ln317_1_fu_882_p1) + unsigned(ap_const_lv9_181));
    add_ln317_2_fu_1433_p2 <= std_logic_vector(unsigned(zext_ln317_2_fu_1429_p1) + unsigned(ap_const_lv9_181));
    add_ln317_3_fu_1568_p2 <= std_logic_vector(unsigned(zext_ln317_3_fu_1564_p1) + unsigned(ap_const_lv9_181));
    add_ln317_fu_655_p2 <= std_logic_vector(unsigned(zext_ln317_fu_651_p1) + unsigned(ap_const_lv9_181));
    add_ln8_fu_334_p2 <= std_logic_vector(unsigned(zext_ln8_fu_330_p1) + unsigned(atomLocations1));
    and_ln170_1_fu_812_p2 <= (xor_ln167_1_fu_807_p2 and icmp_ln170_1_reg_1786);
    and_ln170_2_fu_1137_p2 <= (xor_ln167_2_fu_1132_p2 and icmp_ln170_2_reg_1868);
    and_ln170_3_fu_1231_p2 <= (xor_ln167_3_fu_1226_p2 and icmp_ln170_3_reg_1899);
    and_ln170_fu_581_p2 <= (xor_ln167_fu_576_p2 and icmp_ln170_reg_1760);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);

    ap_ST_fsm_state10_blk_assign_proc : process(m_axi_atomLocations_0_RVALID)
    begin
        if ((m_axi_atomLocations_0_RVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state11_blk_assign_proc : process(m_axi_atomLocations_0_RVALID)
    begin
        if ((m_axi_atomLocations_0_RVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;

    ap_ST_fsm_state27_blk_assign_proc : process(localImages_full_n)
    begin
        if ((localImages_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state27_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state27_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(m_axi_atomLocations_0_ARREADY)
    begin
        if ((m_axi_atomLocations_0_ARREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, localImages_full_n, ap_CS_fsm_state27)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state27) and (localImages_full_n = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(localImages_full_n, ap_CS_fsm_state27)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state27) and (localImages_full_n = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    atomLocations_blk_n_AR_assign_proc : process(m_axi_atomLocations_0_ARREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            atomLocations_blk_n_AR <= m_axi_atomLocations_0_ARREADY;
        else 
            atomLocations_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    atomLocations_blk_n_R_assign_proc : process(m_axi_atomLocations_0_RVALID, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            atomLocations_blk_n_R <= m_axi_atomLocations_0_RVALID;
        else 
            atomLocations_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    coord_x_fu_512_p1 <= data_13_reg_1737;
    coord_y_fu_515_p1 <= data_12_reg_1743;
    data_10_fu_1183_p2 <= std_logic_vector(unsigned(data_15_reg_1883) + unsigned(one_half_cast_i68_fu_1179_p1));
    data_11_fu_1527_p1 <= dc_10_reg_1919;
    data_13_fu_406_p1 <= lshr_ln8_fu_400_p2(32 - 1 downto 0);
    data_14_fu_980_p1 <= dc_6_reg_1840;
    data_15_fu_1027_p1 <= dc_9_reg_1846;
    data_2_fu_533_p2 <= std_logic_vector(unsigned(data_12_reg_1743) + unsigned(one_half_cast_i_fu_529_p1));
    data_4_fu_764_p2 <= std_logic_vector(unsigned(data_13_reg_1737) + unsigned(one_half_cast_i18_fu_760_p1));
    data_5_fu_844_p1 <= dc_4_fu_824_p9;
    data_7_fu_1089_p2 <= std_logic_vector(unsigned(data_14_reg_1852) + unsigned(one_half_cast_i43_fu_1085_p1));
    data_8_fu_1392_p1 <= dc_7_reg_1914;
    data_fu_613_p1 <= dc_1_fu_593_p9;
    dc_10_fu_1243_p2 <= t_16_fu_1168_p3;
    dc_10_fu_1243_p6 <= t_17_fu_1214_p3;
    dc_10_fu_1243_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    dc_10_fu_1243_p8 <= (icmp_ln167_3_reg_1888 & and_ln170_3_fu_1231_p2);
    dc_1_fu_593_p2 <= t_fu_518_p3;
    dc_1_fu_593_p4 <= data_12_reg_1743;
    dc_1_fu_593_p6 <= t_11_fu_564_p3;
    dc_1_fu_593_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    dc_1_fu_593_p8 <= (icmp_ln167_reg_1749 & and_ln170_fu_581_p2);
    dc_4_fu_824_p2 <= t_12_fu_749_p3;
    dc_4_fu_824_p4 <= data_13_reg_1737;
    dc_4_fu_824_p6 <= t_13_fu_795_p3;
    dc_4_fu_824_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    dc_4_fu_824_p8 <= (icmp_ln167_1_reg_1775 & and_ln170_1_fu_812_p2);
    dc_7_fu_1149_p2 <= t_14_fu_1074_p3;
    dc_7_fu_1149_p6 <= t_15_fu_1120_p3;
    dc_7_fu_1149_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    dc_7_fu_1149_p8 <= (icmp_ln167_2_reg_1857 & and_ln170_2_fu_1137_p2);

    grp_fu_309_p0_assign_proc : process(psfSupersample_read_reg_1722, result_13_reg_1818, ap_CS_fsm_state18, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_309_p0 <= psfSupersample_read_reg_1722;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_309_p0 <= result_13_reg_1818;
        else 
            grp_fu_309_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln167_1_fu_476_p2 <= "1" when (unsigned(xs_exp_5_fu_466_p4) < unsigned(ap_const_lv8_7E)) else "0";
    icmp_ln167_2_fu_991_p2 <= "1" when (unsigned(xs_exp_6_fu_983_p3) < unsigned(ap_const_lv8_7E)) else "0";
    icmp_ln167_3_fu_1038_p2 <= "1" when (unsigned(xs_exp_7_fu_1030_p3) < unsigned(ap_const_lv8_7E)) else "0";
    icmp_ln167_fu_430_p2 <= "1" when (unsigned(xs_exp_4_fu_420_p4) < unsigned(ap_const_lv8_7E)) else "0";
    icmp_ln170_1_fu_490_p2 <= "1" when (unsigned(xs_exp_5_fu_466_p4) > unsigned(ap_const_lv8_96)) else "0";
    icmp_ln170_2_fu_1005_p2 <= "1" when (unsigned(xs_exp_6_fu_983_p3) > unsigned(ap_const_lv8_96)) else "0";
    icmp_ln170_3_fu_1052_p2 <= "1" when (unsigned(xs_exp_7_fu_1030_p3) > unsigned(ap_const_lv8_96)) else "0";
    icmp_ln170_fu_444_p2 <= "1" when (unsigned(xs_exp_4_fu_420_p4) > unsigned(ap_const_lv8_96)) else "0";
    icmp_ln8_fu_344_p2 <= "0" when (trunc_ln8_fu_340_p1 = ap_const_lv3_0) else "1";
    index_1_fu_496_p4 <= lshr_ln8_fu_400_p2(27 downto 23);
    index_2_fu_1011_p4 <= data_14_fu_980_p1(27 downto 23);
    index_3_fu_1058_p4 <= data_15_fu_1027_p1(27 downto 23);
    index_fu_450_p4 <= lshr_ln8_fu_400_p2(59 downto 55);
    info_X_max_fu_1387_p2 <= std_logic_vector(unsigned(add_ln18_fu_1381_p2) + unsigned(projShape1_read_reg_1706));
    info_X_min_fu_1365_p2 <= std_logic_vector(unsigned(result_13_reg_1818) - unsigned(sext_ln16_fu_1361_p1));
    info_Y_max_fu_1376_p2 <= std_logic_vector(unsigned(add_ln17_fu_1370_p2) + unsigned(projShape0_read_reg_1714));
    info_Y_min_fu_1311_p2 <= std_logic_vector(unsigned(result_12_reg_1811) - unsigned(sext_ln15_fu_1307_p1));

    localImages_blk_n_assign_proc : process(localImages_full_n, ap_CS_fsm_state27)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state27)) then 
            localImages_blk_n <= localImages_full_n;
        else 
            localImages_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    localImages_din <= (((((((result_fu_1654_p3 & result_14_fu_1519_p3) & info_Y_max_fu_1376_p2) & info_X_max_fu_1387_p2) & info_Y_min_fu_1311_p2) & info_X_min_fu_1365_p2) & result_12_reg_1811) & result_13_reg_1818);

    localImages_write_assign_proc : process(localImages_full_n, ap_CS_fsm_state27)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state27) and (localImages_full_n = ap_const_logic_1))) then 
            localImages_write <= ap_const_logic_1;
        else 
            localImages_write <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln15_1_fu_1274_p4 <= sub_ln15_fu_1269_p2(31 downto 1);
    lshr_ln15_2_fu_1290_p4 <= projShape0_read_reg_1714(31 downto 1);
    lshr_ln16_1_fu_1328_p4 <= sub_ln16_fu_1323_p2(31 downto 1);
    lshr_ln16_2_fu_1344_p4 <= projShape1_read_reg_1706(31 downto 1);
    lshr_ln18_1_fu_926_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_1_fu_878_p1),to_integer(unsigned('0' & zext_ln18_1_fu_922_p1(31-1 downto 0)))));
    lshr_ln18_2_fu_1473_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_2_fu_1425_p1),to_integer(unsigned('0' & zext_ln18_2_fu_1469_p1(31-1 downto 0)))));
    lshr_ln18_3_fu_1608_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_3_fu_1560_p1),to_integer(unsigned('0' & zext_ln18_3_fu_1604_p1(31-1 downto 0)))));
    lshr_ln18_fu_695_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_647_p1),to_integer(unsigned('0' & zext_ln18_fu_691_p1(31-1 downto 0)))));
    lshr_ln8_fu_400_p2 <= std_logic_vector(shift_right(unsigned(tmp_fu_382_p3),to_integer(unsigned('0' & zext_ln8_1_fu_396_p1(31-1 downto 0)))));
    m_axi_atomLocations_0_ARADDR <= sext_ln8_fu_368_p1;
    m_axi_atomLocations_0_ARBURST <= ap_const_lv2_0;
    m_axi_atomLocations_0_ARCACHE <= ap_const_lv4_0;
    m_axi_atomLocations_0_ARID <= ap_const_lv1_0;
    m_axi_atomLocations_0_ARLEN <= select_ln8_reg_1690(32 - 1 downto 0);
    m_axi_atomLocations_0_ARLOCK <= ap_const_lv2_0;
    m_axi_atomLocations_0_ARPROT <= ap_const_lv3_0;
    m_axi_atomLocations_0_ARQOS <= ap_const_lv4_0;
    m_axi_atomLocations_0_ARREGION <= ap_const_lv4_0;
    m_axi_atomLocations_0_ARSIZE <= ap_const_lv3_0;
    m_axi_atomLocations_0_ARUSER <= ap_const_lv1_0;

    m_axi_atomLocations_0_ARVALID_assign_proc : process(m_axi_atomLocations_0_ARREADY, ap_CS_fsm_state2)
    begin
        if (((m_axi_atomLocations_0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_atomLocations_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_atomLocations_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_atomLocations_0_AWADDR <= ap_const_lv64_0;
    m_axi_atomLocations_0_AWBURST <= ap_const_lv2_0;
    m_axi_atomLocations_0_AWCACHE <= ap_const_lv4_0;
    m_axi_atomLocations_0_AWID <= ap_const_lv1_0;
    m_axi_atomLocations_0_AWLEN <= ap_const_lv32_0;
    m_axi_atomLocations_0_AWLOCK <= ap_const_lv2_0;
    m_axi_atomLocations_0_AWPROT <= ap_const_lv3_0;
    m_axi_atomLocations_0_AWQOS <= ap_const_lv4_0;
    m_axi_atomLocations_0_AWREGION <= ap_const_lv4_0;
    m_axi_atomLocations_0_AWSIZE <= ap_const_lv3_0;
    m_axi_atomLocations_0_AWUSER <= ap_const_lv1_0;
    m_axi_atomLocations_0_AWVALID <= ap_const_logic_0;
    m_axi_atomLocations_0_BREADY <= ap_const_logic_0;

    m_axi_atomLocations_0_RREADY_assign_proc : process(m_axi_atomLocations_0_RVALID, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if ((((m_axi_atomLocations_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((m_axi_atomLocations_0_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            m_axi_atomLocations_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_atomLocations_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_atomLocations_0_WDATA <= ap_const_lv64_0;
    m_axi_atomLocations_0_WID <= ap_const_lv1_0;
    m_axi_atomLocations_0_WLAST <= ap_const_logic_0;
    m_axi_atomLocations_0_WSTRB <= ap_const_lv8_0;
    m_axi_atomLocations_0_WUSER <= ap_const_lv1_0;
    m_axi_atomLocations_0_WVALID <= ap_const_logic_0;
    mantissa_1_fu_868_p4 <= ((ap_const_lv1_1 & trunc_ln342_1_fu_864_p1) & ap_const_lv1_0);
    mantissa_2_fu_1415_p4 <= ((ap_const_lv1_1 & trunc_ln342_2_fu_1411_p1) & ap_const_lv1_0);
    mantissa_3_fu_1550_p4 <= ((ap_const_lv1_1 & trunc_ln342_3_fu_1546_p1) & ap_const_lv1_0);
    mantissa_fu_637_p4 <= ((ap_const_lv1_1 & trunc_ln342_fu_633_p1) & ap_const_lv1_0);

    mask_table_address0_local_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state25, zext_ln179_1_fu_506_p1, zext_ln179_3_fu_1068_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            mask_table_address0_local <= zext_ln179_3_fu_1068_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            mask_table_address0_local <= zext_ln179_1_fu_506_p1(5 - 1 downto 0);
        else 
            mask_table_address0_local <= "XXXXX";
        end if; 
    end process;


    mask_table_address1_local_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state25, zext_ln179_fu_460_p1, zext_ln179_2_fu_1021_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            mask_table_address1_local <= zext_ln179_2_fu_1021_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            mask_table_address1_local <= zext_ln179_fu_460_p1(5 - 1 downto 0);
        else 
            mask_table_address1_local <= "XXXXX";
        end if; 
    end process;


    mask_table_ce0_local_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            mask_table_ce0_local <= ap_const_logic_1;
        else 
            mask_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    mask_table_ce1_local_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            mask_table_ce1_local <= ap_const_logic_1;
        else 
            mask_table_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    one_half_cast_i18_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(one_half_table_q0),32));
    one_half_cast_i43_fu_1085_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(one_half_table_q1),32));
    one_half_cast_i68_fu_1179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(one_half_table_q0),32));
    one_half_cast_i_fu_529_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(one_half_table_q1),32));

    one_half_table_address0_local_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state25, zext_ln179_1_fu_506_p1, zext_ln179_3_fu_1068_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            one_half_table_address0_local <= zext_ln179_3_fu_1068_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            one_half_table_address0_local <= zext_ln179_1_fu_506_p1(5 - 1 downto 0);
        else 
            one_half_table_address0_local <= "XXXXX";
        end if; 
    end process;


    one_half_table_address1_local_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state25, zext_ln179_fu_460_p1, zext_ln179_2_fu_1021_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            one_half_table_address1_local <= zext_ln179_2_fu_1021_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            one_half_table_address1_local <= zext_ln179_fu_460_p1(5 - 1 downto 0);
        else 
            one_half_table_address1_local <= "XXXXX";
        end if; 
    end process;


    one_half_table_ce0_local_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            one_half_table_ce0_local <= ap_const_logic_1;
        else 
            one_half_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    one_half_table_ce1_local_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            one_half_table_ce1_local <= ap_const_logic_1;
        else 
            one_half_table_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    result_10_fu_1648_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_3_fu_1640_p3));
    result_12_fu_741_p3 <= 
        result_2_fu_735_p2 when (xs_sign_fu_617_p3(0) = '1') else 
        val_fu_727_p3;
    result_13_fu_972_p3 <= 
        result_5_fu_966_p2 when (xs_sign_1_fu_848_p3(0) = '1') else 
        val_1_fu_958_p3;
    result_14_fu_1519_p3 <= 
        result_9_fu_1513_p2 when (xs_sign_2_fu_1395_p3(0) = '1') else 
        val_2_fu_1505_p3;
    result_2_fu_735_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_fu_727_p3));
    result_5_fu_966_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_1_fu_958_p3));
    result_9_fu_1513_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_2_fu_1505_p3));
    result_fu_1654_p3 <= 
        result_10_fu_1648_p2 when (xs_sign_3_fu_1530_p3(0) = '1') else 
        val_3_fu_1640_p3;
    select_ln15_fu_1299_p3 <= 
        sub_ln15_1_fu_1284_p2 when (tmp_15_fu_1262_p3(0) = '1') else 
        lshr_ln15_2_fu_1290_p4;
    select_ln16_fu_1353_p3 <= 
        sub_ln16_1_fu_1338_p2 when (tmp_16_fu_1316_p3(0) = '1') else 
        lshr_ln16_2_fu_1344_p4;
    select_ln18_2_fu_910_p3 <= 
        sext_ln18_2_fu_906_p1 when (tmp_14_fu_892_p3(0) = '1') else 
        add_ln317_1_fu_886_p2;
    select_ln18_4_fu_1457_p3 <= 
        sext_ln18_4_fu_1453_p1 when (tmp_19_fu_1439_p3(0) = '1') else 
        add_ln317_2_fu_1433_p2;
    select_ln18_6_fu_1592_p3 <= 
        sext_ln18_6_fu_1588_p1 when (tmp_22_fu_1574_p3(0) = '1') else 
        add_ln317_3_fu_1568_p2;
    select_ln18_fu_679_p3 <= 
        sext_ln18_fu_675_p1 when (tmp_11_fu_661_p3(0) = '1') else 
        add_ln317_fu_655_p2;
    select_ln8_fu_350_p3 <= 
        ap_const_lv64_2 when (icmp_ln8_fu_344_p2(0) = '1') else 
        ap_const_lv64_1;
        sext_ln15_fu_1307_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln15_fu_1299_p3),32));

        sext_ln16_fu_1361_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln16_fu_1353_p3),32));

        sext_ln18_1_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_fu_679_p3),32));

        sext_ln18_2_fu_906_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_1_fu_900_p2),9));

        sext_ln18_3_fu_918_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_2_fu_910_p3),32));

        sext_ln18_4_fu_1453_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_2_fu_1447_p2),9));

        sext_ln18_5_fu_1465_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_4_fu_1457_p3),32));

        sext_ln18_6_fu_1588_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_3_fu_1582_p2),9));

        sext_ln18_7_fu_1600_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_6_fu_1592_p3),32));

        sext_ln18_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_fu_669_p2),9));

        sext_ln8_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln8_1_reg_1695),64));

    shl_ln18_1_fu_932_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_1_fu_878_p1),to_integer(unsigned('0' & zext_ln18_1_fu_922_p1(31-1 downto 0)))));
    shl_ln18_2_fu_1479_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_2_fu_1425_p1),to_integer(unsigned('0' & zext_ln18_2_fu_1469_p1(31-1 downto 0)))));
    shl_ln18_3_fu_1614_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_3_fu_1560_p1),to_integer(unsigned('0' & zext_ln18_3_fu_1604_p1(31-1 downto 0)))));
    shl_ln18_fu_701_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_647_p1),to_integer(unsigned('0' & zext_ln18_fu_691_p1(31-1 downto 0)))));
    shl_ln8_1_fu_389_p3 <= (trunc_ln8_reg_1681 & ap_const_lv3_0);
    shl_ln8_fu_322_p3 <= (curr_idx & ap_const_lv3_0);
    sub_ln15_1_fu_1284_p2 <= std_logic_vector(unsigned(ap_const_lv31_0) - unsigned(lshr_ln15_1_fu_1274_p4));
    sub_ln15_fu_1269_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(projShape0_read_reg_1714));
    sub_ln16_1_fu_1338_p2 <= std_logic_vector(unsigned(ap_const_lv31_0) - unsigned(lshr_ln16_1_fu_1328_p4));
    sub_ln16_fu_1323_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(projShape1_read_reg_1706));
    sub_ln18_1_fu_900_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_1_fu_856_p3));
    sub_ln18_2_fu_1447_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_2_fu_1403_p3));
    sub_ln18_3_fu_1582_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_3_fu_1538_p3));
    sub_ln18_fu_669_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_fu_625_p3));
    t_11_fu_564_p3 <= (tmp_8_i_fu_554_p4 & xs_sig_fu_548_p2);
    t_12_fu_749_p3 <= (tmp_12_reg_1781 & ap_const_lv31_0);
    t_13_fu_795_p3 <= (tmp_8_i1_fu_785_p4 & xs_sig_1_fu_779_p2);
    t_14_fu_1074_p3 <= (tmp_17_reg_1863 & ap_const_lv31_0);
    t_15_fu_1120_p3 <= (tmp_8_i2_fu_1110_p4 & xs_sig_2_fu_1104_p2);
    t_16_fu_1168_p3 <= (tmp_20_reg_1894 & ap_const_lv31_0);
    t_17_fu_1214_p3 <= (tmp_8_i3_fu_1204_p4 & xs_sig_3_fu_1198_p2);
    t_fu_518_p3 <= (tmp_1_reg_1755 & ap_const_lv31_0);
    tmp_11_fu_661_p3 <= add_ln317_fu_655_p2(8 downto 8);
    tmp_14_fu_892_p3 <= add_ln317_1_fu_886_p2(8 downto 8);
    tmp_15_fu_1262_p3 <= projShape0_read_reg_1714(31 downto 31);
    tmp_16_fu_1316_p3 <= projShape1_read_reg_1706(31 downto 31);
    tmp_19_fu_1439_p3 <= add_ln317_2_fu_1433_p2(8 downto 8);
    tmp_22_fu_1574_p3 <= add_ln317_3_fu_1568_p2(8 downto 8);
    tmp_2_fu_707_p4 <= lshr_ln18_fu_695_p2(55 downto 24);
    tmp_3_fu_717_p4 <= shl_ln18_fu_701_p2(55 downto 24);
    tmp_4_fu_938_p4 <= lshr_ln18_1_fu_926_p2(55 downto 24);
    tmp_5_fu_948_p4 <= shl_ln18_1_fu_932_p2(55 downto 24);
    tmp_6_fu_1485_p4 <= lshr_ln18_2_fu_1473_p2(55 downto 24);
    tmp_7_fu_1495_p4 <= shl_ln18_2_fu_1479_p2(55 downto 24);
    tmp_8_fu_1620_p4 <= lshr_ln18_3_fu_1608_p2(55 downto 24);
    tmp_8_i1_fu_785_p4 <= data_4_fu_764_p2(31 downto 23);
    tmp_8_i2_fu_1110_p4 <= data_7_fu_1089_p2(31 downto 23);
    tmp_8_i3_fu_1204_p4 <= data_10_fu_1183_p2(31 downto 23);
    tmp_8_i_fu_554_p4 <= data_2_fu_533_p2(31 downto 23);
    tmp_9_fu_1630_p4 <= shl_ln18_3_fu_1614_p2(55 downto 24);
    tmp_fu_382_p3 <= (phi_ln8_reg_282 & atomLocations_addr_read_reg_1727);
    trunc_ln301_1_fu_769_p1 <= data_4_fu_764_p2(23 - 1 downto 0);
    trunc_ln301_2_fu_1094_p1 <= data_7_fu_1089_p2(23 - 1 downto 0);
    trunc_ln301_3_fu_1188_p1 <= data_10_fu_1183_p2(23 - 1 downto 0);
    trunc_ln301_fu_538_p1 <= data_2_fu_533_p2(23 - 1 downto 0);
    trunc_ln342_1_fu_864_p1 <= data_5_fu_844_p1(23 - 1 downto 0);
    trunc_ln342_2_fu_1411_p1 <= data_8_fu_1392_p1(23 - 1 downto 0);
    trunc_ln342_3_fu_1546_p1 <= data_11_fu_1527_p1(23 - 1 downto 0);
    trunc_ln342_fu_633_p1 <= data_fu_613_p1(23 - 1 downto 0);
    trunc_ln8_2_fu_378_p1 <= m_axi_atomLocations_0_RDATA(56 - 1 downto 0);
    trunc_ln8_fu_340_p1 <= add_ln8_fu_334_p2(3 - 1 downto 0);
    val_1_fu_958_p3 <= 
        tmp_4_fu_938_p4 when (tmp_14_fu_892_p3(0) = '1') else 
        tmp_5_fu_948_p4;
    val_2_fu_1505_p3 <= 
        tmp_6_fu_1485_p4 when (tmp_19_fu_1439_p3(0) = '1') else 
        tmp_7_fu_1495_p4;
    val_3_fu_1640_p3 <= 
        tmp_8_fu_1620_p4 when (tmp_22_fu_1574_p3(0) = '1') else 
        tmp_9_fu_1630_p4;
    val_fu_727_p3 <= 
        tmp_2_fu_707_p4 when (tmp_11_fu_661_p3(0) = '1') else 
        tmp_3_fu_717_p4;
    xor_ln167_1_fu_807_p2 <= (icmp_ln167_1_reg_1775 xor ap_const_lv1_1);
    xor_ln167_2_fu_1132_p2 <= (icmp_ln167_2_reg_1857 xor ap_const_lv1_1);
    xor_ln167_3_fu_1226_p2 <= (icmp_ln167_3_reg_1888 xor ap_const_lv1_1);
    xor_ln167_fu_576_p2 <= (icmp_ln167_reg_1749 xor ap_const_lv1_1);
    xor_ln184_1_fu_773_p2 <= (mask_table_q0 xor ap_const_lv23_7FFFFF);
    xor_ln184_2_fu_1098_p2 <= (mask_table_q1 xor ap_const_lv23_7FFFFF);
    xor_ln184_3_fu_1192_p2 <= (mask_table_q0 xor ap_const_lv23_7FFFFF);
    xor_ln184_fu_542_p2 <= (mask_table_q1 xor ap_const_lv23_7FFFFF);
    xs_exp_1_fu_856_p3 <= data_5_fu_844_p1(30 downto 23);
    xs_exp_2_fu_1403_p3 <= data_8_fu_1392_p1(30 downto 23);
    xs_exp_3_fu_1538_p3 <= data_11_fu_1527_p1(30 downto 23);
    xs_exp_4_fu_420_p4 <= lshr_ln8_fu_400_p2(62 downto 55);
    xs_exp_5_fu_466_p4 <= lshr_ln8_fu_400_p2(30 downto 23);
    xs_exp_6_fu_983_p3 <= data_14_fu_980_p1(30 downto 23);
    xs_exp_7_fu_1030_p3 <= data_15_fu_1027_p1(30 downto 23);
    xs_exp_fu_625_p3 <= data_fu_613_p1(30 downto 23);
    xs_sig_1_fu_779_p2 <= (xor_ln184_1_fu_773_p2 and trunc_ln301_1_fu_769_p1);
    xs_sig_2_fu_1104_p2 <= (xor_ln184_2_fu_1098_p2 and trunc_ln301_2_fu_1094_p1);
    xs_sig_3_fu_1198_p2 <= (xor_ln184_3_fu_1192_p2 and trunc_ln301_3_fu_1188_p1);
    xs_sig_fu_548_p2 <= (xor_ln184_fu_542_p2 and trunc_ln301_fu_538_p1);
    xs_sign_1_fu_848_p3 <= data_5_fu_844_p1(31 downto 31);
    xs_sign_2_fu_1395_p3 <= data_8_fu_1392_p1(31 downto 31);
    xs_sign_3_fu_1530_p3 <= data_11_fu_1527_p1(31 downto 31);
    xs_sign_fu_617_p3 <= data_fu_613_p1(31 downto 31);
    zext_ln15_1_fu_878_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_1_fu_868_p4),79));
    zext_ln15_2_fu_1425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_2_fu_1415_p4),79));
    zext_ln15_3_fu_1560_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_3_fu_1550_p4),79));
    zext_ln15_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_637_p4),79));
    zext_ln179_1_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_1_fu_496_p4),64));
    zext_ln179_2_fu_1021_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_2_fu_1011_p4),64));
    zext_ln179_3_fu_1068_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_3_fu_1058_p4),64));
    zext_ln179_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_fu_450_p4),64));
    zext_ln18_1_fu_922_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_3_fu_918_p1),79));
    zext_ln18_2_fu_1469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_5_fu_1465_p1),79));
    zext_ln18_3_fu_1604_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_7_fu_1600_p1),79));
    zext_ln18_fu_691_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_1_fu_687_p1),79));
    zext_ln317_1_fu_882_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_1_fu_856_p3),9));
    zext_ln317_2_fu_1429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_2_fu_1403_p3),9));
    zext_ln317_3_fu_1564_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_3_fu_1538_p3),9));
    zext_ln317_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_625_p3),9));
    zext_ln8_1_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln8_1_fu_389_p3),120));
    zext_ln8_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln8_fu_322_p3),64));
end behav;
