-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reconstruct_post_process is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    projSumUsed : IN STD_LOGIC_VECTOR (31 downto 0);
    sum : IN STD_LOGIC_VECTOR (31 downto 0);
    curr_imageProjs : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_emissions_0_AWVALID : OUT STD_LOGIC;
    m_axi_emissions_0_AWREADY : IN STD_LOGIC;
    m_axi_emissions_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_emissions_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_emissions_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_emissions_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_emissions_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_emissions_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_emissions_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_emissions_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_emissions_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_emissions_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_WVALID : OUT STD_LOGIC;
    m_axi_emissions_0_WREADY : IN STD_LOGIC;
    m_axi_emissions_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_emissions_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_emissions_0_WLAST : OUT STD_LOGIC;
    m_axi_emissions_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_ARVALID : OUT STD_LOGIC;
    m_axi_emissions_0_ARREADY : IN STD_LOGIC;
    m_axi_emissions_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_emissions_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_emissions_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_emissions_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_emissions_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_emissions_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_emissions_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_emissions_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_emissions_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_emissions_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_RVALID : IN STD_LOGIC;
    m_axi_emissions_0_RREADY : OUT STD_LOGIC;
    m_axi_emissions_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_emissions_0_RLAST : IN STD_LOGIC;
    m_axi_emissions_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_emissions_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_emissions_0_BVALID : IN STD_LOGIC;
    m_axi_emissions_0_BREADY : OUT STD_LOGIC;
    m_axi_emissions_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_emissions_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_emissions_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    dout : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of reconstruct_post_process is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (18 downto 0) := "0000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (18 downto 0) := "0000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (18 downto 0) := "0000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (18 downto 0) := "0000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (18 downto 0) := "0000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (18 downto 0) := "0001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (18 downto 0) := "0010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (18 downto 0) := "0100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (18 downto 0) := "1000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal emissions_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal emissions_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal emissions_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal curr_imageProjs_read_reg_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal projSumUsed_read_reg_125 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_read_reg_130 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_92_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal div_i_reg_135 : STD_LOGIC_VECTOR (31 downto 0);
    signal emissions_addr_reg_140 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fu_88_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_reg_146 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln116_fu_106_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln_fu_96_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_88_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component reconstruct_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component reconstruct_fdiv_32ns_32ns_32_9_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    fmul_32ns_32ns_32_3_max_dsp_1_U2215 : component reconstruct_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => div_i_reg_135,
        din1 => sum_read_reg_130,
        ce => grp_fu_88_ce,
        dout => grp_fu_88_p2);

    fdiv_32ns_32ns_32_9_no_dsp_1_U2216 : component reconstruct_fdiv_32ns_32ns_32_9_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => curr_imageProjs_read_reg_120,
        din1 => projSumUsed_read_reg_125,
        ce => ap_const_logic_1,
        dout => grp_fu_92_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((m_axi_emissions_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                curr_imageProjs_read_reg_120 <= curr_imageProjs;
                projSumUsed_read_reg_125 <= projSumUsed;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                div_i_reg_135 <= grp_fu_92_p2;
                sum_read_reg_130 <= sum;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                emissions_addr_reg_140 <= sext_ln116_fu_106_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_emissions_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                mul_i_reg_146 <= grp_fu_88_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, m_axi_emissions_0_AWREADY, m_axi_emissions_0_WREADY, m_axi_emissions_0_BVALID, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state19, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((m_axi_emissions_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if (((m_axi_emissions_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                if (((m_axi_emissions_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(m_axi_emissions_0_AWREADY)
    begin
        if ((m_axi_emissions_0_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state14_blk_assign_proc : process(m_axi_emissions_0_WREADY)
    begin
        if ((m_axi_emissions_0_WREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;

    ap_ST_fsm_state19_blk_assign_proc : process(m_axi_emissions_0_BVALID)
    begin
        if ((m_axi_emissions_0_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state19_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state19_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, m_axi_emissions_0_BVALID, ap_CS_fsm_state19)
    begin
        if (((m_axi_emissions_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axi_emissions_0_BVALID, ap_CS_fsm_state19)
    begin
        if (((m_axi_emissions_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    emissions_blk_n_AW_assign_proc : process(m_axi_emissions_0_AWREADY, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            emissions_blk_n_AW <= m_axi_emissions_0_AWREADY;
        else 
            emissions_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    emissions_blk_n_B_assign_proc : process(m_axi_emissions_0_BVALID, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            emissions_blk_n_B <= m_axi_emissions_0_BVALID;
        else 
            emissions_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    emissions_blk_n_W_assign_proc : process(m_axi_emissions_0_WREADY, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            emissions_blk_n_W <= m_axi_emissions_0_WREADY;
        else 
            emissions_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_88_ce_assign_proc : process(m_axi_emissions_0_AWREADY, ap_CS_fsm_state13, ap_CS_fsm_state12, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((m_axi_emissions_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13)))) then 
            grp_fu_88_ce <= ap_const_logic_1;
        else 
            grp_fu_88_ce <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_emissions_0_ARADDR <= ap_const_lv64_0;
    m_axi_emissions_0_ARBURST <= ap_const_lv2_0;
    m_axi_emissions_0_ARCACHE <= ap_const_lv4_0;
    m_axi_emissions_0_ARID <= ap_const_lv1_0;
    m_axi_emissions_0_ARLEN <= ap_const_lv32_0;
    m_axi_emissions_0_ARLOCK <= ap_const_lv2_0;
    m_axi_emissions_0_ARPROT <= ap_const_lv3_0;
    m_axi_emissions_0_ARQOS <= ap_const_lv4_0;
    m_axi_emissions_0_ARREGION <= ap_const_lv4_0;
    m_axi_emissions_0_ARSIZE <= ap_const_lv3_0;
    m_axi_emissions_0_ARUSER <= ap_const_lv1_0;
    m_axi_emissions_0_ARVALID <= ap_const_logic_0;
    m_axi_emissions_0_AWADDR <= emissions_addr_reg_140;
    m_axi_emissions_0_AWBURST <= ap_const_lv2_0;
    m_axi_emissions_0_AWCACHE <= ap_const_lv4_0;
    m_axi_emissions_0_AWID <= ap_const_lv1_0;
    m_axi_emissions_0_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_emissions_0_AWLOCK <= ap_const_lv2_0;
    m_axi_emissions_0_AWPROT <= ap_const_lv3_0;
    m_axi_emissions_0_AWQOS <= ap_const_lv4_0;
    m_axi_emissions_0_AWREGION <= ap_const_lv4_0;
    m_axi_emissions_0_AWSIZE <= ap_const_lv3_0;
    m_axi_emissions_0_AWUSER <= ap_const_lv1_0;

    m_axi_emissions_0_AWVALID_assign_proc : process(m_axi_emissions_0_AWREADY, ap_CS_fsm_state13)
    begin
        if (((m_axi_emissions_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            m_axi_emissions_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_emissions_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_emissions_0_BREADY_assign_proc : process(m_axi_emissions_0_BVALID, ap_CS_fsm_state19)
    begin
        if (((m_axi_emissions_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            m_axi_emissions_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_emissions_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_emissions_0_RREADY <= ap_const_logic_0;
    m_axi_emissions_0_WDATA <= mul_i_reg_146;
    m_axi_emissions_0_WID <= ap_const_lv1_0;
    m_axi_emissions_0_WLAST <= ap_const_logic_0;
    m_axi_emissions_0_WSTRB <= ap_const_lv4_F;
    m_axi_emissions_0_WUSER <= ap_const_lv1_0;

    m_axi_emissions_0_WVALID_assign_proc : process(m_axi_emissions_0_WREADY, ap_CS_fsm_state14)
    begin
        if (((m_axi_emissions_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            m_axi_emissions_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_emissions_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln116_fu_106_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_96_p4),64));

    trunc_ln_fu_96_p4 <= dout(63 downto 2);
end behav;
