// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module reconstruct_getLocalImages_single (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        curr_idx,
        psfSupersample,
        projShape0,
        projShape1,
        m_axi_atomLocations_0_AWVALID,
        m_axi_atomLocations_0_AWREADY,
        m_axi_atomLocations_0_AWADDR,
        m_axi_atomLocations_0_AWID,
        m_axi_atomLocations_0_AWLEN,
        m_axi_atomLocations_0_AWSIZE,
        m_axi_atomLocations_0_AWBURST,
        m_axi_atomLocations_0_AWLOCK,
        m_axi_atomLocations_0_AWCACHE,
        m_axi_atomLocations_0_AWPROT,
        m_axi_atomLocations_0_AWQOS,
        m_axi_atomLocations_0_AWREGION,
        m_axi_atomLocations_0_AWUSER,
        m_axi_atomLocations_0_WVALID,
        m_axi_atomLocations_0_WREADY,
        m_axi_atomLocations_0_WDATA,
        m_axi_atomLocations_0_WSTRB,
        m_axi_atomLocations_0_WLAST,
        m_axi_atomLocations_0_WID,
        m_axi_atomLocations_0_WUSER,
        m_axi_atomLocations_0_ARVALID,
        m_axi_atomLocations_0_ARREADY,
        m_axi_atomLocations_0_ARADDR,
        m_axi_atomLocations_0_ARID,
        m_axi_atomLocations_0_ARLEN,
        m_axi_atomLocations_0_ARSIZE,
        m_axi_atomLocations_0_ARBURST,
        m_axi_atomLocations_0_ARLOCK,
        m_axi_atomLocations_0_ARCACHE,
        m_axi_atomLocations_0_ARPROT,
        m_axi_atomLocations_0_ARQOS,
        m_axi_atomLocations_0_ARREGION,
        m_axi_atomLocations_0_ARUSER,
        m_axi_atomLocations_0_RVALID,
        m_axi_atomLocations_0_RREADY,
        m_axi_atomLocations_0_RDATA,
        m_axi_atomLocations_0_RLAST,
        m_axi_atomLocations_0_RID,
        m_axi_atomLocations_0_RFIFONUM,
        m_axi_atomLocations_0_RUSER,
        m_axi_atomLocations_0_RRESP,
        m_axi_atomLocations_0_BVALID,
        m_axi_atomLocations_0_BREADY,
        m_axi_atomLocations_0_BRESP,
        m_axi_atomLocations_0_BID,
        m_axi_atomLocations_0_BUSER,
        atomLocations1,
        localImages_din,
        localImages_full_n,
        localImages_write,
        localImages_num_data_valid,
        localImages_fifo_cap
);

parameter    ap_ST_fsm_state1 = 27'd1;
parameter    ap_ST_fsm_state2 = 27'd2;
parameter    ap_ST_fsm_state3 = 27'd4;
parameter    ap_ST_fsm_state4 = 27'd8;
parameter    ap_ST_fsm_state5 = 27'd16;
parameter    ap_ST_fsm_state6 = 27'd32;
parameter    ap_ST_fsm_state7 = 27'd64;
parameter    ap_ST_fsm_state8 = 27'd128;
parameter    ap_ST_fsm_state9 = 27'd256;
parameter    ap_ST_fsm_state10 = 27'd512;
parameter    ap_ST_fsm_state11 = 27'd1024;
parameter    ap_ST_fsm_state12 = 27'd2048;
parameter    ap_ST_fsm_state13 = 27'd4096;
parameter    ap_ST_fsm_state14 = 27'd8192;
parameter    ap_ST_fsm_state15 = 27'd16384;
parameter    ap_ST_fsm_state16 = 27'd32768;
parameter    ap_ST_fsm_state17 = 27'd65536;
parameter    ap_ST_fsm_state18 = 27'd131072;
parameter    ap_ST_fsm_state19 = 27'd262144;
parameter    ap_ST_fsm_state20 = 27'd524288;
parameter    ap_ST_fsm_state21 = 27'd1048576;
parameter    ap_ST_fsm_state22 = 27'd2097152;
parameter    ap_ST_fsm_state23 = 27'd4194304;
parameter    ap_ST_fsm_state24 = 27'd8388608;
parameter    ap_ST_fsm_state25 = 27'd16777216;
parameter    ap_ST_fsm_state26 = 27'd33554432;
parameter    ap_ST_fsm_state27 = 27'd67108864;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] curr_idx;
input  [31:0] psfSupersample;
input  [31:0] projShape0;
input  [31:0] projShape1;
output   m_axi_atomLocations_0_AWVALID;
input   m_axi_atomLocations_0_AWREADY;
output  [63:0] m_axi_atomLocations_0_AWADDR;
output  [0:0] m_axi_atomLocations_0_AWID;
output  [31:0] m_axi_atomLocations_0_AWLEN;
output  [2:0] m_axi_atomLocations_0_AWSIZE;
output  [1:0] m_axi_atomLocations_0_AWBURST;
output  [1:0] m_axi_atomLocations_0_AWLOCK;
output  [3:0] m_axi_atomLocations_0_AWCACHE;
output  [2:0] m_axi_atomLocations_0_AWPROT;
output  [3:0] m_axi_atomLocations_0_AWQOS;
output  [3:0] m_axi_atomLocations_0_AWREGION;
output  [0:0] m_axi_atomLocations_0_AWUSER;
output   m_axi_atomLocations_0_WVALID;
input   m_axi_atomLocations_0_WREADY;
output  [63:0] m_axi_atomLocations_0_WDATA;
output  [7:0] m_axi_atomLocations_0_WSTRB;
output   m_axi_atomLocations_0_WLAST;
output  [0:0] m_axi_atomLocations_0_WID;
output  [0:0] m_axi_atomLocations_0_WUSER;
output   m_axi_atomLocations_0_ARVALID;
input   m_axi_atomLocations_0_ARREADY;
output  [63:0] m_axi_atomLocations_0_ARADDR;
output  [0:0] m_axi_atomLocations_0_ARID;
output  [31:0] m_axi_atomLocations_0_ARLEN;
output  [2:0] m_axi_atomLocations_0_ARSIZE;
output  [1:0] m_axi_atomLocations_0_ARBURST;
output  [1:0] m_axi_atomLocations_0_ARLOCK;
output  [3:0] m_axi_atomLocations_0_ARCACHE;
output  [2:0] m_axi_atomLocations_0_ARPROT;
output  [3:0] m_axi_atomLocations_0_ARQOS;
output  [3:0] m_axi_atomLocations_0_ARREGION;
output  [0:0] m_axi_atomLocations_0_ARUSER;
input   m_axi_atomLocations_0_RVALID;
output   m_axi_atomLocations_0_RREADY;
input  [63:0] m_axi_atomLocations_0_RDATA;
input   m_axi_atomLocations_0_RLAST;
input  [0:0] m_axi_atomLocations_0_RID;
input  [8:0] m_axi_atomLocations_0_RFIFONUM;
input  [0:0] m_axi_atomLocations_0_RUSER;
input  [1:0] m_axi_atomLocations_0_RRESP;
input   m_axi_atomLocations_0_BVALID;
output   m_axi_atomLocations_0_BREADY;
input  [1:0] m_axi_atomLocations_0_BRESP;
input  [0:0] m_axi_atomLocations_0_BID;
input  [0:0] m_axi_atomLocations_0_BUSER;
input  [63:0] atomLocations1;
output  [255:0] localImages_din;
input   localImages_full_n;
output   localImages_write;
input  [2:0] localImages_num_data_valid;
input  [2:0] localImages_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_atomLocations_0_ARVALID;
reg m_axi_atomLocations_0_RREADY;
reg localImages_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [26:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [22:0] mask_table_q0;
wire   [22:0] mask_table_q1;
wire   [23:0] one_half_table_q0;
wire   [23:0] one_half_table_q1;
reg    atomLocations_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    atomLocations_blk_n_R;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    localImages_blk_n;
wire    ap_CS_fsm_state27;
wire   [31:0] grp_fu_309_p1;
reg   [31:0] reg_315;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state21;
wire   [2:0] trunc_ln8_fu_340_p1;
reg   [2:0] trunc_ln8_reg_1681;
reg    ap_block_state1;
wire   [0:0] icmp_ln8_fu_344_p2;
reg   [0:0] icmp_ln8_reg_1686;
wire   [63:0] select_ln8_fu_350_p3;
reg   [63:0] select_ln8_reg_1690;
reg   [60:0] trunc_ln8_1_reg_1695;
reg   [31:0] projShape1_read_reg_1706;
reg   [31:0] projShape0_read_reg_1714;
reg   [31:0] psfSupersample_read_reg_1722;
reg   [63:0] atomLocations_addr_read_reg_1727;
wire   [55:0] trunc_ln8_2_fu_378_p1;
wire   [31:0] data_13_fu_406_p1;
reg   [31:0] data_13_reg_1737;
wire    ap_CS_fsm_state12;
reg   [31:0] data_12_reg_1743;
wire   [0:0] icmp_ln167_fu_430_p2;
reg   [0:0] icmp_ln167_reg_1749;
reg   [0:0] tmp_1_reg_1755;
wire   [0:0] icmp_ln170_fu_444_p2;
reg   [0:0] icmp_ln170_reg_1760;
wire   [0:0] icmp_ln167_1_fu_476_p2;
reg   [0:0] icmp_ln167_1_reg_1775;
reg   [0:0] tmp_12_reg_1781;
wire   [0:0] icmp_ln170_1_fu_490_p2;
reg   [0:0] icmp_ln170_1_reg_1786;
wire   [31:0] coord_x_fu_512_p1;
reg   [31:0] coord_x_reg_1801;
wire    ap_CS_fsm_state13;
wire   [31:0] coord_y_fu_515_p1;
reg   [31:0] coord_y_reg_1806;
wire   [31:0] result_12_fu_741_p3;
reg   [31:0] result_12_reg_1811;
wire   [31:0] result_13_fu_972_p3;
reg   [31:0] result_13_reg_1818;
wire   [31:0] grp_fu_312_p1;
reg   [31:0] conv2_reg_1825;
wire   [31:0] grp_fu_293_p2;
reg   [31:0] sub_reg_1830;
wire   [31:0] grp_fu_297_p2;
reg   [31:0] sub1_reg_1835;
wire   [31:0] grp_fu_301_p2;
reg   [31:0] dc_6_reg_1840;
wire    ap_CS_fsm_state24;
wire   [31:0] grp_fu_305_p2;
reg   [31:0] dc_9_reg_1846;
wire   [31:0] data_14_fu_980_p1;
reg   [31:0] data_14_reg_1852;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln167_2_fu_991_p2;
reg   [0:0] icmp_ln167_2_reg_1857;
reg   [0:0] tmp_17_reg_1863;
wire   [0:0] icmp_ln170_2_fu_1005_p2;
reg   [0:0] icmp_ln170_2_reg_1868;
wire   [31:0] data_15_fu_1027_p1;
reg   [31:0] data_15_reg_1883;
wire   [0:0] icmp_ln167_3_fu_1038_p2;
reg   [0:0] icmp_ln167_3_reg_1888;
reg   [0:0] tmp_20_reg_1894;
wire   [0:0] icmp_ln170_3_fu_1052_p2;
reg   [0:0] icmp_ln170_3_reg_1899;
wire   [31:0] dc_7_fu_1149_p9;
reg   [31:0] dc_7_reg_1914;
wire    ap_CS_fsm_state26;
wire   [31:0] dc_10_fu_1243_p9;
reg   [31:0] dc_10_reg_1919;
reg   [55:0] phi_ln8_reg_282;
wire   [63:0] zext_ln179_fu_460_p1;
wire   [63:0] zext_ln179_1_fu_506_p1;
wire   [63:0] zext_ln179_2_fu_1021_p1;
wire   [63:0] zext_ln179_3_fu_1068_p1;
wire  signed [63:0] sext_ln8_fu_368_p1;
reg    mask_table_ce1_local;
reg   [4:0] mask_table_address1_local;
reg    mask_table_ce0_local;
reg   [4:0] mask_table_address0_local;
reg    one_half_table_ce1_local;
reg   [4:0] one_half_table_address1_local;
reg    one_half_table_ce0_local;
reg   [4:0] one_half_table_address0_local;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state22;
reg   [31:0] grp_fu_309_p0;
wire    ap_CS_fsm_state14;
wire   [18:0] shl_ln8_fu_322_p3;
wire   [63:0] zext_ln8_fu_330_p1;
wire   [63:0] add_ln8_fu_334_p2;
wire   [5:0] shl_ln8_1_fu_389_p3;
wire   [119:0] tmp_fu_382_p3;
wire   [119:0] zext_ln8_1_fu_396_p1;
wire   [119:0] lshr_ln8_fu_400_p2;
wire   [7:0] xs_exp_4_fu_420_p4;
wire   [4:0] index_fu_450_p4;
wire   [7:0] xs_exp_5_fu_466_p4;
wire   [4:0] index_1_fu_496_p4;
wire   [31:0] t_fu_518_p3;
wire   [31:0] one_half_cast_i_fu_529_p1;
wire   [31:0] data_2_fu_533_p2;
wire   [22:0] trunc_ln301_fu_538_p1;
wire   [22:0] xor_ln184_fu_542_p2;
wire   [8:0] tmp_8_i_fu_554_p4;
wire   [22:0] xs_sig_fu_548_p2;
wire   [31:0] t_11_fu_564_p3;
wire   [0:0] xor_ln167_fu_576_p2;
wire   [0:0] and_ln170_fu_581_p2;
wire   [31:0] dc_1_fu_593_p2;
wire   [31:0] dc_1_fu_593_p4;
wire   [31:0] dc_1_fu_593_p6;
wire   [31:0] dc_1_fu_593_p7;
wire   [1:0] dc_1_fu_593_p8;
wire   [31:0] dc_1_fu_593_p9;
wire   [31:0] data_fu_613_p1;
wire   [22:0] trunc_ln342_fu_633_p1;
wire   [24:0] mantissa_fu_637_p4;
wire   [7:0] xs_exp_fu_625_p3;
wire   [8:0] zext_ln317_fu_651_p1;
wire   [8:0] add_ln317_fu_655_p2;
wire   [7:0] sub_ln18_fu_669_p2;
wire   [0:0] tmp_11_fu_661_p3;
wire  signed [8:0] sext_ln18_fu_675_p1;
wire   [8:0] select_ln18_fu_679_p3;
wire  signed [31:0] sext_ln18_1_fu_687_p1;
wire   [78:0] zext_ln15_fu_647_p1;
wire   [78:0] zext_ln18_fu_691_p1;
wire   [78:0] lshr_ln18_fu_695_p2;
wire   [78:0] shl_ln18_fu_701_p2;
wire   [31:0] tmp_2_fu_707_p4;
wire   [31:0] tmp_3_fu_717_p4;
wire   [31:0] val_fu_727_p3;
wire   [0:0] xs_sign_fu_617_p3;
wire   [31:0] result_2_fu_735_p2;
wire   [31:0] t_12_fu_749_p3;
wire   [31:0] one_half_cast_i18_fu_760_p1;
wire   [31:0] data_4_fu_764_p2;
wire   [22:0] trunc_ln301_1_fu_769_p1;
wire   [22:0] xor_ln184_1_fu_773_p2;
wire   [8:0] tmp_8_i1_fu_785_p4;
wire   [22:0] xs_sig_1_fu_779_p2;
wire   [31:0] t_13_fu_795_p3;
wire   [0:0] xor_ln167_1_fu_807_p2;
wire   [0:0] and_ln170_1_fu_812_p2;
wire   [31:0] dc_4_fu_824_p2;
wire   [31:0] dc_4_fu_824_p4;
wire   [31:0] dc_4_fu_824_p6;
wire   [31:0] dc_4_fu_824_p7;
wire   [1:0] dc_4_fu_824_p8;
wire   [31:0] dc_4_fu_824_p9;
wire   [31:0] data_5_fu_844_p1;
wire   [22:0] trunc_ln342_1_fu_864_p1;
wire   [24:0] mantissa_1_fu_868_p4;
wire   [7:0] xs_exp_1_fu_856_p3;
wire   [8:0] zext_ln317_1_fu_882_p1;
wire   [8:0] add_ln317_1_fu_886_p2;
wire   [7:0] sub_ln18_1_fu_900_p2;
wire   [0:0] tmp_14_fu_892_p3;
wire  signed [8:0] sext_ln18_2_fu_906_p1;
wire   [8:0] select_ln18_2_fu_910_p3;
wire  signed [31:0] sext_ln18_3_fu_918_p1;
wire   [78:0] zext_ln15_1_fu_878_p1;
wire   [78:0] zext_ln18_1_fu_922_p1;
wire   [78:0] lshr_ln18_1_fu_926_p2;
wire   [78:0] shl_ln18_1_fu_932_p2;
wire   [31:0] tmp_4_fu_938_p4;
wire   [31:0] tmp_5_fu_948_p4;
wire   [31:0] val_1_fu_958_p3;
wire   [0:0] xs_sign_1_fu_848_p3;
wire   [31:0] result_5_fu_966_p2;
wire   [7:0] xs_exp_6_fu_983_p3;
wire   [4:0] index_2_fu_1011_p4;
wire   [7:0] xs_exp_7_fu_1030_p3;
wire   [4:0] index_3_fu_1058_p4;
wire   [31:0] t_14_fu_1074_p3;
wire   [31:0] one_half_cast_i43_fu_1085_p1;
wire   [31:0] data_7_fu_1089_p2;
wire   [22:0] trunc_ln301_2_fu_1094_p1;
wire   [22:0] xor_ln184_2_fu_1098_p2;
wire   [8:0] tmp_8_i2_fu_1110_p4;
wire   [22:0] xs_sig_2_fu_1104_p2;
wire   [31:0] t_15_fu_1120_p3;
wire   [0:0] xor_ln167_2_fu_1132_p2;
wire   [0:0] and_ln170_2_fu_1137_p2;
wire   [31:0] dc_7_fu_1149_p2;
wire   [31:0] dc_7_fu_1149_p6;
wire   [31:0] dc_7_fu_1149_p7;
wire   [1:0] dc_7_fu_1149_p8;
wire   [31:0] t_16_fu_1168_p3;
wire   [31:0] one_half_cast_i68_fu_1179_p1;
wire   [31:0] data_10_fu_1183_p2;
wire   [22:0] trunc_ln301_3_fu_1188_p1;
wire   [22:0] xor_ln184_3_fu_1192_p2;
wire   [8:0] tmp_8_i3_fu_1204_p4;
wire   [22:0] xs_sig_3_fu_1198_p2;
wire   [31:0] t_17_fu_1214_p3;
wire   [0:0] xor_ln167_3_fu_1226_p2;
wire   [0:0] and_ln170_3_fu_1231_p2;
wire   [31:0] dc_10_fu_1243_p2;
wire   [31:0] dc_10_fu_1243_p6;
wire   [31:0] dc_10_fu_1243_p7;
wire   [1:0] dc_10_fu_1243_p8;
wire   [31:0] sub_ln15_fu_1269_p2;
wire   [30:0] lshr_ln15_1_fu_1274_p4;
wire   [0:0] tmp_15_fu_1262_p3;
wire   [30:0] sub_ln15_1_fu_1284_p2;
wire   [30:0] lshr_ln15_2_fu_1290_p4;
wire   [30:0] select_ln15_fu_1299_p3;
wire  signed [31:0] sext_ln15_fu_1307_p1;
wire   [31:0] sub_ln16_fu_1323_p2;
wire   [30:0] lshr_ln16_1_fu_1328_p4;
wire   [0:0] tmp_16_fu_1316_p3;
wire   [30:0] sub_ln16_1_fu_1338_p2;
wire   [30:0] lshr_ln16_2_fu_1344_p4;
wire   [30:0] select_ln16_fu_1353_p3;
wire  signed [31:0] sext_ln16_fu_1361_p1;
wire   [31:0] info_Y_min_fu_1311_p2;
wire   [31:0] add_ln17_fu_1370_p2;
wire   [31:0] info_X_min_fu_1365_p2;
wire   [31:0] add_ln18_fu_1381_p2;
wire   [31:0] data_8_fu_1392_p1;
wire   [22:0] trunc_ln342_2_fu_1411_p1;
wire   [24:0] mantissa_2_fu_1415_p4;
wire   [7:0] xs_exp_2_fu_1403_p3;
wire   [8:0] zext_ln317_2_fu_1429_p1;
wire   [8:0] add_ln317_2_fu_1433_p2;
wire   [7:0] sub_ln18_2_fu_1447_p2;
wire   [0:0] tmp_19_fu_1439_p3;
wire  signed [8:0] sext_ln18_4_fu_1453_p1;
wire   [8:0] select_ln18_4_fu_1457_p3;
wire  signed [31:0] sext_ln18_5_fu_1465_p1;
wire   [78:0] zext_ln15_2_fu_1425_p1;
wire   [78:0] zext_ln18_2_fu_1469_p1;
wire   [78:0] lshr_ln18_2_fu_1473_p2;
wire   [78:0] shl_ln18_2_fu_1479_p2;
wire   [31:0] tmp_6_fu_1485_p4;
wire   [31:0] tmp_7_fu_1495_p4;
wire   [31:0] val_2_fu_1505_p3;
wire   [0:0] xs_sign_2_fu_1395_p3;
wire   [31:0] result_9_fu_1513_p2;
wire   [31:0] data_11_fu_1527_p1;
wire   [22:0] trunc_ln342_3_fu_1546_p1;
wire   [24:0] mantissa_3_fu_1550_p4;
wire   [7:0] xs_exp_3_fu_1538_p3;
wire   [8:0] zext_ln317_3_fu_1564_p1;
wire   [8:0] add_ln317_3_fu_1568_p2;
wire   [7:0] sub_ln18_3_fu_1582_p2;
wire   [0:0] tmp_22_fu_1574_p3;
wire  signed [8:0] sext_ln18_6_fu_1588_p1;
wire   [8:0] select_ln18_6_fu_1592_p3;
wire  signed [31:0] sext_ln18_7_fu_1600_p1;
wire   [78:0] zext_ln15_3_fu_1560_p1;
wire   [78:0] zext_ln18_3_fu_1604_p1;
wire   [78:0] lshr_ln18_3_fu_1608_p2;
wire   [78:0] shl_ln18_3_fu_1614_p2;
wire   [31:0] tmp_8_fu_1620_p4;
wire   [31:0] tmp_9_fu_1630_p4;
wire   [31:0] val_3_fu_1640_p3;
wire   [0:0] xs_sign_3_fu_1530_p3;
wire   [31:0] result_10_fu_1648_p2;
wire   [31:0] result_fu_1654_p3;
wire   [31:0] result_14_fu_1519_p3;
wire   [31:0] info_Y_max_fu_1376_p2;
wire   [31:0] info_X_max_fu_1387_p2;
reg   [26:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire  signed [1:0] dc_1_fu_593_p1;
wire   [1:0] dc_1_fu_593_p3;
wire   [1:0] dc_1_fu_593_p5;
wire  signed [1:0] dc_4_fu_824_p1;
wire   [1:0] dc_4_fu_824_p3;
wire   [1:0] dc_4_fu_824_p5;
wire  signed [1:0] dc_7_fu_1149_p1;
wire   [1:0] dc_7_fu_1149_p3;
wire   [1:0] dc_7_fu_1149_p5;
wire  signed [1:0] dc_10_fu_1243_p1;
wire   [1:0] dc_10_fu_1243_p3;
wire   [1:0] dc_10_fu_1243_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 27'd1;
end

reconstruct_getLocalImages_single_mask_table_ROM_AUTO_1R #(
    .DataWidth( 23 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
mask_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mask_table_address0_local),
    .ce0(mask_table_ce0_local),
    .q0(mask_table_q0),
    .address1(mask_table_address1_local),
    .ce1(mask_table_ce1_local),
    .q1(mask_table_q1)
);

reconstruct_getLocalImages_single_one_half_table_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
one_half_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(one_half_table_address0_local),
    .ce0(one_half_table_ce0_local),
    .q0(one_half_table_q0),
    .address1(one_half_table_address1_local),
    .ce1(one_half_table_ce1_local),
    .q1(one_half_table_q1)
);

reconstruct_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(coord_x_reg_1801),
    .din1(reg_315),
    .ce(1'b1),
    .dout(grp_fu_293_p2)
);

reconstruct_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(coord_y_reg_1806),
    .din1(conv2_reg_1825),
    .ce(1'b1),
    .dout(grp_fu_297_p2)
);

reconstruct_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_reg_1830),
    .din1(reg_315),
    .ce(1'b1),
    .dout(grp_fu_301_p2)
);

reconstruct_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub1_reg_1835),
    .din1(reg_315),
    .ce(1'b1),
    .dout(grp_fu_305_p2)
);

reconstruct_sitofp_32ns_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_4_no_dsp_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_309_p0),
    .ce(1'b1),
    .dout(grp_fu_309_p1)
);

reconstruct_sitofp_32ns_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_4_no_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(result_12_reg_1811),
    .ce(1'b1),
    .dout(grp_fu_312_p1)
);

(* dissolve_hierarchy = "yes" *) reconstruct_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U9(
    .din0(dc_1_fu_593_p2),
    .din1(dc_1_fu_593_p4),
    .din2(dc_1_fu_593_p6),
    .def(dc_1_fu_593_p7),
    .sel(dc_1_fu_593_p8),
    .dout(dc_1_fu_593_p9)
);

(* dissolve_hierarchy = "yes" *) reconstruct_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U10(
    .din0(dc_4_fu_824_p2),
    .din1(dc_4_fu_824_p4),
    .din2(dc_4_fu_824_p6),
    .def(dc_4_fu_824_p7),
    .sel(dc_4_fu_824_p8),
    .dout(dc_4_fu_824_p9)
);

(* dissolve_hierarchy = "yes" *) reconstruct_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U11(
    .din0(dc_7_fu_1149_p2),
    .din1(dc_6_reg_1840),
    .din2(dc_7_fu_1149_p6),
    .def(dc_7_fu_1149_p7),
    .sel(dc_7_fu_1149_p8),
    .dout(dc_7_fu_1149_p9)
);

(* dissolve_hierarchy = "yes" *) reconstruct_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U12(
    .din0(dc_10_fu_1243_p2),
    .din1(dc_9_reg_1846),
    .din2(dc_10_fu_1243_p6),
    .def(dc_10_fu_1243_p7),
    .sel(dc_10_fu_1243_p8),
    .dout(dc_10_fu_1243_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state27) & (localImages_full_n == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_atomLocations_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        atomLocations_addr_read_reg_1727 <= m_axi_atomLocations_0_RDATA;
        projShape0_read_reg_1714 <= projShape0;
        projShape1_read_reg_1706 <= projShape1;
        psfSupersample_read_reg_1722 <= psfSupersample;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        conv2_reg_1825 <= grp_fu_312_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        coord_x_reg_1801 <= coord_x_fu_512_p1;
        coord_y_reg_1806 <= coord_y_fu_515_p1;
        result_12_reg_1811 <= result_12_fu_741_p3;
        result_13_reg_1818 <= result_13_fu_972_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        data_12_reg_1743 <= {{lshr_ln8_fu_400_p2[63:32]}};
        data_13_reg_1737 <= data_13_fu_406_p1;
        icmp_ln167_1_reg_1775 <= icmp_ln167_1_fu_476_p2;
        icmp_ln167_reg_1749 <= icmp_ln167_fu_430_p2;
        icmp_ln170_1_reg_1786 <= icmp_ln170_1_fu_490_p2;
        icmp_ln170_reg_1760 <= icmp_ln170_fu_444_p2;
        tmp_12_reg_1781 <= lshr_ln8_fu_400_p2[32'd31];
        tmp_1_reg_1755 <= lshr_ln8_fu_400_p2[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        data_14_reg_1852 <= data_14_fu_980_p1;
        data_15_reg_1883 <= data_15_fu_1027_p1;
        icmp_ln167_2_reg_1857 <= icmp_ln167_2_fu_991_p2;
        icmp_ln167_3_reg_1888 <= icmp_ln167_3_fu_1038_p2;
        icmp_ln170_2_reg_1868 <= icmp_ln170_2_fu_1005_p2;
        icmp_ln170_3_reg_1899 <= icmp_ln170_3_fu_1052_p2;
        tmp_17_reg_1863 <= data_14_fu_980_p1[32'd31];
        tmp_20_reg_1894 <= data_15_fu_1027_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        dc_10_reg_1919 <= dc_10_fu_1243_p9;
        dc_7_reg_1914 <= dc_7_fu_1149_p9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        dc_6_reg_1840 <= grp_fu_301_p2;
        dc_9_reg_1846 <= grp_fu_305_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        icmp_ln8_reg_1686 <= icmp_ln8_fu_344_p2;
        select_ln8_reg_1690[1 : 0] <= select_ln8_fu_350_p3[1 : 0];
        trunc_ln8_1_reg_1695 <= {{add_ln8_fu_334_p2[63:3]}};
        trunc_ln8_reg_1681 <= trunc_ln8_fu_340_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_atomLocations_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        phi_ln8_reg_282 <= trunc_ln8_2_fu_378_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state17))) begin
        reg_315 <= grp_fu_309_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sub1_reg_1835 <= grp_fu_297_p2;
        sub_reg_1830 <= grp_fu_293_p2;
    end
end

always @ (*) begin
    if ((m_axi_atomLocations_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_atomLocations_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((localImages_full_n == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_atomLocations_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) & (localImages_full_n == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) & (localImages_full_n == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        atomLocations_blk_n_AR = m_axi_atomLocations_0_ARREADY;
    end else begin
        atomLocations_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        atomLocations_blk_n_R = m_axi_atomLocations_0_RVALID;
    end else begin
        atomLocations_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_309_p0 = psfSupersample_read_reg_1722;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_309_p0 = result_13_reg_1818;
    end else begin
        grp_fu_309_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        localImages_blk_n = localImages_full_n;
    end else begin
        localImages_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) & (localImages_full_n == 1'b1))) begin
        localImages_write = 1'b1;
    end else begin
        localImages_write = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_atomLocations_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_atomLocations_0_ARVALID = 1'b1;
    end else begin
        m_axi_atomLocations_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((m_axi_atomLocations_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((m_axi_atomLocations_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_atomLocations_0_RREADY = 1'b1;
    end else begin
        m_axi_atomLocations_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        mask_table_address0_local = zext_ln179_3_fu_1068_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mask_table_address0_local = zext_ln179_1_fu_506_p1;
    end else begin
        mask_table_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        mask_table_address1_local = zext_ln179_2_fu_1021_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mask_table_address1_local = zext_ln179_fu_460_p1;
    end else begin
        mask_table_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state12))) begin
        mask_table_ce0_local = 1'b1;
    end else begin
        mask_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state12))) begin
        mask_table_ce1_local = 1'b1;
    end else begin
        mask_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        one_half_table_address0_local = zext_ln179_3_fu_1068_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        one_half_table_address0_local = zext_ln179_1_fu_506_p1;
    end else begin
        one_half_table_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        one_half_table_address1_local = zext_ln179_2_fu_1021_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        one_half_table_address1_local = zext_ln179_fu_460_p1;
    end else begin
        one_half_table_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state12))) begin
        one_half_table_ce0_local = 1'b1;
    end else begin
        one_half_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state12))) begin
        one_half_table_ce1_local = 1'b1;
    end else begin
        one_half_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_atomLocations_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((m_axi_atomLocations_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln8_reg_1686 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((m_axi_atomLocations_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln8_reg_1686 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((m_axi_atomLocations_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((1'b1 == ap_CS_fsm_state27) & (localImages_full_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln17_fu_1370_p2 = ($signed(info_Y_min_fu_1311_p2) + $signed(32'd4294967295));

assign add_ln18_fu_1381_p2 = ($signed(info_X_min_fu_1365_p2) + $signed(32'd4294967295));

assign add_ln317_1_fu_886_p2 = ($signed(zext_ln317_1_fu_882_p1) + $signed(9'd385));

assign add_ln317_2_fu_1433_p2 = ($signed(zext_ln317_2_fu_1429_p1) + $signed(9'd385));

assign add_ln317_3_fu_1568_p2 = ($signed(zext_ln317_3_fu_1564_p1) + $signed(9'd385));

assign add_ln317_fu_655_p2 = ($signed(zext_ln317_fu_651_p1) + $signed(9'd385));

assign add_ln8_fu_334_p2 = (zext_ln8_fu_330_p1 + atomLocations1);

assign and_ln170_1_fu_812_p2 = (xor_ln167_1_fu_807_p2 & icmp_ln170_1_reg_1786);

assign and_ln170_2_fu_1137_p2 = (xor_ln167_2_fu_1132_p2 & icmp_ln170_2_reg_1868);

assign and_ln170_3_fu_1231_p2 = (xor_ln167_3_fu_1226_p2 & icmp_ln170_3_reg_1899);

assign and_ln170_fu_581_p2 = (xor_ln167_fu_576_p2 & icmp_ln170_reg_1760);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign coord_x_fu_512_p1 = data_13_reg_1737;

assign coord_y_fu_515_p1 = data_12_reg_1743;

assign data_10_fu_1183_p2 = (data_15_reg_1883 + one_half_cast_i68_fu_1179_p1);

assign data_11_fu_1527_p1 = dc_10_reg_1919;

assign data_13_fu_406_p1 = lshr_ln8_fu_400_p2[31:0];

assign data_14_fu_980_p1 = dc_6_reg_1840;

assign data_15_fu_1027_p1 = dc_9_reg_1846;

assign data_2_fu_533_p2 = (data_12_reg_1743 + one_half_cast_i_fu_529_p1);

assign data_4_fu_764_p2 = (data_13_reg_1737 + one_half_cast_i18_fu_760_p1);

assign data_5_fu_844_p1 = dc_4_fu_824_p9;

assign data_7_fu_1089_p2 = (data_14_reg_1852 + one_half_cast_i43_fu_1085_p1);

assign data_8_fu_1392_p1 = dc_7_reg_1914;

assign data_fu_613_p1 = dc_1_fu_593_p9;

assign dc_10_fu_1243_p2 = t_16_fu_1168_p3;

assign dc_10_fu_1243_p6 = t_17_fu_1214_p3;

assign dc_10_fu_1243_p7 = 'bx;

assign dc_10_fu_1243_p8 = {{icmp_ln167_3_reg_1888}, {and_ln170_3_fu_1231_p2}};

assign dc_1_fu_593_p2 = t_fu_518_p3;

assign dc_1_fu_593_p4 = data_12_reg_1743;

assign dc_1_fu_593_p6 = t_11_fu_564_p3;

assign dc_1_fu_593_p7 = 'bx;

assign dc_1_fu_593_p8 = {{icmp_ln167_reg_1749}, {and_ln170_fu_581_p2}};

assign dc_4_fu_824_p2 = t_12_fu_749_p3;

assign dc_4_fu_824_p4 = data_13_reg_1737;

assign dc_4_fu_824_p6 = t_13_fu_795_p3;

assign dc_4_fu_824_p7 = 'bx;

assign dc_4_fu_824_p8 = {{icmp_ln167_1_reg_1775}, {and_ln170_1_fu_812_p2}};

assign dc_7_fu_1149_p2 = t_14_fu_1074_p3;

assign dc_7_fu_1149_p6 = t_15_fu_1120_p3;

assign dc_7_fu_1149_p7 = 'bx;

assign dc_7_fu_1149_p8 = {{icmp_ln167_2_reg_1857}, {and_ln170_2_fu_1137_p2}};

assign icmp_ln167_1_fu_476_p2 = ((xs_exp_5_fu_466_p4 < 8'd126) ? 1'b1 : 1'b0);

assign icmp_ln167_2_fu_991_p2 = ((xs_exp_6_fu_983_p3 < 8'd126) ? 1'b1 : 1'b0);

assign icmp_ln167_3_fu_1038_p2 = ((xs_exp_7_fu_1030_p3 < 8'd126) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_430_p2 = ((xs_exp_4_fu_420_p4 < 8'd126) ? 1'b1 : 1'b0);

assign icmp_ln170_1_fu_490_p2 = ((xs_exp_5_fu_466_p4 > 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln170_2_fu_1005_p2 = ((xs_exp_6_fu_983_p3 > 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln170_3_fu_1052_p2 = ((xs_exp_7_fu_1030_p3 > 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln170_fu_444_p2 = ((xs_exp_4_fu_420_p4 > 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_344_p2 = ((trunc_ln8_fu_340_p1 != 3'd0) ? 1'b1 : 1'b0);

assign index_1_fu_496_p4 = {{lshr_ln8_fu_400_p2[27:23]}};

assign index_2_fu_1011_p4 = {{data_14_fu_980_p1[27:23]}};

assign index_3_fu_1058_p4 = {{data_15_fu_1027_p1[27:23]}};

assign index_fu_450_p4 = {{lshr_ln8_fu_400_p2[59:55]}};

assign info_X_max_fu_1387_p2 = (add_ln18_fu_1381_p2 + projShape1_read_reg_1706);

assign info_X_min_fu_1365_p2 = ($signed(result_13_reg_1818) - $signed(sext_ln16_fu_1361_p1));

assign info_Y_max_fu_1376_p2 = (add_ln17_fu_1370_p2 + projShape0_read_reg_1714);

assign info_Y_min_fu_1311_p2 = ($signed(result_12_reg_1811) - $signed(sext_ln15_fu_1307_p1));

assign localImages_din = {{{{{{{{result_fu_1654_p3}, {result_14_fu_1519_p3}}, {info_Y_max_fu_1376_p2}}, {info_X_max_fu_1387_p2}}, {info_Y_min_fu_1311_p2}}, {info_X_min_fu_1365_p2}}, {result_12_reg_1811}}, {result_13_reg_1818}};

assign lshr_ln15_1_fu_1274_p4 = {{sub_ln15_fu_1269_p2[31:1]}};

assign lshr_ln15_2_fu_1290_p4 = {{projShape0_read_reg_1714[31:1]}};

assign lshr_ln16_1_fu_1328_p4 = {{sub_ln16_fu_1323_p2[31:1]}};

assign lshr_ln16_2_fu_1344_p4 = {{projShape1_read_reg_1706[31:1]}};

assign lshr_ln18_1_fu_926_p2 = zext_ln15_1_fu_878_p1 >> zext_ln18_1_fu_922_p1;

assign lshr_ln18_2_fu_1473_p2 = zext_ln15_2_fu_1425_p1 >> zext_ln18_2_fu_1469_p1;

assign lshr_ln18_3_fu_1608_p2 = zext_ln15_3_fu_1560_p1 >> zext_ln18_3_fu_1604_p1;

assign lshr_ln18_fu_695_p2 = zext_ln15_fu_647_p1 >> zext_ln18_fu_691_p1;

assign lshr_ln8_fu_400_p2 = tmp_fu_382_p3 >> zext_ln8_1_fu_396_p1;

assign m_axi_atomLocations_0_ARADDR = sext_ln8_fu_368_p1;

assign m_axi_atomLocations_0_ARBURST = 2'd0;

assign m_axi_atomLocations_0_ARCACHE = 4'd0;

assign m_axi_atomLocations_0_ARID = 1'd0;

assign m_axi_atomLocations_0_ARLEN = select_ln8_reg_1690;

assign m_axi_atomLocations_0_ARLOCK = 2'd0;

assign m_axi_atomLocations_0_ARPROT = 3'd0;

assign m_axi_atomLocations_0_ARQOS = 4'd0;

assign m_axi_atomLocations_0_ARREGION = 4'd0;

assign m_axi_atomLocations_0_ARSIZE = 3'd0;

assign m_axi_atomLocations_0_ARUSER = 1'd0;

assign m_axi_atomLocations_0_AWADDR = 64'd0;

assign m_axi_atomLocations_0_AWBURST = 2'd0;

assign m_axi_atomLocations_0_AWCACHE = 4'd0;

assign m_axi_atomLocations_0_AWID = 1'd0;

assign m_axi_atomLocations_0_AWLEN = 32'd0;

assign m_axi_atomLocations_0_AWLOCK = 2'd0;

assign m_axi_atomLocations_0_AWPROT = 3'd0;

assign m_axi_atomLocations_0_AWQOS = 4'd0;

assign m_axi_atomLocations_0_AWREGION = 4'd0;

assign m_axi_atomLocations_0_AWSIZE = 3'd0;

assign m_axi_atomLocations_0_AWUSER = 1'd0;

assign m_axi_atomLocations_0_AWVALID = 1'b0;

assign m_axi_atomLocations_0_BREADY = 1'b0;

assign m_axi_atomLocations_0_WDATA = 64'd0;

assign m_axi_atomLocations_0_WID = 1'd0;

assign m_axi_atomLocations_0_WLAST = 1'b0;

assign m_axi_atomLocations_0_WSTRB = 8'd0;

assign m_axi_atomLocations_0_WUSER = 1'd0;

assign m_axi_atomLocations_0_WVALID = 1'b0;

assign mantissa_1_fu_868_p4 = {{{{1'd1}, {trunc_ln342_1_fu_864_p1}}}, {1'd0}};

assign mantissa_2_fu_1415_p4 = {{{{1'd1}, {trunc_ln342_2_fu_1411_p1}}}, {1'd0}};

assign mantissa_3_fu_1550_p4 = {{{{1'd1}, {trunc_ln342_3_fu_1546_p1}}}, {1'd0}};

assign mantissa_fu_637_p4 = {{{{1'd1}, {trunc_ln342_fu_633_p1}}}, {1'd0}};

assign one_half_cast_i18_fu_760_p1 = one_half_table_q0;

assign one_half_cast_i43_fu_1085_p1 = one_half_table_q1;

assign one_half_cast_i68_fu_1179_p1 = one_half_table_q0;

assign one_half_cast_i_fu_529_p1 = one_half_table_q1;

assign result_10_fu_1648_p2 = (32'd0 - val_3_fu_1640_p3);

assign result_12_fu_741_p3 = ((xs_sign_fu_617_p3[0:0] == 1'b1) ? result_2_fu_735_p2 : val_fu_727_p3);

assign result_13_fu_972_p3 = ((xs_sign_1_fu_848_p3[0:0] == 1'b1) ? result_5_fu_966_p2 : val_1_fu_958_p3);

assign result_14_fu_1519_p3 = ((xs_sign_2_fu_1395_p3[0:0] == 1'b1) ? result_9_fu_1513_p2 : val_2_fu_1505_p3);

assign result_2_fu_735_p2 = (32'd0 - val_fu_727_p3);

assign result_5_fu_966_p2 = (32'd0 - val_1_fu_958_p3);

assign result_9_fu_1513_p2 = (32'd0 - val_2_fu_1505_p3);

assign result_fu_1654_p3 = ((xs_sign_3_fu_1530_p3[0:0] == 1'b1) ? result_10_fu_1648_p2 : val_3_fu_1640_p3);

assign select_ln15_fu_1299_p3 = ((tmp_15_fu_1262_p3[0:0] == 1'b1) ? sub_ln15_1_fu_1284_p2 : lshr_ln15_2_fu_1290_p4);

assign select_ln16_fu_1353_p3 = ((tmp_16_fu_1316_p3[0:0] == 1'b1) ? sub_ln16_1_fu_1338_p2 : lshr_ln16_2_fu_1344_p4);

assign select_ln18_2_fu_910_p3 = ((tmp_14_fu_892_p3[0:0] == 1'b1) ? sext_ln18_2_fu_906_p1 : add_ln317_1_fu_886_p2);

assign select_ln18_4_fu_1457_p3 = ((tmp_19_fu_1439_p3[0:0] == 1'b1) ? sext_ln18_4_fu_1453_p1 : add_ln317_2_fu_1433_p2);

assign select_ln18_6_fu_1592_p3 = ((tmp_22_fu_1574_p3[0:0] == 1'b1) ? sext_ln18_6_fu_1588_p1 : add_ln317_3_fu_1568_p2);

assign select_ln18_fu_679_p3 = ((tmp_11_fu_661_p3[0:0] == 1'b1) ? sext_ln18_fu_675_p1 : add_ln317_fu_655_p2);

assign select_ln8_fu_350_p3 = ((icmp_ln8_fu_344_p2[0:0] == 1'b1) ? 64'd2 : 64'd1);

assign sext_ln15_fu_1307_p1 = $signed(select_ln15_fu_1299_p3);

assign sext_ln16_fu_1361_p1 = $signed(select_ln16_fu_1353_p3);

assign sext_ln18_1_fu_687_p1 = $signed(select_ln18_fu_679_p3);

assign sext_ln18_2_fu_906_p1 = $signed(sub_ln18_1_fu_900_p2);

assign sext_ln18_3_fu_918_p1 = $signed(select_ln18_2_fu_910_p3);

assign sext_ln18_4_fu_1453_p1 = $signed(sub_ln18_2_fu_1447_p2);

assign sext_ln18_5_fu_1465_p1 = $signed(select_ln18_4_fu_1457_p3);

assign sext_ln18_6_fu_1588_p1 = $signed(sub_ln18_3_fu_1582_p2);

assign sext_ln18_7_fu_1600_p1 = $signed(select_ln18_6_fu_1592_p3);

assign sext_ln18_fu_675_p1 = $signed(sub_ln18_fu_669_p2);

assign sext_ln8_fu_368_p1 = $signed(trunc_ln8_1_reg_1695);

assign shl_ln18_1_fu_932_p2 = zext_ln15_1_fu_878_p1 << zext_ln18_1_fu_922_p1;

assign shl_ln18_2_fu_1479_p2 = zext_ln15_2_fu_1425_p1 << zext_ln18_2_fu_1469_p1;

assign shl_ln18_3_fu_1614_p2 = zext_ln15_3_fu_1560_p1 << zext_ln18_3_fu_1604_p1;

assign shl_ln18_fu_701_p2 = zext_ln15_fu_647_p1 << zext_ln18_fu_691_p1;

assign shl_ln8_1_fu_389_p3 = {{trunc_ln8_reg_1681}, {3'd0}};

assign shl_ln8_fu_322_p3 = {{curr_idx}, {3'd0}};

assign sub_ln15_1_fu_1284_p2 = (31'd0 - lshr_ln15_1_fu_1274_p4);

assign sub_ln15_fu_1269_p2 = (32'd0 - projShape0_read_reg_1714);

assign sub_ln16_1_fu_1338_p2 = (31'd0 - lshr_ln16_1_fu_1328_p4);

assign sub_ln16_fu_1323_p2 = (32'd0 - projShape1_read_reg_1706);

assign sub_ln18_1_fu_900_p2 = (8'd127 - xs_exp_1_fu_856_p3);

assign sub_ln18_2_fu_1447_p2 = (8'd127 - xs_exp_2_fu_1403_p3);

assign sub_ln18_3_fu_1582_p2 = (8'd127 - xs_exp_3_fu_1538_p3);

assign sub_ln18_fu_669_p2 = (8'd127 - xs_exp_fu_625_p3);

assign t_11_fu_564_p3 = {{tmp_8_i_fu_554_p4}, {xs_sig_fu_548_p2}};

assign t_12_fu_749_p3 = {{tmp_12_reg_1781}, {31'd0}};

assign t_13_fu_795_p3 = {{tmp_8_i1_fu_785_p4}, {xs_sig_1_fu_779_p2}};

assign t_14_fu_1074_p3 = {{tmp_17_reg_1863}, {31'd0}};

assign t_15_fu_1120_p3 = {{tmp_8_i2_fu_1110_p4}, {xs_sig_2_fu_1104_p2}};

assign t_16_fu_1168_p3 = {{tmp_20_reg_1894}, {31'd0}};

assign t_17_fu_1214_p3 = {{tmp_8_i3_fu_1204_p4}, {xs_sig_3_fu_1198_p2}};

assign t_fu_518_p3 = {{tmp_1_reg_1755}, {31'd0}};

assign tmp_11_fu_661_p3 = add_ln317_fu_655_p2[32'd8];

assign tmp_14_fu_892_p3 = add_ln317_1_fu_886_p2[32'd8];

assign tmp_15_fu_1262_p3 = projShape0_read_reg_1714[32'd31];

assign tmp_16_fu_1316_p3 = projShape1_read_reg_1706[32'd31];

assign tmp_19_fu_1439_p3 = add_ln317_2_fu_1433_p2[32'd8];

assign tmp_22_fu_1574_p3 = add_ln317_3_fu_1568_p2[32'd8];

assign tmp_2_fu_707_p4 = {{lshr_ln18_fu_695_p2[55:24]}};

assign tmp_3_fu_717_p4 = {{shl_ln18_fu_701_p2[55:24]}};

assign tmp_4_fu_938_p4 = {{lshr_ln18_1_fu_926_p2[55:24]}};

assign tmp_5_fu_948_p4 = {{shl_ln18_1_fu_932_p2[55:24]}};

assign tmp_6_fu_1485_p4 = {{lshr_ln18_2_fu_1473_p2[55:24]}};

assign tmp_7_fu_1495_p4 = {{shl_ln18_2_fu_1479_p2[55:24]}};

assign tmp_8_fu_1620_p4 = {{lshr_ln18_3_fu_1608_p2[55:24]}};

assign tmp_8_i1_fu_785_p4 = {{data_4_fu_764_p2[31:23]}};

assign tmp_8_i2_fu_1110_p4 = {{data_7_fu_1089_p2[31:23]}};

assign tmp_8_i3_fu_1204_p4 = {{data_10_fu_1183_p2[31:23]}};

assign tmp_8_i_fu_554_p4 = {{data_2_fu_533_p2[31:23]}};

assign tmp_9_fu_1630_p4 = {{shl_ln18_3_fu_1614_p2[55:24]}};

assign tmp_fu_382_p3 = {{phi_ln8_reg_282}, {atomLocations_addr_read_reg_1727}};

assign trunc_ln301_1_fu_769_p1 = data_4_fu_764_p2[22:0];

assign trunc_ln301_2_fu_1094_p1 = data_7_fu_1089_p2[22:0];

assign trunc_ln301_3_fu_1188_p1 = data_10_fu_1183_p2[22:0];

assign trunc_ln301_fu_538_p1 = data_2_fu_533_p2[22:0];

assign trunc_ln342_1_fu_864_p1 = data_5_fu_844_p1[22:0];

assign trunc_ln342_2_fu_1411_p1 = data_8_fu_1392_p1[22:0];

assign trunc_ln342_3_fu_1546_p1 = data_11_fu_1527_p1[22:0];

assign trunc_ln342_fu_633_p1 = data_fu_613_p1[22:0];

assign trunc_ln8_2_fu_378_p1 = m_axi_atomLocations_0_RDATA[55:0];

assign trunc_ln8_fu_340_p1 = add_ln8_fu_334_p2[2:0];

assign val_1_fu_958_p3 = ((tmp_14_fu_892_p3[0:0] == 1'b1) ? tmp_4_fu_938_p4 : tmp_5_fu_948_p4);

assign val_2_fu_1505_p3 = ((tmp_19_fu_1439_p3[0:0] == 1'b1) ? tmp_6_fu_1485_p4 : tmp_7_fu_1495_p4);

assign val_3_fu_1640_p3 = ((tmp_22_fu_1574_p3[0:0] == 1'b1) ? tmp_8_fu_1620_p4 : tmp_9_fu_1630_p4);

assign val_fu_727_p3 = ((tmp_11_fu_661_p3[0:0] == 1'b1) ? tmp_2_fu_707_p4 : tmp_3_fu_717_p4);

assign xor_ln167_1_fu_807_p2 = (icmp_ln167_1_reg_1775 ^ 1'd1);

assign xor_ln167_2_fu_1132_p2 = (icmp_ln167_2_reg_1857 ^ 1'd1);

assign xor_ln167_3_fu_1226_p2 = (icmp_ln167_3_reg_1888 ^ 1'd1);

assign xor_ln167_fu_576_p2 = (icmp_ln167_reg_1749 ^ 1'd1);

assign xor_ln184_1_fu_773_p2 = (mask_table_q0 ^ 23'd8388607);

assign xor_ln184_2_fu_1098_p2 = (mask_table_q1 ^ 23'd8388607);

assign xor_ln184_3_fu_1192_p2 = (mask_table_q0 ^ 23'd8388607);

assign xor_ln184_fu_542_p2 = (mask_table_q1 ^ 23'd8388607);

assign xs_exp_1_fu_856_p3 = {{data_5_fu_844_p1[30:23]}};

assign xs_exp_2_fu_1403_p3 = {{data_8_fu_1392_p1[30:23]}};

assign xs_exp_3_fu_1538_p3 = {{data_11_fu_1527_p1[30:23]}};

assign xs_exp_4_fu_420_p4 = {{lshr_ln8_fu_400_p2[62:55]}};

assign xs_exp_5_fu_466_p4 = {{lshr_ln8_fu_400_p2[30:23]}};

assign xs_exp_6_fu_983_p3 = {{data_14_fu_980_p1[30:23]}};

assign xs_exp_7_fu_1030_p3 = {{data_15_fu_1027_p1[30:23]}};

assign xs_exp_fu_625_p3 = {{data_fu_613_p1[30:23]}};

assign xs_sig_1_fu_779_p2 = (xor_ln184_1_fu_773_p2 & trunc_ln301_1_fu_769_p1);

assign xs_sig_2_fu_1104_p2 = (xor_ln184_2_fu_1098_p2 & trunc_ln301_2_fu_1094_p1);

assign xs_sig_3_fu_1198_p2 = (xor_ln184_3_fu_1192_p2 & trunc_ln301_3_fu_1188_p1);

assign xs_sig_fu_548_p2 = (xor_ln184_fu_542_p2 & trunc_ln301_fu_538_p1);

assign xs_sign_1_fu_848_p3 = data_5_fu_844_p1[32'd31];

assign xs_sign_2_fu_1395_p3 = data_8_fu_1392_p1[32'd31];

assign xs_sign_3_fu_1530_p3 = data_11_fu_1527_p1[32'd31];

assign xs_sign_fu_617_p3 = data_fu_613_p1[32'd31];

assign zext_ln15_1_fu_878_p1 = mantissa_1_fu_868_p4;

assign zext_ln15_2_fu_1425_p1 = mantissa_2_fu_1415_p4;

assign zext_ln15_3_fu_1560_p1 = mantissa_3_fu_1550_p4;

assign zext_ln15_fu_647_p1 = mantissa_fu_637_p4;

assign zext_ln179_1_fu_506_p1 = index_1_fu_496_p4;

assign zext_ln179_2_fu_1021_p1 = index_2_fu_1011_p4;

assign zext_ln179_3_fu_1068_p1 = index_3_fu_1058_p4;

assign zext_ln179_fu_460_p1 = index_fu_450_p4;

assign zext_ln18_1_fu_922_p1 = $unsigned(sext_ln18_3_fu_918_p1);

assign zext_ln18_2_fu_1469_p1 = $unsigned(sext_ln18_5_fu_1465_p1);

assign zext_ln18_3_fu_1604_p1 = $unsigned(sext_ln18_7_fu_1600_p1);

assign zext_ln18_fu_691_p1 = $unsigned(sext_ln18_1_fu_687_p1);

assign zext_ln317_1_fu_882_p1 = xs_exp_1_fu_856_p3;

assign zext_ln317_2_fu_1429_p1 = xs_exp_2_fu_1403_p3;

assign zext_ln317_3_fu_1564_p1 = xs_exp_3_fu_1538_p3;

assign zext_ln317_fu_651_p1 = xs_exp_fu_625_p3;

assign zext_ln8_1_fu_396_p1 = shl_ln8_1_fu_389_p3;

assign zext_ln8_fu_330_p1 = shl_ln8_fu_322_p3;

always @ (posedge ap_clk) begin
    select_ln8_reg_1690[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //reconstruct_getLocalImages_single
