// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module reconstruct_post_process (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_emissions_0_AWVALID,
        m_axi_emissions_0_AWREADY,
        m_axi_emissions_0_AWADDR,
        m_axi_emissions_0_AWID,
        m_axi_emissions_0_AWLEN,
        m_axi_emissions_0_AWSIZE,
        m_axi_emissions_0_AWBURST,
        m_axi_emissions_0_AWLOCK,
        m_axi_emissions_0_AWCACHE,
        m_axi_emissions_0_AWPROT,
        m_axi_emissions_0_AWQOS,
        m_axi_emissions_0_AWREGION,
        m_axi_emissions_0_AWUSER,
        m_axi_emissions_0_WVALID,
        m_axi_emissions_0_WREADY,
        m_axi_emissions_0_WDATA,
        m_axi_emissions_0_WSTRB,
        m_axi_emissions_0_WLAST,
        m_axi_emissions_0_WID,
        m_axi_emissions_0_WUSER,
        m_axi_emissions_0_ARVALID,
        m_axi_emissions_0_ARREADY,
        m_axi_emissions_0_ARADDR,
        m_axi_emissions_0_ARID,
        m_axi_emissions_0_ARLEN,
        m_axi_emissions_0_ARSIZE,
        m_axi_emissions_0_ARBURST,
        m_axi_emissions_0_ARLOCK,
        m_axi_emissions_0_ARCACHE,
        m_axi_emissions_0_ARPROT,
        m_axi_emissions_0_ARQOS,
        m_axi_emissions_0_ARREGION,
        m_axi_emissions_0_ARUSER,
        m_axi_emissions_0_RVALID,
        m_axi_emissions_0_RREADY,
        m_axi_emissions_0_RDATA,
        m_axi_emissions_0_RLAST,
        m_axi_emissions_0_RID,
        m_axi_emissions_0_RFIFONUM,
        m_axi_emissions_0_RUSER,
        m_axi_emissions_0_RRESP,
        m_axi_emissions_0_BVALID,
        m_axi_emissions_0_BREADY,
        m_axi_emissions_0_BRESP,
        m_axi_emissions_0_BID,
        m_axi_emissions_0_BUSER,
        ap_ce,
        projSumUsed,
        sum,
        curr_imageProjs,
        dout
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_emissions_0_AWVALID;
input   m_axi_emissions_0_AWREADY;
output  [63:0] m_axi_emissions_0_AWADDR;
output  [0:0] m_axi_emissions_0_AWID;
output  [31:0] m_axi_emissions_0_AWLEN;
output  [2:0] m_axi_emissions_0_AWSIZE;
output  [1:0] m_axi_emissions_0_AWBURST;
output  [1:0] m_axi_emissions_0_AWLOCK;
output  [3:0] m_axi_emissions_0_AWCACHE;
output  [2:0] m_axi_emissions_0_AWPROT;
output  [3:0] m_axi_emissions_0_AWQOS;
output  [3:0] m_axi_emissions_0_AWREGION;
output  [0:0] m_axi_emissions_0_AWUSER;
output   m_axi_emissions_0_WVALID;
input   m_axi_emissions_0_WREADY;
output  [31:0] m_axi_emissions_0_WDATA;
output  [3:0] m_axi_emissions_0_WSTRB;
output   m_axi_emissions_0_WLAST;
output  [0:0] m_axi_emissions_0_WID;
output  [0:0] m_axi_emissions_0_WUSER;
output   m_axi_emissions_0_ARVALID;
input   m_axi_emissions_0_ARREADY;
output  [63:0] m_axi_emissions_0_ARADDR;
output  [0:0] m_axi_emissions_0_ARID;
output  [31:0] m_axi_emissions_0_ARLEN;
output  [2:0] m_axi_emissions_0_ARSIZE;
output  [1:0] m_axi_emissions_0_ARBURST;
output  [1:0] m_axi_emissions_0_ARLOCK;
output  [3:0] m_axi_emissions_0_ARCACHE;
output  [2:0] m_axi_emissions_0_ARPROT;
output  [3:0] m_axi_emissions_0_ARQOS;
output  [3:0] m_axi_emissions_0_ARREGION;
output  [0:0] m_axi_emissions_0_ARUSER;
input   m_axi_emissions_0_RVALID;
output   m_axi_emissions_0_RREADY;
input  [31:0] m_axi_emissions_0_RDATA;
input   m_axi_emissions_0_RLAST;
input  [0:0] m_axi_emissions_0_RID;
input  [8:0] m_axi_emissions_0_RFIFONUM;
input  [0:0] m_axi_emissions_0_RUSER;
input  [1:0] m_axi_emissions_0_RRESP;
input   m_axi_emissions_0_BVALID;
output   m_axi_emissions_0_BREADY;
input  [1:0] m_axi_emissions_0_BRESP;
input  [0:0] m_axi_emissions_0_BID;
input  [0:0] m_axi_emissions_0_BUSER;
input   ap_ce;
input  [31:0] projSumUsed;
input  [31:0] sum;
input  [31:0] curr_imageProjs;
input  [63:0] dout;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_emissions_0_AWVALID;
reg m_axi_emissions_0_WVALID;
reg m_axi_emissions_0_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    emissions_blk_n_AW;
wire    ap_block_pp0_stage0_grp1;
reg    emissions_blk_n_W;
reg    emissions_blk_n_B;
reg   [31:0] curr_imageProjs_read_reg_124;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [31:0] sum_read_reg_129;
reg   [31:0] sum_read_reg_129_pp0_iter1_reg;
reg   [31:0] sum_read_reg_129_pp0_iter2_reg;
reg   [31:0] sum_read_reg_129_pp0_iter3_reg;
reg   [31:0] sum_read_reg_129_pp0_iter4_reg;
reg   [31:0] sum_read_reg_129_pp0_iter5_reg;
reg   [31:0] sum_read_reg_129_pp0_iter6_reg;
reg   [31:0] sum_read_reg_129_pp0_iter7_reg;
reg   [31:0] sum_read_reg_129_pp0_iter8_reg;
reg   [31:0] sum_read_reg_129_pp0_iter9_reg;
reg   [31:0] projSumUsed_read_reg_134;
reg   [63:0] emissions_addr_reg_139;
reg   [63:0] emissions_addr_reg_139_pp0_iter1_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter2_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter3_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter4_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter5_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter6_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter7_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter8_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter9_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter10_reg;
reg   [63:0] emissions_addr_reg_139_pp0_iter11_reg;
wire   [31:0] grp_fu_96_p2;
reg   [31:0] div_i_reg_145;
wire   [31:0] grp_fu_92_p2;
reg   [31:0] mul_i_reg_150;
wire  signed [63:0] sext_ln204_fu_110_p1;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [61:0] trunc_ln_fu_100_p4;
reg    grp_fu_92_ce;
reg    ap_block_pp0_stage0_11001;
reg    grp_fu_96_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to17;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_done_reg = 1'b0;
end

reconstruct_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U4740(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(div_i_reg_145),
    .din1(sum_read_reg_129_pp0_iter9_reg),
    .ce(grp_fu_92_ce),
    .dout(grp_fu_92_p2)
);

reconstruct_fdiv_32ns_32ns_32_9_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_9_no_dsp_1_U4741(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(curr_imageProjs_read_reg_124),
    .din1(projSumUsed_read_reg_134),
    .ce(grp_fu_96_ce),
    .dout(grp_fu_96_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        curr_imageProjs_read_reg_124 <= curr_imageProjs;
        emissions_addr_reg_139 <= sext_ln204_fu_110_p1;
        emissions_addr_reg_139_pp0_iter1_reg <= emissions_addr_reg_139;
        projSumUsed_read_reg_134 <= projSumUsed;
        sum_read_reg_129 <= sum;
        sum_read_reg_129_pp0_iter1_reg <= sum_read_reg_129;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        div_i_reg_145 <= grp_fu_96_p2;
        emissions_addr_reg_139_pp0_iter10_reg <= emissions_addr_reg_139_pp0_iter9_reg;
        emissions_addr_reg_139_pp0_iter11_reg <= emissions_addr_reg_139_pp0_iter10_reg;
        emissions_addr_reg_139_pp0_iter2_reg <= emissions_addr_reg_139_pp0_iter1_reg;
        emissions_addr_reg_139_pp0_iter3_reg <= emissions_addr_reg_139_pp0_iter2_reg;
        emissions_addr_reg_139_pp0_iter4_reg <= emissions_addr_reg_139_pp0_iter3_reg;
        emissions_addr_reg_139_pp0_iter5_reg <= emissions_addr_reg_139_pp0_iter4_reg;
        emissions_addr_reg_139_pp0_iter6_reg <= emissions_addr_reg_139_pp0_iter5_reg;
        emissions_addr_reg_139_pp0_iter7_reg <= emissions_addr_reg_139_pp0_iter6_reg;
        emissions_addr_reg_139_pp0_iter8_reg <= emissions_addr_reg_139_pp0_iter7_reg;
        emissions_addr_reg_139_pp0_iter9_reg <= emissions_addr_reg_139_pp0_iter8_reg;
        mul_i_reg_150 <= grp_fu_92_p2;
        sum_read_reg_129_pp0_iter2_reg <= sum_read_reg_129_pp0_iter1_reg;
        sum_read_reg_129_pp0_iter3_reg <= sum_read_reg_129_pp0_iter2_reg;
        sum_read_reg_129_pp0_iter4_reg <= sum_read_reg_129_pp0_iter3_reg;
        sum_read_reg_129_pp0_iter5_reg <= sum_read_reg_129_pp0_iter4_reg;
        sum_read_reg_129_pp0_iter6_reg <= sum_read_reg_129_pp0_iter5_reg;
        sum_read_reg_129_pp0_iter7_reg <= sum_read_reg_129_pp0_iter6_reg;
        sum_read_reg_129_pp0_iter8_reg <= sum_read_reg_129_pp0_iter7_reg;
        sum_read_reg_129_pp0_iter9_reg <= sum_read_reg_129_pp0_iter8_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to17 = 1'b1;
    end else begin
        ap_idle_pp0_0to17 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to17 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        emissions_blk_n_AW = m_axi_emissions_0_AWREADY;
    end else begin
        emissions_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        emissions_blk_n_B = m_axi_emissions_0_BVALID;
    end else begin
        emissions_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        emissions_blk_n_W = m_axi_emissions_0_WREADY;
    end else begin
        emissions_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_92_ce = 1'b1;
    end else begin
        grp_fu_92_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_96_ce = 1'b1;
    end else begin
        grp_fu_96_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_emissions_0_AWVALID = 1'b1;
    end else begin
        m_axi_emissions_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_emissions_0_BREADY = 1'b1;
    end else begin
        m_axi_emissions_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_emissions_0_WVALID = 1'b1;
    end else begin
        m_axi_emissions_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (m_axi_emissions_0_BVALID == 1'b0)) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (m_axi_emissions_0_BVALID == 1'b0)) | ((m_axi_emissions_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | ((m_axi_emissions_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (m_axi_emissions_0_BVALID == 1'b0)) | ((m_axi_emissions_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | ((m_axi_emissions_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | (ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (m_axi_emissions_0_BVALID == 1'b0)) | ((m_axi_emissions_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | ((m_axi_emissions_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign m_axi_emissions_0_ARADDR = 64'd0;

assign m_axi_emissions_0_ARBURST = 2'd0;

assign m_axi_emissions_0_ARCACHE = 4'd0;

assign m_axi_emissions_0_ARID = 1'd0;

assign m_axi_emissions_0_ARLEN = 32'd0;

assign m_axi_emissions_0_ARLOCK = 2'd0;

assign m_axi_emissions_0_ARPROT = 3'd0;

assign m_axi_emissions_0_ARQOS = 4'd0;

assign m_axi_emissions_0_ARREGION = 4'd0;

assign m_axi_emissions_0_ARSIZE = 3'd0;

assign m_axi_emissions_0_ARUSER = 1'd0;

assign m_axi_emissions_0_ARVALID = 1'b0;

assign m_axi_emissions_0_AWADDR = emissions_addr_reg_139_pp0_iter11_reg;

assign m_axi_emissions_0_AWBURST = 2'd0;

assign m_axi_emissions_0_AWCACHE = 4'd0;

assign m_axi_emissions_0_AWID = 1'd0;

assign m_axi_emissions_0_AWLEN = 64'd1;

assign m_axi_emissions_0_AWLOCK = 2'd0;

assign m_axi_emissions_0_AWPROT = 3'd0;

assign m_axi_emissions_0_AWQOS = 4'd0;

assign m_axi_emissions_0_AWREGION = 4'd0;

assign m_axi_emissions_0_AWSIZE = 3'd0;

assign m_axi_emissions_0_AWUSER = 1'd0;

assign m_axi_emissions_0_RREADY = 1'b0;

assign m_axi_emissions_0_WDATA = mul_i_reg_150;

assign m_axi_emissions_0_WID = 1'd0;

assign m_axi_emissions_0_WLAST = 1'b0;

assign m_axi_emissions_0_WSTRB = 4'd15;

assign m_axi_emissions_0_WUSER = 1'd0;

assign sext_ln204_fu_110_p1 = $signed(trunc_ln_fu_100_p4);

assign trunc_ln_fu_100_p4 = {{dout[63:2]}};

endmodule //reconstruct_post_process
